### ISSUE TITLE
Status Bar is Crowded

### ISSUE THREAD

**Issue by DavidR2PA** [jobisoft/TbSync#495] opened 2021-02-05 02:55 UTC
My status bar at the bottom of the TBird window is crowded - many add-ons put stuff there without asking, usually it's OK.
However, it would be much appreciated if you could make it an option to not have TB Sync on the status bar...is this possible?

## Your environment

TbSync version: 2.20
Thunderbird version: 78.7.0 (64 bit)

[No], I have NOT installed the latest available beta version from 
https://tbsync.jobisoft.de
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
...

## Actual behavior
...

## Steps to reproduce
...

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by jobisoft** [comment] 2021-03-18 19:54
Duplicate of #504

**Closed by jobisoft** 2021-03-18 19:54 UTC
