### ISSUE TITLE
Don't see the busy/free blocks Outlook.Office365

### ISSUE THREAD

**Issue by MeP3aBeu** [jobisoft/TbSync#160] opened 2018-10-27 13:54 UTC
ArchLinux
TbSync version: 0.7.16
Thunderbird version: 60.2.1

## Expected behavior
When I check the free/busy time blocks in "Invite Attendees" I expect to see them for the contacts from my company. We use outlook.office365.

## Actual behavior
Doesn't show the busy time blocks.

## Steps to reproduce
Create the new event for the corporate calendar. Invite the person from the company and press "Invite Attendees".

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by jobisoft** [comment] 2018-10-27 14:13
Duplicate of https://github.com/jobisoft/TbSync/issues/141

**Closed by jobisoft** 2018-10-27 14:13 UTC
