### ISSUE TITLE
Google Contact labels not synced with Thunderbird lists or Category manager add-on

### ISSUE THREAD

**Issue by entodoays** [jobisoft/TbSync#441] opened 2020-09-30 08:58 UTC
## Your environment

TbSync version: 68.10.0 (64-bit)
Thunderbird version: 2.12

No, I have installed the latest available beta version from https://tbsync.jobisoft.de

## Expected behavior
Google Contacts labels are synced as Thunderbird lists (or categories in category manager add-on) and vice versa

## Actual behavior
Google Contacts labels are ignored.
Any lists created in Thunderbird get emptied.

## Steps to reproduce
Simply synchronise

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by jobisoft** [comment] 2020-09-30 10:23
Duplicate of https://github.com/jobisoft/TbSync/issues/403

**Closed by jobisoft** 2020-09-30 10:23 UTC
