### ISSUE TITLE
Problems syncing imported data

### ISSUE THREAD

**Issue by xj25vm** [jobisoft/TbSync#26] opened 2017-12-08 21:15 UTC
I can't work out from the description if TBSync is supposed to do a two way sync? I've got it configured and connected to a Horde back end, and it has downloaded data from Horde. But it doesn't seem to be pushing anything back from Thunderbird to Horde. Is it supposed to be able to, or not? Thank you

Edit: checking the TBSync account manager, I can see against the calendar status: "status.js-error-in-calendarsync.sendLocalChanges". So it looks like at least it is trying to update data back to Horde

**Comment by jobisoft** [comment] 2017-12-08 21:26
In general, yes. TbSync is not automatically sending your local changes *as you edit them*, but only if you hit the sync button in the TbSync account manager or set up auto sync (sync every x minutes). This is not ideal, but the current implementation. At some later point I will implement push services, but do not ask me when, I cannot tell.

Do you see your changes pushed to the horde server, if you hit the sync button?

**Comment by jobisoft** [comment] 2017-12-28 22:21
Can you retry with the latest beta [TbSync v0.6.8.3 (2017.12.28)](https://github.com/jobisoft/TbSync/releases/download/v0.6.8.2/TbSync-0.6.8.3-2017.12.28.xpi) ?

Can i have a debug log of when that error (status.js-error-in-calendarsync.sendLocalChanges) happens?

**Comment by xj25vm** [comment] 2018-01-24 21:01
Sorry for the delay. I've retried with 6.9.1 and I get the same error. Please see attached debug log.

[tbsync_debug.log](https://github.com/jobisoft/TbSync/files/1661649/tbsync_debug.log)

**Comment by jobisoft** [comment] 2018-01-24 21:41
Please try again with [beta7](https://github.com/jobisoft/TbSync/releases/download/v0.6.9.1/TbSync-0.6.9.2-beta7.xpi).

**Comment by xj25vm** [comment] 2018-01-24 21:54
With beta7, I get a different error. It counts down 30s on "Waiting for acknowledgement of local changes" and then "Communication timeout". Please note that this is a large calendar, with at least several thousand entries. However, all of them are already identical locally and at the far end. I only added one locally, and tried to sync it back into the backend. I am on a local lan, not through a slow vpn, in case it makes a difference. Please see attached log.

[tbsync_debug2.log](https://github.com/jobisoft/TbSync/files/1661827/tbsync_debug2.log)

**Comment by jobisoft** [comment] 2018-01-24 21:56
please inrease the timeout:

Go to thunderbird options -> Advanced -> Edit Config and search for tbsync. You will get en entry for

extensions.tbsync.eas.timeout

which defaults to 30000 (ms) which are 30s. Try to set it higher and see if it makes any difference.

**Comment by jobisoft** [comment] 2018-01-24 22:14
something is very odd, the log shows, that he wants to sync 100 and more old entries (from 2005) to the server. can you please start from scratch? disconnect the account and reconnect?

**Comment by xj25vm** [comment] 2018-01-25 05:14
Sorry - I just realised that my comment above was wrong. The local copy contains all the entries, going back to 2005 - which I've loaded from a text file export. The back-end is empty. Does that make more sense?

**Comment by jobisoft** [comment] 2018-01-25 08:38
I am just using the Lighning API, so I do not know how things work under the hood.

So you no longer have issues with beta7? I will later increase the default timeout from 30s to 90s.

Can we close this issue?

**Comment by xj25vm** [comment] 2018-01-25 09:16
Maybe I've spoken too soon. It is still in the process of syncing the 9000 calendar entries. Every few hundred entries, I get either "unknown network error" or "Sync failed. Server responds with status <Sync.Collections.Responses.Add[25].Status = 6>."

If I press "Syncronize this account" again, it continues to transfer another few hundred entries, before I see one of the two errors above again. Does it look like a different problem? Should I open a separate bug report?

**Comment by jobisoft** [comment] 2018-01-25 09:26
Keeping this issue is fine.

You have hit two bugs. 

1.) If TbSync prepared an element to be send to the server, he marks it as done right away and does not wait for ack from the server. So if the server fails to accept (like response.add.status=6), tbSync still thinks it has synced that item and will not send it again. This will be fixed in the next version. So if you clear your remote calender, start from scart (disconnect/connect) and re-import your data in TB and sync again, all those errors come back.

2. You are importing data and not using Thunderbird GUI itself to create the calendar items, that's why your data "looks" different from what I am used to and I may have to add more checks, if an element property is actually there. I need the last 100 lines a full debug log of such an error, most important the javascript error and the item data being send.

**Comment by xj25vm** [comment] 2018-01-25 10:00
Please find attached the log for "UNKNOWN_NETWORK_ERROR". I left only the last 1600 lines (it had 36000 lines)
[tbsync_debug3.log](https://github.com/jobisoft/TbSync/files/1663454/tbsync_debug3.log)

**Comment by jobisoft** [comment] 2018-01-25 10:06
There is not much I can do about that error, tbSync was not able to connect to your server (using standard Thunderbird API). 

I can only fix javascript errors.

Any chance you could send me your import file via email, so I can try to reproduce this here directly?I would need the entire file, because we do not know, which entry is the bad one...

**Comment by xj25vm** [comment] 2018-01-25 10:41
That's fine - I've sent you the calendar data as an email attachment. Many thanks for your help so far.

**Comment by jobisoft** [comment] 2018-01-25 13:38
This is taking very long... 

Is there a true need to sync 10 years old calendar data to the server? I am thinking about adding a default limit of 1 year, which can be changed in the settings. What do you think?

**Comment by xj25vm** [comment] 2018-01-25 13:49
I think many calendaring software have a similar default limit when syncing older calendar entries - so it would make sense to limit the import/sync to 1 year by default - as long as it can be changed in the settings. I guess it might be still worth persisting with testing this particular data set, to find out why the sync process breaks?

As a side note, I have tested a lot of calendar sharing solutions over the years - and all of them had the same two weaknesses - they couldn't cope with large data sets, and they couldn't cope if the data was slightly different from what they expected - be it a missing field, or the date format, or other things.

**Comment by jobisoft** [comment] 2018-01-25 13:58
Please check 16.4.2011, Alan Harris- iPad tuition

It has a reminder AFTER the event started. How did that happen? Intentionally?

**Comment by jobisoft** [comment] 2018-01-25 14:53
item.startDate is undefined 

Beautiful data set...

**Comment by jobisoft** [comment] 2018-01-25 15:54
Please start from scratch* and retry with [beta1](https://github.com/jobisoft/TbSync/releases/download/v0.7/TbSync-0.7.1-beta1.xpi)

* disconnect account, remove all calendar entries on the server, reconnect, re-import, sync

**Comment by xj25vm** [comment] 2018-01-25 16:02
> item.startDate is undefined

Could I have the date for that appointment, please? I can't really think of any reason why that should be the case.

> Please start from scratch* and retry with beta1

I will do and report back here

**Comment by jobisoft** [comment] 2018-01-25 16:06
I did not identify the item in question, I just fixed the error. With beta1 I was able to sync the entire dataset to a Kopano server. I could not test with Horde myself.

**Comment by xj25vm** [comment] 2018-01-26 11:04
Just an update - about 4000 records out of the 9000 have been synced, before starting to hit "UNKNOWN_NETWORK_ERROR" again. Restarting the sync manually seems to work. Is TBSync suppose to recover automatically after "UNKNOWN_NETWORK_ERROR" and continue?

**Comment by jobisoft** [comment] 2018-01-26 11:21
Not at the moment, the sync stops after an error. I plan to implement a resume-on-error later. For now, you could simply set autosync to 1, which will trigger a sync every minute (if not currently syncing).

**Comment by xj25vm** [comment] 2018-01-26 12:11
It has just stopped again with "UNKNOWN_NETWORK_ERROR". The autosync is set to 15 minutes - but it doesn't seem to resume the sync - although it seems to try - as it shows the error again. Strangely enough, manually clicking the sync button does restart the sync - for a while.

**Comment by jobisoft** [comment] 2018-01-26 12:15
I would like to handle the fail-to-resume in a different issue later. Currently it is important to know, if the sync fails due to javascript errors caused by corner cases - or if it runs through (with interruptions).

Please set the autosync to 1

**Comment by xj25vm** [comment] 2018-01-26 12:38
I have set autosync to 1, and that indeed resumes the sync. However, now I am stuck on the same set of 50, which keep on failing with "sync failed. Server responds with status <Sync.Collections.Collection.Responses.Add[34].Status = 6>". It is retrying the same set of 50, but the number after "Add[]", between square brackets, is always different. Does that mean it is NOT failing on the same record every time?

**Comment by xj25vm** [comment] 2018-01-26 12:54
> Please check 16.4.2011, Alan Harris- iPad tuition
>It has a reminder AFTER the event started. How did that happen? Intentionally?

Sorry, I didn't notice this earlier. The only reason I can think for this is that the appointment was moved after it was created backwards/earlier, and the reminder remained where it was. I can't think of any other reason.

**Comment by jobisoft** [comment] 2018-01-26 13:18
debug.log with those errors please (via email)

**Comment by jobisoft** [comment] 2018-01-26 13:21
and stop testing, I have worked on some issues and release a new beta shortly.

**Comment by jobisoft** [comment] 2018-01-26 14:03
Continue with [beta2](https://github.com/jobisoft/TbSync/releases/download/v0.7/TbSync-0.7.1-beta2.xpi).

beta2 marks items as "done" only after we received an ACK from the server. So if you run into n error and hit sync again, it will retry with the exact same items. So, in case of NETWORK-ERROR it will go on (because the error was not with the items), but with javascript errors he will get stuck and throw the same error over and over again.

This might sound bad first, but it is the correct way. We need to fix javascript errors and we do not want to silently drop items. Furthermore, if you restart TB (and thus delete the debug log), you can reproduce the error just by hitting sync. 

Can you verify this behaviour? If so, always restart Thunderbird after an error and reproduce the error via sync, to minimize the debug.log.

**Comment by xj25vm** [comment] 2018-01-26 15:22
OK - by the time I got to it, there were only 220 items left which have since synchronised. Do you want me to delete the calendar, re-import and re-start the sync with Beta 2?

**Comment by jobisoft** [comment] 2018-01-26 15:30
sync the last 220, maybe the error pops up again.

If no more error pop up, a restart from scratch is the only option to get to the bottom of this bug..

**Comment by jobisoft** [comment] 2018-01-26 15:31
oh, it is fully synced now already? Yeah, than please start from scratch.

**Comment by jobisoft** [comment] 2018-01-30 11:30
Do you have any more errors syncing your imported data? Otherwise I would like to close this issue. The beta2 is no longer avail, use the latest official release of [0.7.3](https://github.com/jobisoft/TbSync/releases/download/v0.7.3/TbSync-0.7.3.xpi)

**Comment by xj25vm** [comment] 2018-01-30 14:19
Sorry - I didn't get a chance to re-run the sync yet. Could you keep this issue open a bit longer please - I hope to get to it in the next few days.

**Comment by jobisoft** [comment] 2018-01-30 14:22
Sure.

**Comment by jobisoft** [comment] 2018-01-30 21:23
Important: For your test please set the following advanced options:

extensions.tbsync.eas.synclimit = 0
extensions.tbsync.eas.maxitems = 1

How these options are set is described in the [wiki](https://github.com/jobisoft/TbSync/wiki/Advanced-configurations). After you have set these values, restart Thunderbird before starting your test.

**Comment by xj25vm** [comment] 2018-01-31 10:05
The value options for extensions.tbsync.eas.synclimit seems a little counter-intuitive. Wouldn't it have been possible to just have the number of days - with a maximum of 180, and 0 for 'all' - maybe?

**Comment by jobisoft** [comment] 2018-01-31 10:27
These are advanced options which are explained in the wiki. They translate directly to EAS options and I do not want to add an extra "transformation" layer there. Also "6 month" cannot be converted to a fixed number of days.

**Comment by xj25vm** [comment] 2018-01-31 11:48
OK - thank you for the explanation. Will there likely be an option in the UI to change these settings, at some point in time in the future?

The latest sync is still in progress - I will post here when it is done, or if I encounter errors.

**Comment by jobisoft** [comment] 2018-01-31 11:55
I do not think I will add those options to the GUI, usually the default values for these are good. Furthermore the concept behind TbSync is "simple and works", without much need for the user to setup anything. Currently there are a few settings for contacts which will eventually go away as well (not my code).

If the defaults to not fit your needs, you can change them with just a few clicks. Adding those options to some "advanced config" tab in TbSync is a lot of work, which I do not want to spend.

**Comment by xj25vm** [comment] 2018-01-31 12:03
And I've hit the first error of the sync - after about 2000 items. Please see attached log - it might contain several retries on the same item, I think.
[tbsync_debug_2018-01-31a.log](https://github.com/jobisoft/TbSync/files/1681594/tbsync_debug_2018-01-31a.log)

**Comment by jobisoft** [comment] 2018-01-31 12:07
The test worked perfecty, there is exactly on item (which failed), which I can now analyse. What kind of server are you sending this to? Office 365? Horde? Kopano?

**Comment by xj25vm** [comment] 2018-01-31 12:23
It's a Horde 5.2.10 back-end. There are another 7000 items to sync, though.

**Comment by jobisoft** [comment] 2018-01-31 12:27
You should not be able to sync anymore items, because TbSync is stuck on the one you send me, right? I will send you a new version of TbSync, after I fixed the bug. Then you can continue until you encounter the next bug (or until the sync runs fine the end).

I am currently fixing another buf, so it might take a while.

**Comment by xj25vm** [comment] 2018-01-31 12:30
Correct - the sync it stuck on that item. No hurry with regards to the fix - thank you for your help so far.

**Comment by jobisoft** [comment] 2018-01-31 13:45
Any chance you could lockup the log files of your horde server, if there is any indication of what is causing the error? I am sending against an horde as well (need to lookup what version) and I can send the event without error. I compared the WBXML, they are identical (besides synckey and collection id of course).

**Comment by jobisoft** [comment] 2018-02-02 08:42
Other approach: Can you mail me your ics file, which you are trying to import? Maybe with that file I will be able to reproduce the error.

**Comment by xj25vm** [comment] 2018-02-02 09:00
It's exactly the same file I sent you before - I used the same one so that you can do tests on it if necessary.

**Comment by jobisoft** [comment] 2018-02-02 10:18
Furthermore: If my assumption is correct, you should be able to see the failing item in your online calendar in your horde webinterface.

```
<StartTime xmlns='Calendar'>20090702T100000Z</StartTime>
<EndTime xmlns='Calendar'>20090702T163000Z</EndTime>
<Subject xmlns='Calendar'>Sinclairs - electric drill for brackets, tidy up it stuff in Gordon's room, signature for all, finish old computer, enable case fans on new computers, Pauline's bookmarks from old computer, extra RAM on Aaron's, connect printer to server, Spark on Pauline's, Barbara's old calendar items, new network point for Toni's, office compatibility pack on all</Subject>
```

If that event is there, it is a clear indication for my "error-on-resending-item-as-new" assumption.

**Comment by xj25vm** [comment] 2018-02-02 10:52
> If my assumption is correct, you should be able to see the failing item in your online calendar in your horde webinterface.

I'm afraid it isn't there. The last item in the Horde back-end is the one just before it - at 20090702T1000 (local time).

> This error can be caused by timeouts (missing responses) or some other network error (do you recall having a network error before this error poped up?).

I don't recall a network error, but considering this laptop is on wifi while syncing, it is perfectly possible for the wifi to have caused a brief drop - wifi networks do that all the time.

I think it is important to find a robust solution to this problem. For example, this particular laptop I am using (and testing TBSync on) travels every day between different networks, most of the time is on wifi, a lot of time talks to the Horde server via vpn (OpenVPN), and it is regularly put to sleep/stand-by and woken up again. I'm not sure adding the same item again to the back-end would be the best option - in practice this could end up adding a lot of duplicates to the back-end.

> Do you see any errors in your logs pointing in that direction? Something with bad ClientId (that is the correct fieldname used by EAS)?

In my Horde back-end, I have the following error repeated again and again:

`2018-02-02T10:47:29+00:00 ERR: HORDE [kronolith] SQL QUERY FAILED: SQLSTATE[22001]: String data, right truncated: 7 ERROR:  value too long for type character varying(255)  
	INSERT INTO kronolith_events (event_id, event_uid, event_creator_id,
	  event_title, event_description, event_location, event_timezone,
	  event_url, event_private, event_status, event_attendees,
	  event_resources, event_modified, event_start, event_end, event_allday,
	  event_alarm, event_alarm_methods, event_recurtype, calendar_id) VALUES
	  ('VfGTqdeOokNpLzX5o6rWOu1',
	  '20180202104729.V1asWRZGT-r8R9K0s0skRiq@192.168.16.1',
	  's.arcus@open-t.co.uk', 'Sinclairs - electric drill for brackets, tidy
	  up it stuff in Gordon''s room, signature for all, finish old computer,
	  enable case fans on new computers, Pauline''s bookmarks from old
	  computer, extra RAM on Aaron''s, connect printer to server, Spark on
	  Pauline''s, Barbara''s old calendar items, new network point for
	  Toni''s, office compatibility pack on all', '', '', 'Europe/Berlin',
	  '', 0, 1, 'a:0:{}', 'a:0:{}', 1517568447, '2009-07-02 10:00:00',
	  '2009-07-02 16:30:00', 0, 60, 'N;', 0, 'Il8z3_caK3f4F3DUKBDHf3X') [pid 25585 on line 234 of "/usr/lib64/php/Horde/Db/Adapter/Pdo/Base.php"]`

**Comment by xj25vm** [comment] 2018-02-02 12:16
Yes - the sync has resumed now. I wonder what would be the best way to deal with this case? TBSync to silently truncate the Subject field to 255 characters during sync? Submit it as a bug to the Horde team - so that Horde truncates silently the Subject to 255 characters, instead of aborting with an error? Maybe a third option - like TBSync complaining out loud, with a full error message, including the item which can't be synced - but continuing to sync the other itmes?

**Comment by jobisoft** [comment] 2018-02-02 12:33
I think 256 chars max on the subject is not such a bad assumption. You clearly have a corner case here. I am still trying to find out, what the actual EAS specification says about that. I think I will limit the subject and add a note to the subject in the event (too long or something like that).

I will get in touch with the horde team...

**Comment by jobisoft** [comment] 2018-02-02 12:34
If you get any other errors on your import, tell me :-)

**Comment by xj25vm** [comment] 2018-02-02 14:01
Sure. After another 1200 items (I think), another similar error, on 2009-10-05. I truncated the Subject field again, and resumed the sync.

And then another one on 2009-10-09 - and probably there will be more :-)

**Comment by jobisoft** [comment] 2018-02-02 14:40
How about that: I truncate the Subject (indicated by ... at the end) and add the full subject to the body, as

Too long Subject: <subject>

This would get it out of my feet without loosing data

**Comment by xj25vm** [comment] 2018-02-02 14:57
That would be an option. I think something more rigorous would be to continue with the sync, and at the end to present a list of all the items which could not be synced because of incompatibility between the Thunderbird and the back-end. This way the user can choose what to do with them. I think usually a sync software silently making changes on the data would be considered not really acceptable.

**Comment by jobisoft** [comment] 2018-02-02 15:13
I really do not want to spend dev time on corner cases. Your suggestion req. a lot of changes to the sync process. 

I am down to two options:
- hard fail like now, but with a specific error (event xy has a to long subject)
- silent truncation with backup in body

Since I agree with your statement about data integrity, I would go for option 1. Ok?

**Comment by xj25vm** [comment] 2018-02-02 15:17
Would it be possible to hard-fail like now, but skip the affected items and continue with the others - or would that require a lot of changes to the code?

**Comment by jobisoft** [comment] 2018-02-02 15:23
That is the exactly what would need refactoring :-) I will think about this ...

**Comment by xj25vm** [comment] 2018-02-02 16:12
Hmm - yes, that is a tricky one. As things are now, it is quite a problem. It is perfectly possible for users to put in lots of text in the Subject field - as Thunderbird allows it. And then the sync stops completely - and without the additional debug output, it doesn't even tell users why or where the problem is.

**Comment by jobisoft** [comment] 2018-02-02 16:55
Do not manually truncate your subjects, so that we still have something to test against. I will provide a solution over the weekend.

**Comment by xj25vm** [comment] 2018-02-02 18:15
I have truncated about 3 of them - but I still have the original .ics file - so I could restart the import and sync from scratch if necessary.

**Comment by jobisoft** [comment] 2018-02-03 12:39
Please try [this](https://github.com/jobisoft/TbSync/releases/download/v0.7.3/TbSync-softfailtest.xpi) version.

It should skipp bad items and throw a final message at the end. Next time you sync, it should retry those failed items and throw the same message again.

**Comment by jobisoft** [comment] 2018-02-03 12:41
If you get another error (network or something else that throws hard) before coming to the end, the information of the skipped items is lost, but they are still in the changelog (thus retried on next sync), so eventually you should see the list of failed items.

**Comment by xj25vm** [comment] 2018-02-03 13:12
The first problem is that it doesn't seem to recognise the sync state left by the previous version of TBSync. After installing the version you suggested above, it attempts a sync, and then it shows "OK: Calendar" - although there should be another 6000 items to sync (I checked the count in the back-end). Do you want me to remove the local and remote calendars, re-import the .ics file and re-start from scratch - or try something else?

**Comment by jobisoft** [comment] 2018-02-03 13:30
Yeah, there was a change to the changelog data format. Restart from scratch.

**Comment by jobisoft** [comment] 2018-02-03 22:25
Did you restart the test yet?

I continued to work on the soft fail concept and I would consider it "done" now, but since I had to change a lot, I would like to ask you to test [softfailtest2](https://github.com/jobisoft/TbSync/releases/download/v0.7.3/TbSync-softfailtest2.xpi).

You will see, that your data set contains another "error": There are 234 tasks in your import data, which cannot by synced to a calendar folder. You will get the message at the very end. :-)

**Comment by jobisoft** [comment] 2018-02-04 08:43
For the test with softfail2 you can set

extensions.tbsync.eas.maxitems = 50

again.

**Comment by xj25vm** [comment] 2018-02-05 06:15
Thank you. I will re-run the sync over the next few days and report back

**Comment by xj25vm** [comment] 2018-02-06 17:23
It has synced everything, except for 260 items. Any ideas what "wrong folder type" means?

By the way - I really like the verbose error message, full of useful details :-)

**Comment by jobisoft** [comment] 2018-02-06 17:38
Wrong folder type means, you have tasks in a Calendar folder. For thunderbird, this is no problem, but I cannot sync mixed types to EAS (EAS has distinct calendar and tasks folders).

What would be a better but still short error type/message?

**Comment by xj25vm** [comment] 2018-02-06 18:12
Maybe "task item in calendar folder" and "calendar item in task folder" (if it happens the other way around)? I suppose the correct error message would be "wrong item type" - but I think this would be too vague - nobody would know what it really means.

It seems that this data set has been more challenging than I realised. I guess it helped to fix plenty of future bugs, though :-)

**Comment by jobisoft** [comment] 2018-02-06 18:27
Yep, I will change those error messages.

I will close this issue soon, it was indeed a beautiful dataset and i want to thank you very much for your testing.

All changes have been migrated to beta4.

May I put you on the beta testing list? The release of the v0.7 branch was a mess and I had to release lots of quick fixes. For the future, before releasing a new version to Mozilla, I would like to have some user feedback.

If you are interested, just drop me an email: john.bieling@gmx.de

**Comment by xj25vm** [comment] 2018-02-07 21:45
Thank you for taking the time to build fixes and release them.

Do add me to the beta testing list. I might not find the time every time to test TBSync releases - but I will try.

**Comment by xj25vm** [comment] 2018-02-07 21:51
Just a quick suggestion before I forget - I wonder if it would be better to have a lower number for extensions.tbsync.eas.maxitems by default - maybe 10? It seems that on slower computers with larger calendars, the "waiting for acknowledgement of local changes" step takes quite a long time when it is set to 50 - and the Thunderbird interface is very sluggish (I wonder if that is because TB is still single threaded?)

**Comment by jobisoft** [comment] 2018-02-08 16:49
Many server do not like such low maxitems, because the load is much higher, so I will not change the default, but you may of course set it as you like. I hope in the future, there will be better background thread support in Thunderbird.

**Closed by jobisoft** 2018-02-08 16:49 UTC

**Comment by jobisoft** [comment] 2018-04-03 15:15
Please update your beta version of TbSync to [0.7.6.8](https://github.com/jobisoft/TbSync/releases/download/v0.7.6/TbSync-0.7.6.8.xpi) or any later version available at the [release page](https://github.com/jobisoft/TbSync/releases).

This version now includes an update notification, so I no longer have to contact all beta users, to update their TbSync versions:

https://raw.githubusercontent.com/jobisoft/TbSync/master/screenshots/update_notification.png

While on the beta release channel, I strongly suggest to update, if a newer version is available. Once a new stable version gets released, you automatically switch back to the stable release channel (you no longer receive update notifications for beta versions).
