### ISSUE TITLE
accounts gone

### ISSUE THREAD

**Issue by dio99** [jobisoft/TbSync#238] opened 2019-02-18 08:12 UTC
tbsync 1.5
i updated pwd on my exchange and now when i try to open tbsync my account is gone but the calendar is still there and sync ?? 

## Your environment

TbSync version:
Thunderbird version:

[ ] Yes, I have installed the latest available (beta) version from 
https://github.com/jobisoft/TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
...

## Actual behavior
...

## Steps to reproduce
...

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by dio99** [comment] 2019-02-18 08:30
damn i saw now that thunderbird version 60.4.0 is not supported :( my thunderbird got updated

**Comment by jobisoft** [comment] 2019-02-18 11:14
That is not true! TbSync runs on Thunderbird 60.5 as well! Where does it say it is not compatible?

**Comment by jobisoft** [comment] 2019-02-18 11:17
The official page also says compatible up to 61.*
https://addons.thunderbird.net/addon/tbsync

**Comment by dio99** [comment] 2019-02-18 11:17
sorry my misstake i read on the wrong plugin.. was to fast to write to add that..
but still its very strange since i dont see my account but still its active.. 
i updated to beta 1.5.5 plugins still same issue

**Comment by jobisoft** [comment] 2019-02-18 11:20
Can you Restart TB and check if that helps? 
Can I have a screenshoot of the Manager? 
Can you search your Thunderbird profile Folder and lok for a Folder TbSync and send me the accounts.json file? Via Email?

**Comment by dio99** [comment] 2019-02-18 11:23
tested restart still same 
hmm strange that json is empty as the manger..

**Comment by jobisoft** [comment] 2019-02-18 11:27
Totally empty or does it inlcude something like [] or {}?

All other files (Folders and changelog) empty as well? Do you have any special storage?

**Comment by dio99** [comment] 2019-02-18 11:29
TbSync $ more accounts.json 
{"sequence":0,"data":{}}
changelog is some info in
in Photos dir i got 2 folders
nope local disk

**Comment by jobisoft** [comment] 2019-02-18 11:31
It looks like TbSync has overwriten ist config with an empty template. Not good. I will look into that.

What about folders.json?

**Comment by dio99** [comment] 2019-02-18 11:33
ail folders.json 
{}larssand@ul001714 ~/.thunderbird/tieto.default/TbSync $ more folders.json 
{}

**Comment by jobisoft** [comment] 2019-02-18 11:36
yes, empty dataset. You have to remove/rename your local stale sync Targets (addressbooks and calendars) and set it up again.

Please observe, if TB crashes or something else happens, that could cause this. Is that a laptop which sometimes runs out of battery?

**Comment by dio99** [comment] 2019-02-18 11:38
yes it is.. 
okie but that will reqiure me to add the ID fo be allowed since the uniq id will be new right ?

**Comment by jobisoft** [comment] 2019-02-18 11:44
You mean the Client-ID? If you still now the "old" ID, you can replace the new generated one in accounts.json after you created the account and before you enable it.

You must close Thunderbird completely before changing the accounts.json and wait at least 6 seconds before editing accounts.json.

**Comment by dio99** [comment] 2019-02-18 11:46
aha okie so i can modify the ID and it will work.. great..

**Comment by jobisoft** [comment] 2019-02-18 12:13
ahm, do not do that! 

The Client-ID is only used for the syncstate, not for access auth. The Server ID I send is used for Auth, and I did not Change that.

**Comment by jobisoft** [comment] 2019-02-19 08:17
This is a duplicate of 
https://github.com/jobisoft/TbSync/issues/234

I close this, please subscribe to the other issue.
Thanks.

**Closed by jobisoft** 2019-02-19 08:17 UTC
