### ISSUE TITLE
Supports TB 115

### ISSUE THREAD

**Issue by panther7** [jobisoft/TbSync#669] opened 2023-05-16 16:10 UTC
Prepare for compatibility with future Thunderbird 115.   
Actually 114 is not supported.

Beta release date: 8 June 2023
Release date: 11 July 2023

**Comment by jim-davenport** [comment] 2023-07-10 19:18
Where are we at on this? I believe that 115 is to be released tomorrow.

**Comment by entepe85** [comment] 2023-07-11 08:19
FWIW: The current main branch of this repo is compatible w/ TB 115 "Supernova". I've verified this by downloading the branch as a ZIP, unpacking it and loading it into TB through "Debug addons".

**Comment by Ule15** [comment] 2023-07-11 14:44
Hi I'm a total rookie, meaning I have idea about programming.
I just changed the "max Version" in the manifest.json to 116 and made a new XPI. Then I loaded the extension successfully in TB. Greetings Uli

**Comment by jobisoft** [comment] 2023-07-11 15:44
The current branch is almost ready, but has a few buttons missing. Will work on it on Friday.

**Comment by McBaumwolle** [comment] 2023-07-11 15:46
Thanks omg!

**Comment by jim-davenport** [comment] 2023-07-11 21:02
> Hi I'm a total rookie, meaning I have idea about programming. I just changed the "max Version" in the manifest.json to 116 and made a new XPI. Then I loaded the extension successfully in TB. Greetings Uli

Can you send me the XPI? I would like to try it, but have no idea how do what  you did.

**Comment by Ule15** [comment] 2023-07-12 05:56
> Can you send me the XPI? I would like to try it, but have no idea how do what you did.

Extract the zip file, edit the manifest.json. The XPI is created by the batch file which is included in the zip. Or wait until friday

Greetings Uli

**Comment by jobisoft** [comment] 2023-07-12 08:55
> Also I'm not sure if you are aware, but on your sponsorship page on github, minimum monthly sponsorship is $100, I'd be happy to contribute a little to your work on a monthly basis but I can't contribute that much!

Oh wow, I was unaware that the tier value was not changeable by the donor, lowered it to $10. Thanks for the hint!

**Comment by nicolaheile** [comment] 2023-07-13 08:07
Is there any way to geht the Addon XPI? Or a manual how to build it?
Can you create a release?

**Comment by bjo81** [comment] 2023-07-13 08:14
Click on "Code" -> "Download ZIP" -> Unzip the ZIP and then rezip the contents without subfolder. Then you can use the zip like a xpi.

**Comment by jim-davenport** [comment] 2023-07-13 13:21
Just reporting a possible problem in advance. I loaded the extensions based on the above posts. All calendars and contacts are syncing with the exception of my main calendar from my outlook.com account. When that attempts to sync, it locks up Thunderbird as not responding. I have to end the task and make sure that calendar is not selected.

**Comment by smmehta1822** [comment] 2023-07-14 16:53
I download the xpis for TBSync and Provider for Exchange and re-created zip and worked with TB 115.

**Comment by McBaumwolle** [comment] 2023-07-14 17:49
Maybe this is helpful, but when I try to do this (change the version req) the screen with the calendars/tasks has no scroll bar and the button to sync is at the bottom aka not visible.

**Comment by smmehta1822** [comment] 2023-07-14 19:19
I do not use tasks. Just use the Calendar (Exchange) and seems have worked. I still need to test more. Max versions for these 2 add-ons are 115 already so I did not make any changes.

**Comment by jim-davenport** [comment] 2023-07-14 19:51
> Just reporting a possible problem in advance. I loaded the extensions based on the above posts. All calendars and contacts are syncing with the exception of my main calendar from my outlook.com account. When that attempts to sync, it locks up Thunderbird as not responding. I have to end the task and make sure that calendar is not selected.

I wanted to add one thing... That calendar that is locking up 115 syncs fine on 102 - both Windows.

**Comment by jobisoft** [comment] 2023-07-14 20:41
1. No one should manually edit the manifest file of an older version and change the max version from 102 to 115. 
2. The development version is not published (yet), because it is not fully done, but you could build it by yourself from the source provided in this repo
3. I see the demand and packed it up for download here (rename zip to xpi)

[TbSync-beta.zip](https://github.com/jobisoft/TbSync/files/12053777/TbSync-beta.zip)

**Comment by jim-davenport** [comment] 2023-07-14 21:07
Thank you for posting that. It still locks up on my main calendar though. 
<img width="563" alt="Screenshot 2023-07-14 170610" src="https://github.com/jobisoft/TbSync/assets/25080903/d3832b7b-7ead-41fc-877e-318ac4c09510">

**Comment by McBaumwolle** [comment] 2023-07-14 21:25
Thank you so much @jobisoft and take all the time you need of course!

**Comment by jretxaniz** [comment] 2023-07-15 20:01
Hello and thanks. We will need too a new version of Provider for Exchange ActiveSync. Where could we get it?

**Comment by entepe85** [comment] 2023-07-16 07:00
> Hello and thanks. We will need too a new version of Provider for Exchange ActiveSync. Where could we get it?

You can download the source code for that extension as a ZIP, unpack it and then ZIP the content of the unpacked folder an rename it to .xpi for the time being. 

The approach is also explained in the comments to this issue.

**Comment by jretxaniz** [comment] 2023-07-17 05:33
> > Hello and thanks. We will need too a new version of Provider for Exchange ActiveSync. Where could we get it?
> 
> You can download the source code for that extension as a ZIP, unpack it and then ZIP the content of the unpacked folder an rename it to .xpi for the time being.
> 
> The approach is also explained in the comments to this issue.

Done and working. Thanks a lot

**Comment by panther7** [comment] 2023-07-17 07:08
> <img alt="Screenshot 2023-07-14 170610" width="563" src="https://user-images.githubusercontent.com/25080903/253682740-d3832b7b-7ead-41fc-877e-318ac4c09510.png">

OT: Maybe is time, fix dark theme, finaly 😇

**Comment by brianhanifin** [comment] 2023-07-18 04:47
> [TbSync-beta.zip](https://github.com/jobisoft/TbSync/files/12053777/TbSync-beta.zip)

Wow! It works well. I have never had my iCloud contacts synced before. Donation incoming. :)

Thank you!

**Comment by warp123** [comment] 2023-07-18 16:47
> > Hello and thanks. We will need too a new version of Provider for Exchange ActiveSync. Where could we get it?
> 
> You can download the source code for that extension as a ZIP, unpack it and then ZIP the content of the unpacked folder an rename it to .xpi for the time being.
> 
> The approach is also explained in the comments to this issue.

Is it possible to explain how to install the  Exchange ActiveSync addon for fb115? I didn't get the procedure you described.

**Comment by McBaumwolle** [comment] 2023-07-19 08:28
@warp123 you can just go to the repository on [GitHub](https://github.com/jobisoft/EAS-4-TbSync) and click "download Zip" in the green `<> Code` menu. 

<details><summary>GitHub</summary>

![image](https://github.com/jobisoft/TbSync/assets/67203883/03ba1c68-4c23-4055-9bfa-4ec352597ce8)


</details>

Then unpack the `.zip` folder and go to the main folder that has the same structure as the repository (where the `readme.md` is located) and select all files and compress as a `.zip`. 


Now head over to Thunderbird and go to extensions, over the settings-icon you can import an add-on from files. 

<details><summary>Thunderbird</summary>

![image](https://github.com/jobisoft/TbSync/assets/67203883/0ed27710-28d7-47ca-89ce-24e9c40e7aa9)

</details>

This should do it, at least for me it worked.

**Comment by warp123** [comment] 2023-07-19 08:36
> @warp123 you can just go to the repository on [GitHub](https://github.com/jobisoft/EAS-4-TbSync) and click "download Zip" in the green `<> Code` menu.
> 
> GitHub
> Then unpack the `.zip` folder and go to the main folder that has the same structure as the repository (where the `readme.md` is located) and select all files and compress as a `.zip`.
> 
> Now head over to Thunderbird and go to extensions, over the settings-icon you can import an add-on from files.
> 
> Thunderbird
> This should do it, at least for me it worked.

Thanks a lot. It worked. Just needed to rename zip file to xci. The zip extension was giving error.

**Comment by je-vv** [comment] 2023-07-23 03:10
When doing the final release to [thunderbird add-ons](https://addons.thunderbird.net), which versions to expect for both TbSync and EAS-4-TbSync?  Are both goind to be released at the same time on add-ons?

**Comment by BillH99999** [comment] 2023-07-23 03:11
I have the same question about Google-4-TbSync.

**Comment by andreasbrett** [comment] 2023-07-24 10:35
I have the same question for DAV-4-TbSync

**Comment by bananabob** [comment] 2023-07-30 05:51
Interested when this will be released

**Comment by mysterymeth** [comment] 2023-08-09 14:02
for the provider, repository on https://github.com/jobisoft/EAS-4-TbSync and click "download Zip" in the green <> Code menu

Then unzip it, and run `make` this will create an xpi file, which you can add to thunderbird 115 and it works

**Comment by otristrichter** [comment] 2023-08-10 14:09
Unfortunately, something is still not working properly with the EAS-4-TbSync plugin under TB 115. I have two calendars in the Exchange and during the initial sync the appointments of one calendar are imported correctly but with the second calendar the sync gets stuck at 0/xx and imports nothing.
With TB 102 it works with both calendars without errors.

**Comment by jim-davenport** [comment] 2023-08-10 14:31
I have the same problem. It is locks up Thunderbird solid when syncing my main calendar. All is good on 102

**Comment by Mechtilde** [comment] 2023-08-11 08:57
@jobisoft when do you plan to release the final version for thunderbirs 115.
I want to package it for Debian

**Comment by bananabob** [comment] 2023-08-12 07:55
Tried the .xpi for the beta and it won't let me add caldav accounts as 
Provider for CalDAV & CardDAV extension is required but it is not yet available for 115.

**Comment by pcause** [comment] 2023-08-14 15:05
I installed the 115.1 flatpak.  Using the zip I install tbsync.  EAS-4-Tbsync wouldn't install.    I tried downloading the zip from the repository and renaming and got that it was corrupted.  Downloaded the released version, unpacked, edited the manifest and rezipped and it installed.  However couldn't add a o365 account.  Tried Oauth and it failed with message about local.

**Comment by jmaris** [comment] 2023-08-18 09:52
Any updates on this ?

**Comment by pcause** [comment] 2023-08-20 13:45
Just saw that the EAS-4=Tbsync was added to the addins on the thunderbird site

**Comment by BillH99999** [comment] 2023-08-22 03:59
Unfortunately, I can no longer wait for Google-4-Tbsynd to be updated for 115.  I've been using Tbsync for years now and Google-4-Tbsync since Tbsync no longer natively supported Google.  There has been no word from the Google-4-Tbsync author for months and they aren't replying to reviews on the plugin site or to issues on Gitub, so maybe it is dead.  I guess I'll switch to Cardbook.  I will miss Tbsync.

**Comment by panther7** [comment] 2023-08-22 04:48
This is typical for this project, TB 102 was released 29 June 2022, Tbsync was release for 102 in 21 Sep 2022.
I don't understand, why Tbsync is not prepared for TB in beta stage. 🤷‍♂️

But, I hope, than will be release soon. 🤞

**Comment by r3dpan** [comment] 2023-08-22 06:31
> Unfortunately, I can no longer wait for Google-4-Tbsync to be updated for 115. I've been using Tbsync for years now and Google-4-Tbsync since Tbsync no longer natively supported Google. There has been no word from the Google-4-Tbsync author for months and they aren't replying to reviews on the plugin site or to issues on Gitub, so maybe it is dead. I guess I'll switch to Cardbook. I will miss Tbsync.


> This is typical for this project, TB 102 was released [29 June 2022](https://www.thunderbird.net/en-US/thunderbird/102.0/releasenotes/), Tbsync was release for 102 in [21 Sep 2022](https://github.com/jobisoft/TbSync/issues/591#issuecomment-1253635484). I don't understand, why Tbsync is not prepared for TB in beta stage. 🤷‍♂️
> 
> But, I hope, than will be release soon. 🤞

You do realize that this is a completly free and open source plugin which the devs probably work on during their free time (additionally to their jobs)? It always bothers me when people start expecting business grade support from people they don't even pay for their work. You are however free to donate to support this project.
Besides @jobisoft already mentioned on the main post on the tbsync github page (and it was already mentioned here too) that you are free to download the current version from github, rename the file and manually import it in thunderbird. Already did this two weeks, after TB 116 got released and so far this works fine for me.

**Comment by jobisoft** [comment] 2023-08-22 06:59
TbSync has been officially released for 115 a few days ago. I usually try to finish the update bevor Thunderbird itself enables auto update to the new ESR, which I think will happen in 1 or 2 weeks.

I wrote it elsewhere already: This cycle I concentrated on my other add-on Quicktext and have finished the conversion to a pure WebExtension to roughly 70%. Once completed, it will require a lot less update work and will be compatible with beta and daily. After that work has been completed, I will convert TbSync. I hope that will happen till ESR release next year.

**Comment by pcause** [comment] 2023-08-22 11:44
> TbSync has been officially released for 115 a few days ago. I usually try to finish the update bevor Thunderbird itself enables auto update to the new ESR, which I think will happen in 1 or 2 weeks.
> 
> I wrote it elsewhere already: This cycle I concentrated on my other add-on Quicktext and have finished the conversion to a pure WebExtension to roughly 70%. Once completed, it will require a lot less update work and will be compatible with beta and daily. After that work has been completed, I will convert TbSync. I hope that will happen till ESR release next year.

Your efforts are GREATLY appreciated.  Without your efforts I, and I assume many others, couldn't use Thunderbird.  Thanks.

**Comment by BillH99999** [comment] 2023-08-22 15:01
> > Unfortunately, I can no longer wait for Google-4-Tbsync to be updated for 115. I've been using Tbsync for years now and Google-4-Tbsync since Tbsync no longer natively supported Google. There has been no word from the Google-4-Tbsync author for months and they aren't replying to reviews on the plugin site or to issues on Gitub, so maybe it is dead. I guess I'll switch to Cardbook. I will miss Tbsync.
> 
> > This is typical for this project, TB 102 was released [29 June 2022](https://www.thunderbird.net/en-US/thunderbird/102.0/releasenotes/), Tbsync was release for 102 in [21 Sep 2022](https://github.com/jobisoft/TbSync/issues/591#issuecomment-1253635484). I don't understand, why Tbsync is not prepared for TB in beta stage. 🤷‍♂️
> > But, I hope, than will be release soon. 🤞
> 
> You do realize that this is a completly free and open source plugin which the devs probably work on during their free time (additionally to their jobs)? It always bothers me when people start expecting business grade support from people they don't even pay for their work. You are however free to donate to support this project. Besides @jobisoft already mentioned on the main post on the tbsync github page (and it was already mentioned here too) that you are free to download the current version from github, rename the file and manually import it in thunderbird. Already did this two weeks, after TB 116 got released and so far this works fine for me.

r2dpan,

Maybe you misread my post.  I said I can no longer wait for Google-4-TbSync to be updated.  I already know that TbSync has been released for 115 and I downloaded and installed it.  Unfortunately TbSync requires Google-4-TbSync in order to use it with Google.  I was only commenting that the author of Google-4-TbSync (not John) is not replying to any issues on Github and hasn't for months.  Maybe that plugin it dead.  I've always been very pleased with TbSync and the work that John does.  I was sad when he dropped support for Google.  I had hoped Google-4-TbSync would be the answer.  Cardbook is already updated for 115, I installed it, and it works great.

**Comment by Nils-TUD** [comment] 2023-08-22 15:43
> There is a problem with Thunderbird completely locking up while syncing one or more calendars with the latest version on 115. These calendars sync fine on 102. Where are we with that? Do you need more information? Thanks!

As far as I can see, this is not caused by TbSync as it also happens for me when I disable all extensions (with 115, it's fine with 102). I've filed a bug report [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1849540).

**Comment by TBrianB** [comment] 2023-08-25 22:56
> As far as I can see, this is not caused by TbSync as it also happens for me when I disable all extensions (with 115, it's fine with 102). I've filed a bug report [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1849540).

That doesn't seem to make any sense. If TB locks up when syncing **it's using TBSync** - which is an exension. So unless the previous poster is getting lock-ups when not trying to sync (and they specifically refer to lock ups when syncing) it's using TBSync when it locks up.

**Comment by Nils-TUD** [comment] 2023-08-26 05:28
Yes, I'm also not sure what's happening there. I was first experiencing the problem when using TBSync after updating to TB 115. As soon as it tried to sync the calendar, TB locked up. Then I removed the calendar, disabled all extensions and tried to add it again. And then TB also locked up. See also the bug report: someone else investigated that further and said that this has something to do with the existence of the `VTIMEZONE` object (i.e., not all CalDAV calendars are affected). So, this indeed happens without TBSync being used.

Maybe TB is involved during the sync via TBSync as well, so that the same problem occurs for syncs as well? Or these are two different bugs?

**Comment by TBrianB** [comment] 2023-08-26 14:58
d that this has something to do with the existence of the `VTIMEZONE` object (i.e., not all CalDAV calendars are affected). So, this indeed happens without TBSync being used.
> 
> Maybe TB is involved during the sync via TBSync as well, so that the same problem occurs for syncs? Or these are two different bugs?
I am puzzled. how can you do the sync without using TBSync ?
Also is it the TBSync or the Providor for Exchange Active Sync that's the issue? I'm not sure wqhere th functionality of one ends and the other begins.
On my machine it locks up at 100/113 calendar entries. But it also creates extrra calendar copies and produces duplicate entries in teh calendar side bar at the same time (not showing/hidden in the main calendar
![Screenshot_3](https://github.com/jobisoft/TbSync/assets/143229939/68dffb92-5c14-48c5-8ad2-fb9fe09253f4)
![Screenshot_1](https://github.com/jobisoft/TbSync/assets/143229939/a5f2d522-0b1a-42d2-a2b8-cea079de590e)
) see screenshot

**Comment by Nils-TUD** [comment] 2023-08-26 15:25
> I am puzzled. how can you do the sync without using TBSync ?

I wasn't syncing without TBSync. As I said, it apparently happens when adding a calendar to TB (without TBSync) *and* when syncing a calendar (with TBsync).

> Also is it the TBSync or the Providor for Exchange Active Sync that's the issue? I'm not sure wqhere th functionality of one ends and the other begins.

In my case it was a CalDAV calendar, not an Exchange calendar.

**Comment by jim-davenport** [comment] 2023-08-26 15:33
In my case, it is a calendar from my personal M365 outlook.com account that locks up both Tbsync and Thunderbird. My O365 calendars sync with no issues.


__________________________
Jim Davenport
Information Technology/Interactive Media
Bridgeport High School
55707 Industrial Drive
Bridgeport, OH 43912
(740) 635-0853 x 6090

________________________________

**Comment by jobisoft** [comment] 2023-08-29 09:41
To clarify: TbSync (this repository) is not doing any sync operations. This is a manager UI. If you have sync issues, please file a detailed error description at the issue section of the affected provider.
 - [DAV-4-TbSync](https://github.com/jobisoft/DAV-4-TbSync/issues/)
 - [EAS-4-TbSync](https://github.com/jobisoft/EAS-4-TbSync/issues/)
 
 I am going to sunset DAV-4-TbSync soon, because it is not needed anymore, except for iCloud discovery.

**Closed by jobisoft** 2023-08-29 09:41 UTC

**Comment by jobisoft** [comment] 2023-08-29 19:17
I currently have no idea why CardDAV sync could hang, I will need a dedicated issue with more details in the [DAV-4-TbSync](https://github.com/jobisoft/DAV-4-TbSync/issues/) provider.

I think I did fix the sync issues with EAS:
https://github.com/jobisoft/EAS-4-TbSync/issues/234#issuecomment-1697976342

Please test and report in the linked issue.

**Comment by marunjar** [comment] 2023-08-29 20:12
> I am going to sunset DAV-4-TbSync soon, because it is not needed anymore, except for iCloud discovery.

That's a pity as DAV-4-TbSync is able to pull calendar subscriptions from nextcloud, which thunderbird cannot.
Without this, every calendar must be added to thunderbird manually again.

**Comment by jobisoft** [comment] 2023-08-29 20:20
I do not think that is true anymore:

![image](https://github.com/jobisoft/TbSync/assets/5830621/d26404de-c465-4424-91ee-3a73b7f6a9a5)

**Comment by lmkra** [comment] 2023-08-29 21:54
Will this new release be available also on addons.thunderbird.net ?

**Comment by jobisoft** [comment] 2023-08-29 21:56
Do you mean the current beta for TbSync 4.7? Yes, I assume in 2-4 days.

**Comment by RRNYC** [comment] 2024-02-17 00:43
@jobisoft Hi John.  I'm hoping you can help with an issue related to this Microsoft EAS mess they created about four weeks ago.  TBSync connectivity for a legacy Hotmail account was intermittently working for me these past weeks, but has been completely broken since Wednesday.  Nothing I've tried has been successful at restoring that connection via EAS.  

I've tried the MS Office 365 OAuth option.  Despite that I pay for an Microsoft 365 Personal account (and should be able to use that option), TBSync keeps throwing the "User not found (HTTP Error 404)" error:  

![image](https://github.com/jobisoft/TbSync/assets/160291927/927ef196-9c5d-4b91-93ba-bca83741fc20)

Any help would be greatly appreciated (and for which I'll gladly tip).

Thanks!
RR
