### ISSUE TITLE
writeproteted calendar: error at write to calendar

### ISSUE THREAD

**Issue by TobiasLaa** [jobisoft/TbSync#202] opened 2018-12-20 14:05 UTC
## Your environment

TbSync version: Beta Release Channel 1.0.7
Thunderbird version: 60.3.3 32bit

[x] Yes, I have installed the latest available (beta) version from 
https://github.com/jobisoft/TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
Because the calendar ist write protected and also the one-way sync of the TBSync-beta is activated, I expect, that the calendar will only be read, never written

## Actual behavior
I get a write error, but nothiung should be written

## Steps to reproduce
Config a calendar like above (I don't have the permission to write to it) and sync the calendar. 
The initial sync was ok, but the following periodic syncs raise the error 

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

![image](https://user-images.githubusercontent.com/46024111/50289116-28417880-0468-11e9-90c0-d523d4917e50.png)
![image](https://user-images.githubusercontent.com/46024111/50289150-427b5680-0468-11e9-9885-94d424500875.png)
![image](https://user-images.githubusercontent.com/46024111/50289190-5de66180-0468-11e9-9044-40ef53346562.png)

**Comment by jobisoft** [comment] 2018-12-21 22:42
This is not full duplicate of #85 but closely related and its fix will also fix your problem.

**Closed by jobisoft** 2018-12-21 22:42 UTC
