### ISSUE TITLE
TbSync loses manually added DisplayName

### ISSUE THREAD

**Issue by aalexan** [jobisoft/TbSync#268] opened 2019-07-26 10:46 UTC
## Your environment

TbSync version: 1.7
Thunderbird version: 60.8.0 (32-bit) English

[ ] Yes, I have installed the latest available (beta) version from 
https://github.com/jobisoft/TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
I manually create a new contact in the shared  & synced address book (Firstname = "A", LastName = "B", DisplayName = "ABC".
I save the contact, everything looks fine.
I trigger the AddressBook sync.
Once the sync completes, the DisplayName should be "ABC" 

## Actual behavior
In the above scenario, the DisplayName is automatically changed to "A B" after sync.
The same problem occurs when changing the First or Last names: the DisplayName gets altered on sync, not on saving the contact in the local AddressBook.

Shared Address Book is hosted on CPanel/Horde

See also https://github.com/jobisoft/TbSync/issues/246

Thanks for checking!

**Comment by jobisoft** [comment] 2019-07-26 15:55
It sounds like you have the „override display name with first name + last name” option enabled for that account. Can you check the options tab?

**Comment by aalexan** [comment] 2019-07-26 16:14
Thank you John for the quick reply! I was unable to find this option in Thunderbird or TbSync Options.. Can you please specify where I should look for it?
Many thanks!

**Comment by jobisoft** [comment] 2019-07-26 16:46
If it is an EAS account, you find that setting in the third tab in the tbsync account manager of that account. Sorry, I am on the road and cannot make screenshots.

**Comment by aalexan** [comment] 2019-07-26 17:18
It seems that this might not apply in my situation:
![image](https://user-images.githubusercontent.com/48678694/61969037-35b47780-afe2-11e9-97ed-6fa2a4724b86.png)
Is there perhaps a way to alter this setting via Thunderbird's Config Editor?
Thank you again+

**Comment by jobisoft** [comment] 2019-07-26 18:55
That account is using the caldav/carddav provider, who does not have that option.

It could be, that this is a bug, which I have to look at. But I will not be able to work on this for about 3 weeks. 

You could check, if this is already fixed in the latest version of TbSync for Thunderbird 68 (Beta). You can install Thunderbird 68 (Beta) in its own directory and start it with ‘thunderbird -p’ to create a new profile, so it does not touch your existing installation. You can get the new TbSync version simply via the AddonManager of Thunderbird 68 (Beta).

**Comment by jobisoft** [comment] 2019-07-27 07:51
Oh no, Thunderbird started to release Thunderbird 69 via the Beta channel, before Thunderbird 68 ESR has been released. That is stupid :-( You can no longer test Thunderbird 68. Sorry, you have to wait till I a can look at this.

**Comment by jobisoft** [comment] 2019-08-19 22:33
Is this still valid? Can we postpone this until TB68 is out, so you can run this against the latest version?

Alternativly, can you create a test account on the same server for me, so I can reproduce that here?

**Comment by jobisoft** [comment] 2019-09-17 12:20
I cannot reproduce that with TB68. Reopen, if this is still an issue for you. But I will definitly need a test account on your server, to investigate this.

**Closed by jobisoft** 2019-09-17 12:20 UTC
Labels: bug
