### ISSUE TITLE
Add-on incompatibility with TB 102 release.

### ISSUE THREAD

**Issue by RyanHir** [jobisoft/TbSync#583] opened 2022-05-30 03:44 UTC
## Your environment

Windows 11 22H2 (Insider) x64

TbSync version: 3.0.2
Thunderbird version: 101.0b4

## Expected behavior
Add-on is enabled as with Thunderbird Stable (91.xx)

## Actual behavior
Add-on is disabled by Thunderbird due to an incompatibility with the upcoming Thunderbird 102 release.

## Steps to reproduce
1. Install Thunderbird Stable (91.xx)
2. Install TbSync
2. Install the Thunderbird beta
3. Check Add-on manager
![image](https://user-images.githubusercontent.com/4690732/170913217-470510c7-e558-4aaa-97cb-5f27f407f987.png)

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by panther7** [comment] 2022-06-07 12:16
102b2 too

**Comment by panther7** [comment] 2022-06-15 16:42
TB 102 will be soon. Actually probably last beta 5.

**Comment by chaos-prevails** [comment] 2022-06-27 16:26
Hello,

will there be a new version which is compatible with TB102? I think the new caldav/carddav functionality of TB102 is not yet the same as TBSync provided (e.g. subscribe/unsubscribe to calendars after initial setup IMHO is not possible with TB102).

**Comment by ewolff** [comment] 2022-06-29 05:58
After an update to the 102.0 release, tbSync is disabled and therefore won't work.

**Comment by panther7** [comment] 2022-06-29 06:13
Maybe this addon is dead(?)

**Comment by jobisoft** [comment] 2022-06-29 06:15
It is not dead, working on the update.

**Comment by ewolff** [comment] 2022-06-29 06:18
Great! Without the plugin, Thunderbird is pretty useless to me.

**Comment by jobisoft** [comment] 2022-06-29 06:56
FYI: We have https://addons.thunderbird.net/addon/addon-compatibility-check/ which allows you to see which of your used add-ons work in 102, before upgrading. Spread the word!

**Comment by chaos-prevails** [comment] 2022-06-29 07:22
Hi John,

thanks a lot as well from our side. I was always hoping/thinking that TBSync will eventually get integrated into TB, together with CardBook (but maybe that is a too long shot). Or is this never going to happen, so there will always be the plugins?

**Comment by mysteriously** [comment] 2022-07-01 05:35
Any news, please?

**Comment by jobisoft** [comment] 2022-07-01 06:46
ETA : 2 weeks. 

For CardDAV users, I suggest you try out the new built-in support. Migration is not possible. Remove the old TbSync address books and set them up anew as Thunderbird CardDAV address books:

![image](https://user-images.githubusercontent.com/5830621/176839468-e20db6a6-21b8-4412-9a89-557ef1375081.png)

Sorry, German screenshot, but I hope you get the idea.

**Comment by mbiebl** [comment] 2022-07-04 22:36
Wasn't there an attempt to more closely integrate cardbook and tbsync with each other?
What happened to those efforts? Especially in light of the changes in TB 102.

**Comment by jobisoft** [comment] 2022-07-04 22:46
I was young, I had dreams. Now I have kids.

**Comment by yuanh9** [comment] 2022-07-05 10:11
> Hi John,
> 
> thanks a lot as well from our side. I was always hoping/thinking that TBSync will eventually get integrated into TB, together with CardBook (but maybe that is a too long shot). Or is this never going to happen, so there will always be the plugins?

Same questions.

**Comment by dilyanpalauzov** [comment] 2022-07-16 05:31
The advantage of TBSync/DAV-4-TbSync over the integrated in Thunderbird CalDAV/CardDAV clients is that TBSync can enforce authentication.  This means for servers, which deliver different, correct results for authenticated and unauthenticated requests, the user can set in TBSync/DAV-4-TbSync to authenticate.

The missing functionality for Thunderbird is reported at https://bugzilla.mozilla.org/show_bug.cgi?id=1722296 .

It would be great, if TBSync/DAV-4-TbSync continue to offer this functionality, which lacks in TB102.

**Comment by jaymzh** [comment] 2022-07-18 19:36
> ETA : 2 weeks.

Thanks for your work on this. I know open-source work is a bit thankless sometimes.

Is there a PR/branch we could test?

**Comment by panther7** [comment] 2022-08-04 11:27
> ETA : 2 weeks.

...no commit, no branch, nothing for testing

**Comment by bjo81** [comment] 2022-08-04 11:34
> ...no commit, no branch, nothing for testing

Stop complaining, start donating.

**Comment by Meliphagidae** [comment] 2022-08-13 14:15
> I was young, I had dreams. Now I have kids.
> 
> Edit: That means my priorities have shifted. My kids are awesome, and I rather spend my free time with them, than coding (which I do already enough during my day job).

Congratulations! Enjoy your kids as long as they (1+) are little. Anyhow 1 question: Does it mean you have stopped working on TbSync, Provider für CalDAV & CardDAV and Category Manager? Or does it just explain the extension of ETA?

**Comment by jobisoft** [comment] 2022-08-13 16:31
This cycle is rather out-of-line for my standards, I usually do not need this long. I am working on an update for TbSync + EAS. CalDAV/CardDAV will be reduced to autodiscovery, but syncing will use Thunderbirds methods (you actually do not need TbSync for that anymore). CategoryManager is difficult, all the UI is gone, have not got my head around how I will address this. Will do that after release of TbSync update.

**Comment by dilyanpalauzov** [comment] 2022-08-13 17:58
<  I am working on an update for TbSync + EAS. CalDAV/CardDAV will be reduced to autodiscovery, but syncing will use Thunderbirds methods (you actually do not need TbSync for that anymore). 

Currently in DAV-4-TbSync it is possible to tell the CUA to authenticate, even if the server does not request this (that is the server does not return 401, but valid results for unauthenticated users).  Will syncing in the future also send credentials to the server, once the setup is performed by DAV-4-TbSync and the server does not reply with 401 on missing credentials?

**Comment by jaymzh** [comment] 2022-08-15 21:47
For what it's worth, the new CardDAV support was sufficient for all my uses of TbSync, so I was able to move to that.

For those wanting to do so, it's not super intuitive. Add a new address book, just CardDAV and then use the url `https://www.googleapis.com/.well-known/carddav` .

Thanks @jobisoft for this addon... even though I no longer need it, it's been an amazing tool, and as an opensource developer myself, I appreciate the time and effort that goes into maintaining it. Hopefully as more of these features make it into TB natively, you will have to maintain less and less code.

**Comment by chaos-prevails** [comment] 2022-08-16 08:19
> This cycle is rather out-of-line for my standards, I usually do not need this long. I am working on an update for TbSync + EAS. CalDAV/CardDAV will be reduced to autodiscovery, but syncing will use Thunderbirds methods (you actually do not need TbSync for that anymore). CategoryManager is difficult, all the UI is gone, have not got my head around how I will address this. Will do that after release of TbSync update.

Hi John,
also from me a big thank you for your support (I'm the developer of a tiny TB addon, and I really appreciate your work). 

If you write "reduced to auto-discovery".. does that also include the managing of subscriptions (e.g. after setup of a calendar resource, you can go back at a later time to subscribe/unsubscribe calendars which have been auto-discovered)? TBSync is such a useful addon, and for us auto-discovery, and the managing of subscriptions functionality after initial setup makes all the difference. It would be great if that functionality could be included in TB at a later stage.

@jaymzh as far as I know, TB should normally auto-discover all available calendars automatically with just the "root" URL. We use e.g. sogo, and its just https://sogo.mydomain.org, and also with the TB only calendar subscription, it will show you all available calendars (but AFAIK you cannot go back to this "resource" if you want to subscribe to another calendar <-- this is what was possible with TBSync).

**Comment by jobisoft** [comment] 2022-08-16 09:14
> If you write "reduced to auto-discovery".. does that also include the managing of subscriptions (e.g. after setup of a calendar resource, you can go back at a later time to subscribe/unsubscribe calendars which have been auto-discovered)? TBSync is such a useful addon, and for us auto-discovery, and the managing of subscriptions functionality after initial setup makes all the difference. It would be great if that functionality could be included in TB at a later stage.

Yes, that part will stay, only the actual syncing will be replaced by Thunderbirds own native CardDAV sync.

**Comment by jretxaniz** [comment] 2022-08-30 06:46
Hello John. I have a medium sized network in a local government and we use your plugin in combination with Exquilla, working well together. This Exquilla has been maintained by a German company for a couple of years, and we pay for the license every year. I think that it is the fairest way for there to be fair compensation for their work and for us to be sure that we will be updated.

**Comment by jretxaniz** [comment] 2022-08-30 06:51
Even my problem is that I would like to contribute but I can't use paypal to make payments at work

**Comment by straygecko** [comment] 2022-09-08 01:37
> > If you write "reduced to auto-discovery".. does that also include the managing of subscriptions (e.g. after setup of a calendar resource, you can go back at a later time to subscribe/unsubscribe calendars which have been auto-discovered)? TBSync is such a useful addon, and for us auto-discovery, and the managing of subscriptions functionality after initial setup makes all the difference. It would be great if that functionality could be included in TB at a later stage.
> 
> Yes, that part will stay, only the actual syncing will be replaced by Thunderbirds own native CardDAV sync.

Oh no!  TB native CardDav sync is broken.  I had to downgrade to keep using TBSync and have been waiting for TBSync compatibility with 102 so I can upgrade.  See https://bugzilla.mozilla.org/show_bug.cgi?id=1736289

**Comment by fridrich** [comment] 2022-09-14 13:51
> 

I would love to know where is this blocking. Can the public help somehow? Are we left out there hanging?

**Comment by stvhay** [comment] 2022-09-15 22:48
I am definitely interested in updating, but I am happy to wait on v91 of Thunderbird until we have a solution. I have to say, this extension is not the only place where I see a very thin infrastructure supporting email. There are very few viable (free) CalDAV and CardDAV implementations, DKIM software seems to come down to OpenDKIM (limping along) and dkimpy (one main developer). 

Please consider supporting the people that are keeping this infrastructure alive, and be patient. It doesn't look like there are necessarily developers clamoring to pick up the torch on these technologies.

**Comment by jobisoft** [comment] 2022-09-16 07:58
For EAS, please head over to:
https://github.com/jobisoft/EAS-4-TbSync/issues/167#issuecomment-1249030422

In general, this is a dupe of:
https://github.com/jobisoft/TbSync/issues/591

**Closed by jobisoft** 2022-09-16 07:58 UTC

**Comment by jretxaniz** [comment] 2022-09-19 07:25
Everything working fine for me. Thanks a lot. I tried to contribute, hoping it will work for you

**Comment by panther7** [comment] 2022-09-19 08:15
DAV-4-TbSync need update too.

**Comment by Mike-Sbg** [comment] 2022-09-20 09:27
Can you please help me:

I tried to test the beta Version on Windows 10

Downloaded the Files ... unpacked them and started the makefile.bat.
With 7-zip installed it generated die .xpi file. 
But when I try to add it to TB102 it tells me, that it is not comtabible.

What was my mistake?

**Comment by jobisoft** [comment] 2022-09-20 09:45
There is not yet an update for DAV. EAS is at 75%. After that, I will work on DAV.

**Comment by Hydranet** [comment] 2022-09-20 17:25
> ETA : 2 weeks.
> 
> For CardDAV users, I suggest you try out the new built-in support. Migration is not possible. Remove the old TbSync address books and set them up anew as Thunderbird CardDAV address books:
> 
> ![image](https://user-images.githubusercontent.com/5830621/176839468-e20db6a6-21b8-4412-9a89-557ef1375081.png)
> 
> Sorry, German screenshot, but I hope you get the idea.
Thanks I didn't know this was builtin now, it also so seems caldav has a builtin feature now because I can connect to my caldav nextcloud just by create a new network calendar or was this there before but never noticed it.
