### ISSUE TITLE
Read-Only mode blocks synching

### ISSUE THREAD

**Issue by gerhardmu** [jobisoft/TbSync#50] opened 2018-02-15 12:09 UTC
When I add a calendar from somebody else I do not want to modify it, just view. on the list of calendars left side I can modify the general setting so as the color of entries. On that place I set the "read only" mode. The positive result is that I cannot set by mistage an event on the wrong calendar. The negative effect is that synching fails now.

**Comment by jobisoft** [comment] 2018-03-05 19:22
Confirmed. I cannot add new items from the server to the local calendar, because it is set as write protected. I know what you had in mind, when enabling write-protect mode, but the way TbSync is operating, this does not work. Using that option is not supported at the moment.

I take "allow write protect mode" as a feature request, but this has low priority. I schedule this for v0.9.

**Comment by jobisoft** [comment] 2018-03-05 19:24
Added it to the official [roadmap](https://github.com/jobisoft/TbSync/wiki/Roadmap) and closing this issue.

**Closed by jobisoft** 2018-03-05 19:24 UTC
Labels: enhancement

**Comment by jobisoft** [comment] 2018-06-01 12:15
Die aktuelle beta (.19) hat nun eine globale one-way sync option:
![image](https://user-images.githubusercontent.com/5830621/40840150-c51d4b64-65a5-11e8-9dec-3dba457dc104.png)

Wenn die aktiv ist, werden die lokalen Änderungen nicht zum Server übertragen und außerdem werden die Änderungen rückgängig gemacht, sodass nach dem sync die lokale Version immer mit der Server Version abgeglichen ist.

Die Standard-Funktion beim Kalender (die du damals benutzt hast) wird von mir weiterhin nicht unterstützt. 

Im Augenblick sehe ich nicht, wie ich das besser hinkriegen kann. 

Feedback wäre super. 

P.S. Du brauchst wirklich beta 19, in beta 18 gibt es zwar die Option schon, aber sie funktioniert noch nicht.

**Comment by spaetz** [comment] 2018-10-11 07:29
Hi there, just fell in the same trap as I enabled "read-only" in Lightning to enforce a read-only mode. It would be great to just add a hint somewhere that this leads to a failure and the "one-way sync" setting in TBSync is the preferred way.
Thanks for TBSync, will be donating soon.

**Comment by jobisoft** [comment] 2018-10-11 07:50
I am still trying to find a good solution here, it is the next thing to be impl.

**Comment by dartcafe** [comment] 2018-10-27 10:03
I would like to set a read only flag for each calendar and/or adress book to enable an indiviual one-way snc. 

I have a SOGo installation with shared address books. Some of the are read only and sync always throws an error on syncing the read only address book. The second sync finishes without error then. 

Additionally local changes on read only calendars/address books should be kept unless updated by the server and not thrown away without warning.
