### ISSUE TITLE
No confirmation is sent when replying "I will attend"

### ISSUE THREAD

**Issue by tvass** [jobisoft/TbSync#73] opened 2018-05-03 13:59 UTC
## Your environment

TbSync version: 0.7.7
Thunderbird version: 52.7.0+build1-0ubuntu1

[X] Yes, I have installed the latest available (beta) version from 
https://github.com/jobisoft/TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

Tryed with (0.7.7.7)

## Expected behavior
When someone sends you a calendar invite, he should see your answer (I will attend,  I might attend, I will NOT attend).

## Actual behavior
No confirmation is sent (with or without  check box for "Support Outlook 200 and Outlook 2002/XP") when you answer (ie: "I will attend").

Local Calendar in Thunderbird / Lightning is updated) but your status seems not to be updated on Exchange server.

## Steps to reproduce
1. Send a calendar invite from an other user.
2. Confirm meeting from your Thunderbird.
3 (a) Go to OWA to see that your current status is still "Need to answer".
3 (b) From the meeting creator, you can see that there is no answer.

** Thu May 03 2018 09:56:20 GMT-0400 (EDT) **
```
** Thu May 03 2018 09:56:20 GMT-0400 (EDT) **
[JavaScript Error: "NS_ERROR_MALFORMED_URI: Component returned failure code: 0x804b000a (NS_ERROR_MALFORMED_URI) [nsIMsgSend.sendMessageFile]" {file: "file:///home/thomas/.thunderbird/ilvlua5s.default/extensions/%7Be2fda1a4-762b-4020-b5ad-a41df1933103%7D/components/calItipEmailTransport.js" line: 319}]

** Thu May 03 2018 09:56:20 GMT-0400 (EDT) **
[JavaScript Error: "[Exception... "Component returned failure code: 0x804b000a (NS_ERROR_MALFORMED_URI) [nsIMsgSend.sendMessageFile]"  nsresult: "0x804b000a (NS_ERROR_MALFORMED_URI)"  location: "JS frame :: file:///home/thomas/.thunderbird/ilvlua5s.default/extensions/%7Be2fda1a4-762b-4020-b5ad-a41df1933103%7D/components/calItipEmailTransport.js :: calItipEmailTransport.prototype._sendXpcomMail :: line 319"  data: no]" {file: "resource://calendar/modules/calProviderUtils.jsm" line: 634}]
```
%7Be2fda1a4-762b-4020-b5ad-a41df1933103%7D = Lightning add-on.

**Comment by jobisoft** [comment] 2018-05-03 20:42
Can you check, what E-Mail identity is assigned to your calendar?

![image](https://user-images.githubusercontent.com/5830621/39601727-3e8dd84a-4f23-11e8-85e8-62dd03b9b91f.png)

**Comment by kernel23** [comment] 2018-05-03 21:35
It is associated to my Exchange account.

**Comment by jobisoft** [comment] 2018-07-03 19:36
That is not yet fully implemented. It is scheduled for the 0.7 branch, but I cannot tell you when.

**Comment by xiadong1994** [comment] 2018-08-27 03:14
Same issue. Have it been fixed?

**Comment by moritzhoewer** [comment] 2018-10-14 13:47
Looking forward to having the attendance status sync properly...it does not work at all for me (Calendar in OWA has the meeting set as "confirmed attendance" whereas in Thunderbird it shows as needing a reply.
I can set it to "accepted" in Thunderbird, but after rebooting and reopening Thunderbird on the next day, it's back to needing a reply.

Also something triggers the Exchange Server to send me automatic E-Mails about it having "updated" appointments that are supposedly "out of date" (seemingly at random). Not sure what exactly is causing that.

**Comment by jobisoft** [comment] 2018-11-04 23:34
This issue was moved to jobisoft/EAS-4-TbSync#8

**Closed by jobisoft** 2018-11-04 23:34 UTC
Labels: meeting stuff postponed to v0.8

**Comment by ohmer1** [comment] 2019-05-09 17:17
Hi,

I see you moved the issue to the EAS repository, but I have the same problem using Caldav. Should I open a new issue in the caldav repository?

**Comment by jobisoft** [comment] 2019-05-10 20:41
If you see this issue with CalDAV, than thisis not an issue with TbSync but with lightning itself, since all TbSync is doing for CalDAV is to autodiscover your calendars. TbSync is just adding them to Lightning and Lightning takes care of the syncing stuff.

I assume, your issue is due to not having associated an email identity:
![image](https://user-images.githubusercontent.com/5830621/57555464-9a155280-7374-11e9-9e15-99c5ae6a5307.png)

I will add an option to TbSync itself, so you can do that in the manager as well. For now you have to do that in Lioghtning.
