### ISSUE TITLE
Exchange calendar appointments lost after disable/enable instructions of v0.7.9

### ISSUE THREAD

**Issue by ThomasA** [jobisoft/TbSync#98] opened 2018-07-02 07:26 UTC
## Your environment

TbSync version: 0.7.9
Thunderbird version: 52.8.0

- [x] Yes, I have installed the latest available (beta) version from 
https://github.com/jobisoft/TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.
*In fact, the latest version seems to have caused it.*

## Expected behavior
After the most recent upgrade of TbSync, a dialog appeared instructing me to disable my accounts in TbSync and then re-enable them again. The message also stated that I could synchronise my appointments prior to doing this. I made sure to tell it to sync everything before I disabled the accounts. I then re-enabled the accounts, after which I expected to have all my appointments in my calendar again.

## Actual behavior
After re-enabling my accounts, almost all of the appointments in my work calendar are gone. Unfortunately, they are not just gone from Thunderbird. TbSync seems to have deleted them from the Exchange server and now they have disappeared from all my devices. Strangely, a few appointments remain. I do not know what is special about these few remaining appointments that has caused them to survive.
I have another, private calendar on another server. This calendar does not seem to have lost any appointments. The IT department at my workplace is currently attempting to restore my calendar from a backup. In the meantime, I am missing all the meetings I should have been to...

## Steps to reproduce
I do not know how to reproduce this and frankly, I do not dare to try. It is bad enough as it is. I hope for this to never happen again.

**Comment by jobisoft** [comment] 2018-07-02 08:02
Damn, they are lost for good? Please remove all accounts from the tbsync account manager!

**Comment by jobisoft** [comment] 2018-07-02 08:08
I disabled 0.7.9 

DO NOT USE IT UNTIL THIS IS UNDERSTOOD!

**Comment by ThomasA** [comment] 2018-07-02 08:09
At least they are not visible on any of my devices (desktop PC with TbSync 0.7.9, laptop PC with TbSync 0.7.9, and smartphone running Android). I am currently waiting for IT technicians to see if they can restore a backup from last week.

**Comment by jobisoft** [comment] 2018-07-02 08:17
I am deeply sorry, this did not show up during beta test phase and also not on my system. What type of server are you using? Exchange On-Premises?

Please remove any account from the TbSync account manager, but stay with 0.7.9, but do not use it. Also, do not downgrade. Wait till this is understood. Can you give feedback on your current status?

**Comment by jobisoft** [comment] 2018-07-02 09:02
The error was caused by the sync after the update prior to disable/re-enable. I did not suspect that to be a cause for an error.

From .7 to .9 I had to change the DeviceType from "Thunderbird" to TbSync". After you updated and synced, the new DeviceType was send, but it still used the same DeviceID (the mztbxxxxxx u could see in the manager UI). That "unmachted pair" of DeviceType and DeviceID caused the trouble, your server stumbled. 

I have no idea, why only some items are missing. For tasks and contacts (where none is missing) I assume there was nothing to sync and so there was no faulty communication between TbSync and your Server. For the partially missing calendar items, I have no idea.

This is not an excuse, but [accepting appointments is not handled stable yet](https://github.com/jobisoft/TbSync/wiki/What-is-TbSync%3F#known-issues-and-missing-features), maybe they have never been synced to the server? Have you seen those items on your Android at some time?

**For the future: On major updates I will from now on create a backup of your local Thunderbird data, so something like this will not happen again.**

Please report back, when you get feedback of your IT department. I am truly sorry for your hassle.

**Comment by ThomasA** [comment] 2018-07-02 09:06
I noticed that accepting appointments did not seem to work properly, so I started doing that in the EWS recently. However, only few of my appointments were by invitation, so most of those that have disappeared have been created by myself.
I may not hear from the IT department about it until tomorrow or Wednesday. They are working slowly due to vacation.

**Comment by jobisoft** [comment] 2018-07-02 16:04
If the IT department is able to restore you data, please log in to your web interface to make backups yourself, so you have something at hand. 

I will then send you a new version of TbSync. Do not use 0.7.9.

**Comment by UCIS** [comment] 2018-07-02 16:52
I think I may have lost some appointments due to this bug as well. I just dismissed the update dialog and later noticed items were missing from my Outlook and Android clients.

At first the items were still present in Thunderbird, until I disabled and re-enabled the account in Thunderbird (hoping this would prevent it from syncing the deletions back to thunderbird; then finding out that I could not access the calendar anymore with the sync disabled). At this point the items were also gone from Thunderbird.

After further investigation it seems like I lost all appointments from 2018 and some recurring appointments active in 2018. I tried the "Recover Deleted Items" method via the Outlook client, but nothing was found in there. Do you have any clue on how the items were deleted (it doesn't look like a normal forced deletion, since then the items should still be preserved on the server for some 30-60 days in this case)? Any other folders I should look for deleted items?

I think I have another computer with a synchronized Thunderbird at the office, which has not been powered on for about a week, so I will try to recover the data from this computer tomorrow. Do you have any advice to prevent deletion of the data before I get a chance to export the data (other than just unplugging the network connection)?

**Comment by jobisoft** [comment] 2018-07-02 16:59
When you power up that pc, make sure it does not have a valid internet connection, so TbSync is not able to do anything to your data.

When Thunderbird is up and running, disable or remove TbSync. The local calendars will not be removed by that. Use the lightning export function to make backups of your calendar. Also backup your contacts.

I will release a new version, which should prevent data loss. But I am still investigating to what happend.

Are you also on a on-premises exchange server?

**Comment by jobisoft** [comment] 2018-07-02 17:02
Clarification: Disable/Remove the entire AddOn. Do not use the TbSync Account Manager at all!

**Comment by jobisoft** [comment] 2018-07-02 17:11
Clarification # 2: Since TbSync cannot do anything without network connection, I now think it would be more wise to backup your data as fast as possible, without doing anything else beforehand.

This is very difficult for me, I just do not want to cause more dataloss...

**Comment by UCIS** [comment] 2018-07-02 17:58
@jobisoft Yes, this is also an "on-premise" Exchange server.

I gave a local backup on the computer running Thunderbird another shot. I restored all files in the profile/calendar-data folder, and copied the relevant (Exchange account) entries (starting with calendar.registry.) from the backed-up prefs.js to the current one. It seems that disabling and enabling the TbSync account earlier changed the calendar registry GUID, which is why my first attempt to restore the data this way failed.

I got the backup files from a weekly remote backup, but a few days ago there was also a copy in Windows' previous versions storage, so maybe this can help others to get some data back.

Now I have to figure what to do next. I'll probably try to export the data, revert the calendar database to the current version and import the data into a separate calendar so I can compare the two. I disabled all calendar sync plugins before restoring the data files to prevent interference with Google Calendar sync.

I can probably use a similar method to make sure none of my contacts were lost.

@jobisoft Thanks for your help and making this plugin. Unfortunately things like this do happen, and I have re-learned a wise lesson: always make sure you have backups and check that they are working and complete.

**Comment by jobisoft** [comment] 2018-07-02 18:11
When you have all your backups and no further damage can be done, would you take the call for TbSync 0.7.10?

I fear that migrating the missing items from the backup will be tedious. Maybe this helps?
https://github.com/martinp26/ics-tools

**Comment by UCIS** [comment] 2018-07-02 18:35
@jobisoft If you think 0.7.10 won't do any more damage then sure, I will give it a try. However, at this moment 0.7.9 seems to be working alright - I can sync recovered items from TB to Outlook. As for lost calendar data, there were only two relevant items, everything else was in the past anyway. I got one [error trying to sync a recurring event to Exchange](http://foto.kwaaknet.org/uploads/1e3e2db51b5be27c3ada984a8b74bdfe.png). The TbSync debug.log is empty. This might be completely unrelated though.

**Comment by jobisoft** [comment] 2018-07-02 18:38
Nonono, I revoked 0.7.9 for a reason, do not use it, please! 0.7.10 will be ready tomorrow.

Also do NOT downgrade to 0.7.7!

**Comment by jobisoft** [comment] 2018-07-03 11:29
v0.7.10 is out. If you have your backups I would like to use your other PC as a test area, if you dare.
After you have backuped all calendar and contact data from that pc, install v0.7.10. This will happen:
- all accounts will be resetted (disabled)
- all local calendars and address books will be backuped

You should then be able to enable your accounts again and the current data avail on the server should sync down.

That would be an awsome help to make sure this is fixed. 

TbSync v0.7.10 can be downloaded [here](https://github.com/jobisoft/TbSync/releases/download/v0.7.10/TbSync-0.7.10.xpi)

**Comment by UCIS** [comment] 2018-07-03 18:29
Thanks, I have installed the update on the TB running 0.7.9 previously. That worked. After I enabled the extension again, the backup calendar remained and a new one was created and synced from the Exchange server.

One strange appointment appeared, with no subject and only myself as an attendant. I am not sure if this was there before, maybe it was created by the previous attempt to restore the appointments. I still could not copy the recurring appointment from Thunderbird to Exchange, [with the same error](http://foto.kwaaknet.org/uploads/1e3e2db51b5be27c3ada984a8b74bdfe.png), but I have successfully created the appointment in Outlook and it synced to Thunderbird.

I will try to install the update on my work PC tomorrow (which is still on 0.7.7) and see how that works out.

**Comment by jobisoft** [comment] 2018-07-03 19:12
Thanks for your feedback, sound like 0.7.10 is working as intended. Lets see what will happen tomorrow...

**Comment by jobisoft** [comment] 2018-07-03 19:13
@ThomasA Any news from your side? Any chance you have local backups of your thunderbird profile folder? WindowsBackup or something like that? News from your IT department?

**Comment by UCIS** [comment] 2018-07-04 08:04
@jobisoft the update on the other computer seems to have worked well. Two things I noticed:
- My android phone has duplicates of one of the previously lost recurring appointments. Perhaps the Android client does not think the items were deleted, perhaps it found them in some other folder?
- The back-up is corrupted. I am not sure if this was the case before the backup was made (I did not check closely), if so it might give a clue as to what went wrong in the first place. The details (subject, start time, end time) of the recurring appointment were changed to those of another single occurrence appointment. The recurrence schema is still there.

Just a guess - maybe the change of client identifier triggered the server to generate new IDs for all appointments (thinking it was an entirely new client), partially overlapping with previously existing IDs, then TbSync would mismatch items and incorrectly update or delete?

**Comment by jobisoft** [comment] 2018-07-04 09:10
But if TbSync v0.7.10 worked, you should now have a clean backup of your data in Thunderbird, right? Or is that backup corrupt?

**Comment by ThomasA** [comment] 2018-07-04 09:12
Our IT department has now restored my calendar here. They have created a copy of my calender on the Exchange server from which I can copy appointments back.
I noticed another "funny" detail in my calendar this morning (in the corrupted so-far-not-restored calendar on the Exchange server): some appointments (mostly back in January and February) have been duplicated or even appear in triplicates. The new copies of the appointments are not completely identical. Some appear with differing reminder settings and seem to have participants mixed up with other appointments.

**Comment by jobisoft** [comment] 2018-07-04 09:48
@ThomasA Then please update TbSync on all your computers to v0.7.10, to get rid of the faulty version. So you do have to disentangle your data, but basically you are save now as well?

**Comment by ThomasA** [comment] 2018-07-04 09:51
It seems clear that the data *can* be saved. Right now I am just waiting for IT services to make them available to me in some other way. The Exchange EWS does not let me copy the appointments from the temporary calendar to my main calendar...
I supposed I can eventually get rid of all the duplicate/triplicate appointments and replace them by the originals from the backup.

**Comment by jobisoft** [comment] 2018-07-04 09:55
@UCIS @Android All I am doing is guessing, because this error remains strange. I think your android is also in some sort of messed up state. It would be interesting to see what happens, if you sync there fresh as well: Remove the account and set it up again, but I do not dare to ask that. Does your android contain data which is otherwise lost, or do you have all data in the clean backup of your second work pc? 

Backup android data as well, before doing anything there?

**Comment by jobisoft** [comment] 2018-07-04 10:07
@ThomasA But you should be able to export the temporary calendar (which gives you a backup file which you can actually save somwhere). If that backup contains all your data, you can remove any data from your main calendar and import the backuped file. All within the webinterface of your exchange server. Maybe double check that approach with you IT dep.

A side note: Your university obviously uses a large scale exchange server, whose main protocol is EWS (Exchange WebServices). Since TbSync is working, it also supports EAS (Exchange ActiveSync). EWS is fare more poweful then EAS, so after this is issue is resolved, I suggest to switch to an EWS Addon, which should fit your needs better (access to group calendars/shared calendars). You can of course continue to use TbSync, I just wanted you to know the differences.

**Comment by ThomasA** [comment] 2018-07-04 10:22
Unfortunately the web interface does not seem to have an export option, but I will check with IT.

I actually switched to TbSync earlier this year, because the plugin I was using before is apparently not updated any more and I could not use it in newer versions of Thunderbird. It was some fork of this one: https://github.com/Ericsson/exchangecalendar, but I do not remember which fork anymore. I cannot find it in Thunderbird's add-on listing anymore...

**Comment by jobisoft** [comment] 2018-07-04 10:32
That fork is the most recent one, yes. But they are (currently) not able to make the transition to TB60+ (but it should be working with TB52). 

I offered help, but this is all in a very early stage and not usable yet. If this goes as planed, they will create an "Adapter AddOn" which can be installed alongside of TbSync, which will provide true EWS support in TbSync. But it is currently just a prototype without any EWS functionality, we are still in the "will this work out?" phase.

**Comment by jobisoft** [comment] 2018-07-04 10:34
@ThomasA Have you updated to 0.7.10? If so, can you see the temporary calendar in the TbSync account manager? If so, you could download it there and use Thunderbird to export your calendar.

**Comment by UCIS** [comment] 2018-07-04 17:39
@jobisoft the backup made after the v0.7.7 to v0.7.10 update was corrupted: appointments seem to have been mixed up. This may have been caused by v0.7.7 pulling changes from the server yesterday. Might be the same as described by @ThomasA .

@ThomasA if you have an offline Outlook (maybe it works online, maybe even in MSIE/edge?), you can switch the calendar to list view, ctrl-a ctrl-c and ctrl-v into another calendar. If you enable both calendars in Thunderbird you could probably export and import from there, but I think that may alter some details a bit if the appointments weren't originally created via Thunderbird.

**Comment by ThomasA** [comment] 2018-07-04 17:43
@jobisoft I removed the accounts in TbSync 0.7.9 altogether, upgraded to 0.7.10, and then added my accounts from scratch. I do not think I saw any temporary calendar in that process. Anyway, things seem back to normal now; the IT department eventually restored the backup into my main calendar and it seems to have worked without errors.

@UCIS I do not have Outlook on my PC (it's Linux). That is why I am trying to do everything through the Exchange web interface (and Thunderbird via TbSync).

**Comment by jobisoft** [comment] 2018-07-04 17:59
@ThomasA I am very glad to hear that, very very glad. 
@UCIS Are you back to normal as well?

Any chance you both could tell me wich version of exchange your are using? 2003? 2007? 2010? 2013? 2016?

**Comment by ThomasA** [comment] 2018-07-04 20:12
The web interface here seems to say that Exchange is version 14.3.123.0. Does that make sense?

**Comment by jobisoft** [comment] 2018-07-04 20:14
That is 2010, thanks.
https://de.m.wikipedia.org/wiki/Microsoft_Exchange_Server#Geschichte

**Comment by UCIS** [comment] 2018-07-05 19:20
@jobisoft I'm on Exchange 8.3.83.0 with OWA 8.3.389.2. That would be 2007.

**Comment by jobisoft** [comment] 2018-07-05 19:42
So it is not limited to a single version. Thanks for the information.

**Comment by jobisoft** [comment] 2018-07-07 20:31
Mozilla has just released 0.7.10 so it will now update all users and get the faulty version out of this world. I hope I can close this issue soon...

**Closed** 2018-08-02 20:00 UTC
Labels: Critical Bug
