### ISSUE TITLE
TB 95.0b1 is applying dark theme to TbSync Accounts Manager Window and is making parts illegible

### ISSUE THREAD

**Issue by DavidBE-UK** [jobisoft/TbSync#549] opened 2021-11-04 17:30 UTC
## Your environment

TbSync version: 3.01
Thunderbird version: 95.0b1

## Expected behavior
Previous behaviour of TbSync window ignoring TB being set to dark theme, OR a properly thought out dark theme for the TbSync window.

## Actual behavior
A dark theme is applied but with e.g. white text on a white background making parts unreadable.

## Steps to reproduce
Update TB to 95.0b1. Go to Add-ons Manager>Themes and enable Dark. Open TbSync window.

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by chase9** [comment] 2021-11-08 13:38
To elaborate, really all I see needing to be changed is the tab bar and hyperlink color. Here's a screenshot from my computer: 
![image](https://user-images.githubusercontent.com/6013163/140751670-901ca32b-de42-4f94-a657-824419271ed6.png)

Using Arc-Dark on KDE

**Comment by DavidBE-UK** [comment] 2021-11-08 16:33
Rather more than that, with TB using its standard Dark theme on Windows 10
![TbSyncwindow1](https://user-images.githubusercontent.com/49217481/140780884-99037353-a8f7-474a-b875-20f968a46c87.jpg)

![TbSyncwindow2](https://user-images.githubusercontent.com/49217481/140780954-7a09c544-e314-48a5-ac1c-75a1bad00e03.jpg)

**Comment by DavidBE-UK** [comment] 2021-11-15 17:08
Just adding this is still an issue in TB 95.0b3.

**Comment by jobisoft** [comment] 2021-11-15 17:12
I will fix it once I officially releases this for TB Beta. How do you even install TbSync in TB95, does it not say incompatible? 
https://addons.thunderbird.net/addon/tbsync/versions/

**Comment by DavidBE-UK** [comment] 2021-11-15 17:46
Can't remember which add-ons I had to do it to, but all add-ons that changed to 'incompatible' after updating TB to the first 95 beta I downloaded the xpi, changed to .zip, then edited the manifest strict_max_version to 95.* and re-installed the altered .zip via the option in the menu in the add-ons page (don't even have to change back to .xpi these days), which got all the add-ons affected working again, and all without any fault (for my use of them) other than this dark theme issue with the TBSync window. (I even have to do it to the English (GB) Language Pack to get 'colour' back in the TB menus instead of color.) TBSync is actually working fine for the actual syncing with my outlook.com address book and calendars in TB 95.0b3 and I usually don't need to open its window anyway - I only saw this because TBSync 'lost' my main outlook.com calendar after the 95 update for some reason, although it kept all my other added-to-outlook.com calendars, but disabling then re-enabling the account in the TBSync window re-discovered the main outlook.com calendar.

I am not complaining at all if an add-on doesn't work (or fully work) with the betas - I'm actually rather surprised how seldom there's a problem. I just report issues I find to give the developer a heads-up about a forthcoming issue (especially for those extension developers - not you - who are not pro-active and don't look for a problem until the complaints after the public release that breaks the extension).

**Comment by jobisoft** [comment] 2021-11-15 18:18
I was just worried that something broke, which lifts the max_version restriction. I will have some time for my add-ons to do minor fixes in the coming weeks, but the next big time slot is around end of year.

Reporting those bugs is fine, thanks!

**Comment by panther7** [comment] 2022-10-19 15:37
TbSnyc in darkmode still broken.

TbSync v4.3
TB: 102.3.3

![2022-10-19 17 36 30](https://user-images.githubusercontent.com/3808250/196738257-5c0e101a-6bba-44bb-88df-5af8f6ca4948.png)

**Comment by panther7** [comment] 2023-08-29 12:26
TbSync in darkmode still broken.

TbSync v4.6
Thunderbird v115.1.1
Windows 11

**Comment by jobisoft** [comment] 2024-04-01 10:17
Dupe of https://github.com/jobisoft/TbSync/issues/700

**Closed by jobisoft** 2024-04-01 10:17 UTC
