### ISSUE TITLE
TBSync incompatible with TB 102.1.2 and has been deactivated

### ISSUE THREAD

**Issue by CarlosCastaneda** [jobisoft/TbSync#601] opened 2022-08-22 07:55 UTC
## Your environment

TbSync version: 3.0.2
Thunderbird version: 102.1.2

## Expected behavior
TbSync should be compatible with TB and should work as it used to do

## Actual behavior
Error when writing to calendar. MODIFICATION_FAILED

## Steps to reproduce
Just install the versions in question and it should be reproducible

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

Can't find TbSync Account Manager in order to get debug log. May be because it has been deactivated.
![Screenshot 2022-08-22 095422](https://user-images.githubusercontent.com/17195452/185869248-e0b75684-f5fb-4ca0-a06c-53c80f0c4b6c.jpg)

**Comment by svenmk** [comment] 2022-08-22 08:50
Duplicate of #591

**Comment by doctorcomputergenova** [comment] 2022-08-28 10:30
please update the plugin for thunderbird 102.*.*

**Comment by CarlosCastaneda** [comment] 2022-08-29 09:29
Now it's incompatible with TB 102.2.0... 😞

**Comment by PresGas** [comment] 2022-08-29 12:21
@CarlosCastaneda and @doctorcomputergenova this is a duplicate of #591 

The story is there. You will see there is one primary **volunteer** developer. They have a full time job and a family. Yes it can be frustrating to wait, however there are also still viable and supported T-bird installations that aren't 102.x. 

If I were you, I would mark this closed since it is a duplicate and start following the main one.

**Comment by sphakka** [comment] 2022-08-30 11:51
Stick with TB-91 meanwhile. TB-102 is still in testing phase in many (serious) Linux distros. Kudos to @jobisoft ^^

**Comment by GoeWink** [comment] 2022-09-01 09:14
I have the same problem. TB Sync is the only one which supports connections to my own NAS. So I NEED it. It is as important as the add-on "Category Manager".
Both are in use intensively! If it helps I have no problem to donate! I see that most developer get angry because there are so many updates and necessary changes. That eats much time!
So I hope to see a compatible version as soon as possibel for both add-ons.
BTW: I returned to Windows OS (actrually V10)

**Comment by dsommers** [comment] 2022-09-07 10:16
> Stick with TB-91 meanwhile. TB-102 is still in testing phase in many (serious) Linux distros. Kudos to @jobisoft ^^

Thunderbird 102 was already release end of June, 2022: https://blog.thunderbird.net/2022/06/thunderbird-102-released-a-serious-upgrade-to-your-communication/

There are already complaints in the Fedora devel mailing lists that the 102 upgrade in Fedora 36 breaks lots of add-ons; including TbSync.

**Comment by jobisoft** [comment] 2022-09-16 07:36
Closing as dupe of #591

**Closed by jobisoft** 2022-09-16 07:36 UTC
