### ISSUE TITLE
Each addressbook is shown multiple times

### ISSUE THREAD

**Issue by Letterus** [jobisoft/TbSync#84] opened 2018-06-04 20:33 UTC
## Your environment

MacOS 10.13.5

TbSync version: 0.7.7.20 (beta)
Thunderbird version: 52.8.0 (64 bit)

[x] Yes, I have installed the latest available (beta) version from 
https://github.com/jobisoft/TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior

In the list of the addressbook I'd like to see each of my addressbooks only once.

## Actual behavior

Each addressbook appears 25 times.

## Steps to reproduce

Environment described above. Installed plugins: Lightning, Category Manager, TbSync. Activate TbSync and restart Thunderbird.

> To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

Error log seems to be empty.

**Comment by jobisoft** [comment] 2018-06-04 20:44
If you have time to investigate, I would ask you to disable all your accounts in the TbSync account manager. Does that help? After a restart?

If not, does removing them help? After a restart?

Leave logging enabled. If you ever restart, it should contain some information.

**Comment by jobisoft** [comment] 2018-06-04 20:48
Can someone else confirm this? Is this related to the environment of @Letterus ?

**Comment by Letterus** [comment] 2018-06-04 20:55
Investing my last 12 minutes before lunch into TbSync today. ;)

1. Disabling account(s): No change.
2. Restart TB: No change.
3. Delete: No change (only the 50 addressbooks (originally 2) belonging to that account disappear.)
4. Restart TB: No change.

No error message in the log.

I'll try to delete all user/profile data and check again.

**Comment by Letterus** [comment] 2018-06-04 21:02
Deleted all user data I could find. Problem reappears as soon as I reinstall TbSync.

**Comment by jobisoft** [comment] 2018-06-04 21:19
This will take a while. I need to reproduce that here, but first I need to get a Mac. What model are you using?

**Comment by Letterus** [comment] 2018-06-04 21:38
To don‘t make you do unnecessary work I installed Thunderbird on my wife’s Mac where it was not installed before. I can reproduce this issue but addressbooks are only shown twice there. I don‘t know what makes them appear so often using my Mac.

**Comment by jobisoft** [comment] 2018-06-05 07:16
From https://github.com/jobisoft/TbSync/issues/84#issuecomment-394496376 it looks like, you have to restart TB to see an effect after activating/deactivating TbSync.

Can you verify, that you actually only have to restart the address book? Closing and reopening the addressbook should be enough ...

**Comment by ralf1070** [comment] 2018-06-05 09:38
I'm able to confirm that all address books are shown multiple times (twice for me) on mac with TbSync version: 0.7.7.20.

OSX Version: 10.12.6
TB: 52.8.0 (64-Bit)

**Comment by jobisoft** [comment] 2018-06-05 12:37
I just releases beta .21 which has breakpoints. You can change the following global Thunderbird option:
```
extensions.tbsync.debug.breakpoint
```
If you change it from the default value (0), TbSync will simply abort its init sequence at the breakpoint you defined. I added breakpoints 1 to 12. TbSync will of course not work at all, if a breakpoint was set, but I hope that the addressbook problem will appear after one of those breakpoints. To learn WHICH breakpoint that is, would help me to understand this issue.

So if you find the time, it would help a lot, if you could cycle all 12 breakpoints. You need to restart TB after you changed the breakpoint value and check what the address book is doing.

**Comment by jobisoft** [comment] 2018-06-05 12:41
Breakpoints 10 to 12 are post init breakpoints, so TbSync will be usable, but not all features.

**Comment by Letterus** [comment] 2018-06-05 15:30
Ok, thank you. I activate each breakpoint one after another and restart:

Breakpoint:
1. No duplicate addressbooks.
2. No duplicate addressbooks.
3. No duplicate addressbooks.
4. No duplicate addressbooks.
5. No duplicate addressbooks.
6. No duplicate addressbooks.
7. No duplicate addressbooks.
8. No duplicate addressbooks.
9. No duplicate addressbooks.
10. Duplicate addressbooks appear.
11. Duplicate addressbooks appear.
12. Duplicate addressbooks appear.

Hope that helps. ;)

**Comment by jobisoft** [comment] 2018-06-05 15:33
Thanks! I will add more breakpoints between 9 and 10 and report here, when done.

**Comment by jobisoft** [comment] 2018-06-07 18:59
I just release beta .22 which has new breakpoints. I removed all breakpoints except nr. 9 and added new ones up to nr. 28.

So if you find the time, it would help a lot, if you could cycle the breakpoints from 9 to 28. You need to restart TB after you changed the breakpoint value and check what the address book is doing.

**Comment by Letterus** [comment] 2018-06-07 21:10
I‘ll try that as soon as I find some time, but it will be some work to check 19 checkpoints manually.

Do you see a way to test this automatically, i.e. switch breakpoints using a testsuite and count the number of items shown in the addressbook view?

**Comment by jobisoft** [comment] 2018-06-07 21:40
You could use the middle-of-intervall-technique. (german: Intervallschachtelung)

We want to know, where the switch from "No duplicate addressbooks" (good) to "Duplicate addressbooks appear" (bad) happens. We do not need to test all breakpoints.

The first intervall is the entire range: [9...28]
Breakpoint 9 should be good, but verify
Breakpoint 28 is probably bad, but verify

Test the middle of the intervall at breakpoint (9+28)/2 = 18
bad? the switch is between 9 and 18 -> new interval is [9...18]
good? the switch is between 18 and 28 -> new interval is [18...28]

Test the middle of the new intervall ...
... and so on ...

So it breaks down to 6 or 7 breakpoint tests. Could you follow?

**Comment by ralf1070** [comment] 2018-06-08 08:55
Just as a note: after a restart of thunderbird the duplicate address books are currently gone here. I did not activate any of these breakpoints.

**Comment by jobisoft** [comment] 2018-06-08 08:58
Are you sure? After installing beta .22 and restarting once, you do not have double entries? And they do not come back after more restarts? Puzzled...

**Comment by ralf1070** [comment] 2018-06-08 09:09
Restarted 5 times. No duplicates.

**Comment by Letterus** [comment] 2018-06-08 09:20
Interesting. For me they stay. Even when CategoryManager is disabled. But there seems to be an connection: My Mac OS X addressbook (which is shown in the addressbook of Thunderbird) has 24 categories. And each addressbook is shown 24 times.

It seems to me the view renderer displays an addressbook entry for each category entry - like, there is a loop that iterates using item number of the wrong object array or something.

**Comment by ralf1070** [comment] 2018-06-08 09:52
I cleaned up a no longer working carddav connection in OS X address book. This could be related ...

I tried to add/remove some groups, restarted TB ... but no - I currently don't get duplicates anymore.

**Comment by Letterus** [comment] 2018-06-08 10:27
1. Both Macs where this occurs use a CardDAV connection/account with the Mac OS addressbook.
2. I checked: For each category I add using the Mac OS addressbook I get one more duplicate in Thunderbird. And for each I remove one less. This even works with local categories of the Mac OS addressbook - I do not have to add categories using the CardDAV account.

**Comment by Letterus** [comment] 2018-06-10 14:57
View is fine, syncing works!

(I'm trying some other things using the addressbook now that seem to be difficult. I am going to send a mail to you.)

**Closed** 2018-06-10 18:47 UTC
