### ISSUE TITLE
gMail sync

### ISSUE THREAD

**Issue by StephenCheek** [jobisoft/TbSync#326] opened 2019-11-07 11:34 UTC
## Your environment

TbSync version:
Thunderbird version:

Can I use TbSync to connect to gMail contacts/calendars?

[ ] Yes, I have installed the latest available (beta) version from 
https://github.com/jobisoft/TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
...

## Actual behavior
...

## Steps to reproduce
...

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by jobisoft** [comment] 2019-11-07 11:37
Duplicate of https://github.com/jobisoft/DAV-4-TbSync/issues/56

**Closed by jobisoft** 2019-11-07 11:37 UTC

**Comment by jobisoft** [comment] 2019-11-19 21:38
**Tada:** The latest beta has google support! You now can now setup the sync of your google contacts and your google calendars from one single UI!

You can get the beta here: https://tbsync.jobisoft.de

Feedback is appreciated!

![grafik](https://user-images.githubusercontent.com/5830621/69188445-d80de300-0b1c-11ea-8723-811d0dd5b0b3.png)
