### ISSUE TITLE
PROBLEM WITH (AUTO) SYNC

### ISSUE THREAD

**Issue by kloughlin** [jobisoft/TbSync#14] opened 2017-08-31 14:18 UTC
Hi
Having installed TbSync in conjunction with Thunderbird, and succesfully connected to my Outlook.com account calendar, I have one issue:

**1.** the sync only seems to be one-way:-    When adding an event directly in MS Outlook calendar (web) or via Office Suite programme it appears in T'bird (even after forcing sync in TbSync).  When I add an event in T'bird and force the sync, it shows in T'bird BUT does not appear in any Outlook calendar.

Any thoughts on this issue - let me know if you require further info?

Otherwise really cool add-on and only one i can find that actually forms the link to calendar - so at least they show on T'bird (as one way link at present).  Thanks and hope you can duplicate issue with your operations and then may be able to resolve issues in future updates.

Regards,
Keith

**Comment by jobisoft** [comment] 2017-11-01 19:05
Reproduced. Working on it.

**Comment by jobisoft** [comment] 2017-11-02 10:23
Could you check TbSync log, if it stops with an "status code 6" error? Something lile:

[wbxml status] : Server reports status <6>. Error? Aborting Sync.

Could you verify, that it works with [0.6.8.1](https://github.com/jobisoft/TbSync/releases/download/v0.6.8/TbSync-0.6.8.1.xpi)?

**Comment by kloughlin** [comment] 2017-11-02 12:13
Hi
Thanks for reply.  Firstly tried auto-update to 0.6.8.1 but didn't work - had to force update!!??

No change to problem even after update:

Without adding a calendar entry in T'bird the logfile shows sync OK, as follows:
      ** Thu Nov 02 2017 11:44:34 GMT+0000 (GMT Standard Time) **
      [sending] : POST https://eas.outlook.com/Microsoft-Server-ActiveSync?Cmd=Sync&User=k****-l******@outlook.com&DeviceType=Thunderbird&DeviceId=mztb18da984c4b7d010f***********

After adding a calendar entry in T'bird the logfile does  show "Aborting sync", as follows:
    ** Thu Nov 02 2017 11:47:09 GMT+0000 (GMT Standard Time) **
    [wbxml status] : Server reports status <6>. Error? Aborting Sync.

    ** Thu Nov 02 2017 11:47:09 GMT+0000 (GMT Standard Time) **
    [finishSync(): Error @ Account KL Outlook] : ActiveSync error (Status 6).

Hope this helps?  Let me know if you require more info?

**Comment by jobisoft** [comment] 2017-11-02 12:40
Auto-Update does not work, because 0.6.8 is the latest official version in the Mozilla Add-On repository. The next release which I will send to Mozilla will be 0.6.8.2, but I want to fix your problem first.

Are you 100% sure, that you used 0.6.8.1? I assume 0.6.8.1 does not fix your problem, but I want to make sure, that I reproduced your specific problem, and not another one.

**Comment by kloughlin** [comment] 2017-11-02 12:45
Yes, sure of update - see attached jpeg screenshot of T'bird Add-on Manager tab

![tbsync](https://user-images.githubusercontent.com/31512042/32326650-851a2422-bfcb-11e7-922d-19cbed28a547.JPG)

**Comment by kloughlin** [comment] 2017-11-02 12:48
By the way you stated you had reproduced problem.  Is this using the new updated or 6.8.0 version??

Is your problem still there??

**Comment by jobisoft** [comment] 2017-11-02 13:02
I am pretty sure, I reproduced your problem now and it is not fixed yet. There was another related [issue](https://github.com/jobisoft/TbSync/issues/9) which was indeed fixed by 0.6.8.1.

**Comment by kloughlin** [comment] 2017-11-02 13:08
Do you want full copy of both log files (before and after adding a calendar entry), or any other info to help you?  Otherwise I will wait until you contact me again.  Thank you for your help and patience with this one.

**Comment by jobisoft** [comment] 2017-11-02 14:41
Could you test the current 0.6.8.2, where I added a possible fix?
https://github.com/jobisoft/TbSync/releases/download/v0.6.8/TbSync-0.6.8.2-pre.xpi

**Comment by kloughlin** [comment] 2017-11-02 14:59
Hooray!!  You've done it - well done and Thank You.

I updated to 0.6.8.2 and have placed (and deleted) test entries in all permutations i.e. via Outllook Web via T'bird and even using another email client on my mobile phone.  All seems to be working now and cross-syncing.

Is there any info I can provide (from logfiles) that will help you understand the fix.

In any case thank you so much once again, and it has been a pleasure to be a part of this great TbSync app progression.  This Comment issue can be closed from my viewpoint.

**Comment by jobisoft** [comment] 2017-11-02 15:54
Glad, that it is working for you now. If you like this Add-On, consider a donation :-)

https://www.paypal.me/johnbieling

I will push this version to mozilla now.

**Comment by kloughlin** [comment] 2017-11-02 16:55
Hi John,
Just sent a donation – have a beer on me!!  Thank you again.


SENT FROM ACER NOTEBOOK
Kind Regards,         [T'Egypt 022a]
Keith Loughlin

Tel: +44 (0) 7973 223074 (mob)
Tel: +44 (0) 1706 873842 (home)
Tel: +44 (0) 1706 508356 (VOIP PHONE)
Email: keith-loughlin@outlook.com
Skype: keithneileen
save paper - do you really need to print this email?

**Comment by jobisoft** [comment] 2017-11-02 17:50
Thank You!

**Closed by jobisoft** 2017-11-02 17:50 UTC
