### ISSUE TITLE
Google Address book contacts strange labels, phone numbers cannot be updated

### ISSUE THREAD

**Issue by LivingInternet** [jobisoft/TbSync#424] opened 2020-08-26 18:18 UTC
## Your environment

TbSync version: 2.16
Thunderbird version: 78.1.1

I have not installed the latest available beta version from 
https://tbsync.jobisoft.de
as my understanding is that I would not be able to downgrade to stable, and don't want to jeopardize my data.

## Expected behavior

1. Click on Thunderbird "Address Book".
2. In left pane click on "Google (Address Book)".
3. Add a new contact.
4. Click on the "+" sign next to the "Phone numbers" pane on the right and add a phone number.

## Actual behavior

On step 4, nothing happens when the "+" sign is clicked next to "Phone numbers".  There does not appear to be a way to add a phone number.  Please see first screenshot below.

Possibly related: for contacts previously created before I added TBSync, when I double click them and open them in the Thunderbird address book to edit them, the pane for phone numbers is not labelled "Phone numbers", but rather is labelled "__DAV4TBSYNCMSG_abCard.Phone__".  The "+" sign to add phone numbers does not work for these contacts as well.  Please see second screenshot below.  And no phone numbers are displayed in the pane.  Although the contact does have phone numbers, and they are displayed correctly in the preview pane on the bottom in the Thunderbird Address Book window.  Please see third screenshot below.

All the old and the new contact I just created look fine on my Android phone, and syncing appears to work fine as well.  

## Steps to reproduce

As above.

Since there is no error code, and I am just displaying windows, I have not attached a debug log.  Please let me know what actions I should take before sending one if you still want one.

![tb1](https://user-images.githubusercontent.com/70285448/91340830-a3634200-e7a6-11ea-9606-3d902d78427a.png)

![tb2](https://user-images.githubusercontent.com/70285448/91340857-abbb7d00-e7a6-11ea-82f9-246f19739f8d.PNG)

![tb3](https://user-images.githubusercontent.com/70285448/91340865-af4f0400-e7a6-11ea-9a06-6800e3fbacb9.png)

(I just donated to this project from the Donate button on this project's GitHub home page - you should too!)

**Comment by cheabit** [comment] 2020-09-01 09:06
Hi,

I do have the same issue.
I upgraded from Thunderbird 68.12.0 zu 78.2.1

Martin

**Comment by LivingInternet** [comment] 2020-09-02 16:51
I tried a workaround by creating a new contact in the Thunderbird Personal Address Book, filling in the phone number etc., and then dragging it to the Google Address Book.

In Thunderbird, it moved.  However, I tried syncing both TBSync and and my phone several times, and it was not synced to my phone.

When opened in the Google Address book, the contact is as described earlier: not editable, and with strange labels such as "DAV4TBSYNCMSG_abCard.Phone".

**Comment by HendrikF** [comment] 2020-09-05 11:50
Duplicate of https://github.com/jobisoft/TbSync/issues/424

**Comment by LivingInternet** [comment] 2020-09-14 13:50
I see that the apparent duplicate
https://github.com/jobisoft/DAV-4-TbSync/issues/225
has been closed with a fix.  Thanks much.

I assume that fixes this issue as well, even though it is still listed as open?

If so, I'm not sure how I can access this fix?  I'm running TbSync version: 2.16, and in Add-ons in Thunderbird when I checked for updates none were found.  Should I just keep checking, or do I need to uninstall and install a different version?

**Comment by jobisoft** [comment] 2020-09-14 14:17
That was an automatic close by github, just because I listed the issue in the commit. Fix needs a few more days before it lands on ATN.

**Comment by SchwarzerA** [comment] 2020-09-14 17:15
The same behaviour can be seen in TB 78.2.2 (64-bit)/TbSync 2.16/DAV-4-TbSync/1.16 on Linux with baikal: 
![Screenshot_2020-09-14_18-40-27 TbSync baikal](https://user-images.githubusercontent.com/48204981/93117043-7f689180-f6be-11ea-9eff-2e2135e5b0b7.png)

**Comment by jobisoft** [comment] 2020-09-16 10:53
should be fixed in latest beta:
https://github.com/jobisoft/TbSync/wiki/Get-the-latest-TbSync-version

**Comment by LivingInternet** [comment] 2020-09-17 12:48
Many thanks.  It's only a small exaggeration to say that my entire productive life is in my contacts and calendar.  So I'd like to be extra careful.  Is there some way to be automatically notified when this fix is pushed to stable?

**Comment by jobisoft** [comment] 2020-09-17 16:16
It is since yesterday. :-) You may need to disable and re-enable your tbsync account to start fresh.

**Comment by LivingInternet** [comment] 2020-09-17 18:23
Note sure I needed to do all this, but it is what worked for me: 

Disabled TbSync in Add-ons, closed Thunderbird, restarted Thunderbird, re-enabled TbSync, did a manual sync in "Tools > Synchronization Settings (TbSync)", closed Thunderbird, restarted.

All looking good now, thanks.

**Comment by SchwarzerA** [comment] 2020-09-18 07:43
Although it is not perfect…

Moving an address from my Microsoft account to my private baikal account makes the values of field "Last:" appear in field "Suffix:". Now I'm unsure which address is correctly stored and worth to be synced between my devices.

![Screenshot_2020-09-18_09-33-19 tbsync](https://user-images.githubusercontent.com/48204981/93570368-300eb380-f993-11ea-8b96-375177eda64b.png)

**Comment by HendrikF** [comment] 2020-09-20 11:04
This seems to have introduced a bug, that the suffix and last name fields are swapped.

I populated this contact in Nextcloud, and in Thunderbird it shows them swapped:
![Bildschirmfoto von 2020-09-20 11-47-47](https://user-images.githubusercontent.com/6961660/93709770-6853f480-fb41-11ea-98fe-22147f4c11a3.png)

**Comment by jobisoft** [comment] 2020-09-20 11:37
Yep, fix is pending review.

**Comment by exapplerep** [comment] 2020-09-28 17:24
> Note sure I needed to do all this, but it is what worked for me:
> 
> Disabled TbSync in Add-ons, closed Thunderbird, restarted Thunderbird, re-enabled TbSync, did a manual sync in "Tools > Synchronization Settings (TbSync)", closed Thunderbird, restarted.
> 
> All looking good now, thanks.

Did the same as you. The "add" and "modify" screens look okay now. However, the last update of TBSync still shows July 30 (as it has shown since then) and checking for updates shows none available. So where was the problem if nothing was actually changed?

**Comment by jobisoft** [comment] 2020-09-28 17:32
The bug was not in TbSync.

**Comment by exapplerep** [comment] 2020-09-28 17:40
> The bug was not in TbSync.

Ah! Was it the "Provider for CalDAV & CardDAV"?

**Comment by jobisoft** [comment] 2020-09-28 17:44
Sorry, yes. I thought that was obvious :-)

**Comment by exapplerep** [comment] 2020-09-28 17:47
> Sorry, yes. I thought that was obvious :-)

All I see is TBSync listed in this thread. The only time the word "provider" is shown is in my previous post. :D 

All is fine. Thanks for your assistance and your valuable contribution.

**Comment by jobisoft** [comment] 2020-09-28 18:21
There was this:
https://github.com/jobisoft/TbSync/issues/424#issuecomment-687598760

But yeah, should have been closed already.

**Closed by jobisoft** 2020-09-28 18:21 UTC
