### ISSUE TITLE
availibilities of invited persons when creating meeting are unseen

### ISSUE THREAD

**Issue by etremond** [jobisoft/TbSync#694] opened 2023-09-24 07:00 UTC
## Your environment

TbSync version:
Thunderbird version:

## Expected behavior
...

## Actual behavior
...

## Steps to reproduce
...

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by Lev-Shereshevsky** [comment] 2024-01-06 17:31
Duplicate of #696

**Closed** 2024-04-01 10:08 UTC
