### ISSUE TITLE
Addressbook sync generates duplicate entries in 0.7.10 (may be related to gContactSync)

### ISSUE THREAD

**Issue by mikko-ttlsystems** [jobisoft/TbSync#99] opened 2018-07-05 07:01 UTC
## Your environment

TbSync version: 0.7.10
Thunderbird version: 52.9.0/64 Linux, 52.8.0/32 Windows (multiple client systems)
Microsoft Office 365 -> Exchange Online

[X] Yes, I have installed the latest available (beta) version from 
https://github.com/jobisoft/TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

Actually ONLY seen with the latest version, didn't look at 0.7.9 closely though.

## Expected behavior
Addressbook is unchanged on server if no manual changes are made in Tb/TbSync

## Actual behavior
After upgrading to TbSync 0.7.10, addressbook entries are duplicated with no apparent reason, causing 
the number of entries to grow, apparently exponentially. Fortunately it's not all that fast.

## Steps to reproduce
Install TbSync 0.7.10, don't turn off addressbook sync or make it read-only. 

With 0.7.7, the addressbook wasn't actually very good, due to having lots of quote-delimited stuff that messed up the address lines. 
With 0.7.10 it at least looks usable and supports multiple addressbooks too, which would be a significant improvement... except for this.

**Comment by jobisoft** [comment] 2018-07-05 07:05
.10 backuped your addressbooks and you probably re-enabled your accounts, so you have all address books twice. If you select the "global" address book, you see all addresses twice. But if you select a single address book, do you still have that problem?

.10 introduced a new address book sync mechanism.

**Comment by jobisoft** [comment] 2018-07-05 07:35
I have to look at that whit my O365 account. I will report back.

**Comment by jobisoft** [comment] 2018-07-05 07:51
I am not able to reproduce this. I actually see the opposite: IF I duplicate a contact in TB and sync that to O365, it is not show in the web access. There is a  double entry suppression. If I remove the account in TB and set it up again, the duplicated entry comes back, so it is there, but not shown in the web access.

I was not able to cause unwanted duplication.

What are the exact steps to reproduce this?

**Comment by mikko-ttlsystems** [comment] 2018-07-05 08:18
Exact steps:
Turn on sync for address book
Watch number of entries grow...

I had 119 unique entries. Now I'm up to 238, as in each one exactly twice, and yes I'm seeing them in TB, just the single address book selected. Also does shown in web access and Outlook on the PC.

**Comment by jobisoft** [comment] 2018-07-05 08:22
So you do not have any local changes (the account has a green tick in the account manager) and you just hit sync and it syncs "new" entries from the server to TB and adds them to the TB addressbook? 

And you are not doing anything else? Outlook is closed while you da that?

And if you do that again, you get the same entries duplicated? I need to debug log of such a sync.

**Comment by mikko-ttlsystems** [comment] 2018-07-05 08:36
Exactly.
Well, Outlook is open. Not feasible to require it to be closed, wasn't a problem in 0.7.7 ...

And it doesn't happen on *every* sync run, duplicates a variable number of entries while it does.

Well, I turned off addressbook sync in TbSync and looked at the duplicate entries through DavMail with DuplicateContactsManager ( https://addons.mozilla.org/thunderbird/addon/2505 ), seems the differing fields there are modification date, card UID, groupDavKey (which contains the card UID), groupDavVersion, unprocessed:rev (again the last two probably have a 1:1 mapping between fields), RecordKey and DbRowID ... and, sometimes, PhotoType, PhotoName, Notes (which differs in amount of whitespace), and LowercaseSecondEmail (was cleared in at least one example). 

Haven't gone through all of them yet.

**Comment by jobisoft** [comment] 2018-07-05 08:41
please activate debug logging so next time you sync and get new duplicated entries, we can look at the log to see what is comming down.

From what you say so far, it is not TB duplicating items but it actually receives items marked as "new", which however are not new. The debug log will help to understand this further.

**Comment by mikko-ttlsystems** [comment] 2018-07-05 10:18
Ok, I have a log. There's about 5000 lines of logging (693 to 5808 out of 5814 lines total in the logfile) on the contacts folder, happening over 31 seconds, which resulted in duplicating every entry. What am I looking for here?

What I did was, I turned on logging, turned sync on for the contacts, hit sync, saw the number of entries go up in the progress indicator, and after sync was complete turned off logging. The other lines dealt with the calendar and tasks folders (which were already synced) apparently.
[tbsync-syncwithduplication_20180705_justcontacts.log](https://github.com/jobisoft/TbSync/files/2166121/tbsync-syncwithduplication_20180705_justcontacts.log)

**Comment by jobisoft** [comment] 2018-07-05 10:33
The server says "I have 119 elements to sync" (estimate L61) and then sends 119 elements with ADD command (L93, L1073, L2105).

THEN it goes crazy. TbSync reports local modifications and local additions and sends them to the server, but you said, there are no local modifications? 

Are you able to find your Thunderbird profile folder? I would like to do a hard reset.
1. Remove any account from TbSync Account manager
2. Close Thunderbird (important, all processes!)
3. Open your profile folder and look for a folder called TbSync - remove any json file
4. Start Thunderbird and set up your account fresh

**Comment by mikko-ttlsystems** [comment] 2018-07-05 10:47
Well, of course there were no local modifications - this was the initial sync run for the contacts folder... 

In my experience these usually have something to do with character set encoding, locale/language settings or the like. 

And of course I can find my Thunderbird profile folder (yep, still under ~/.thunderbird in Linux and %localappdata%\Thunderbird in Windows), problem is, I may not have much time right now for this. Let's see what I can manage...

**Comment by jobisoft** [comment] 2018-07-05 10:49
Take your time. I just assume for whatever reason the changelog is not empty. I currently see no reason why TbSync should send stuff to your server, if you have no local modifications.

By deleteing all json files, TbSync is resetted hard.

**Comment by mikko-ttlsystems** [comment] 2018-07-05 10:54
... problem is, since this happened with the upgrade to 0.7.10 for me... it might happen for someone else too. Wasn't a hard enough reset at that point if that'd help.

And it also pretty often happens if I turn off sync for a contacts folder and then back on, so... do a hard reset if you change which folders you sync?

**Comment by jobisoft** [comment] 2018-07-05 11:01
I used a procedural to do the reset (clear instead of delete), something might have gone wrong there, yes. That is why I ask you now to clear it "for good" by removing the files.

The folder unsubscribe/subscribe method (which is probably what you refer to as to turn sync on/off) is using the same procedural to clear the changelog of the folder, as the hard resest during update to .10.

Looking forward to hear from you after the hard reset. Maybe do not toggle the subscription state of the contacts folder for a while.

**Comment by mikko-ttlsystems** [comment] 2018-07-05 13:02
Actually I did an even harder reset - a whole new fresh Thunderbird profile. Took about half an hour for it to start getting anything from Office 365 and when it did, it again duplicated every contact.

Then I did the TbSync profile wipe with a "rm TbSync/*.json", then again waited for Office 365 to start giving any data. ... right, now it's getting some, and we're up to 4 copies of each entry.

But really, how does this thing check for local changes anyway? Because after the profile wipe it had no changelog.json at all, until about the time it did start giving data (several sync runs in between that came up with no content), and then it wrote lots of stuff to changelog.json during the sync job already... and pushed the duplicates back on the server right away.

**Comment by jobisoft** [comment] 2018-07-05 13:18
Thanks for your time. I fear this will take a while. The worst thing is, I cannot reproduce it and I have not even an idea of what is going on.

Is there any other addon installed, which might modify new contacts? Could you remove all other addons?

You did remove the duplicate entries from the server, right? Just double checking ...

**Comment by jobisoft** [comment] 2018-07-05 13:29
Take your time.

After you made the next profile wipe via rm *.json (while TB is not running!) install the attached version to set up your account and sync. This version is unable to push anything to the server, the function has been removed.

Monitor the changelog file and send it to me if something shows up after syncing without you doing anything to the contacts.

[TbSync-beta.zip](https://github.com/jobisoft/TbSync/files/2166739/TbSync-beta.zip)

**Comment by jobisoft** [comment] 2018-07-05 15:24
To make our life easier, I would like to verify the current situation.

1. Leave your profile as it is, with all your addons enabled
2. Install the special version of tbsync
3. Disable all your accounts in the TbSync Account Manager
4. Make sure, that the changelog file gets cleared by that (no need to close TB, but it takes up to 10s before the changed changelog data is written to file, except on TB close, than it is written immediately)
5. Re-Enable your account and sync, wait 10s and than check changelog, it should now contain a bunch of entries of type "added_by_user". (If not, sync a few times to make sure it does not happen later. Do other types show up?)

This should be the current situation.

**Comment by mikko-ttlsystems** [comment] 2018-07-06 12:47
Well, right, there's a whole lot of those "added_by_user" entries, one for each preexisting line in the addressbook.  And then there's just as many "modified_by_user" entries. 

Specifically, there's a '{"parentId":"moz-abmdbdirectory://abook-1.mab","itemId":"<number =< $number_of_entries>","status":"added_by_user"},{"parentId":"moz-abmdbdirectory://abook-1.mab","itemId":"<string that looks sort of like base64 but decodes to garbage>","status":"modified_by_user"},' for each one. 

[changelog.zip](https://github.com/jobisoft/TbSync/files/2170532/changelog.zip)


BTW, still got a dupe when running with the special version. Just one though, the latest entry to be added and one that had been added after the testing-profile TB was last run. If you're sure your code doesn't add that, I'd suspect something weird happening in Exchange Online again. (That's unfortunately a bit too common...)

**Comment by jobisoft** [comment] 2018-07-06 12:51
Yes, you still get the duplication in Thunderbird, but it is not send to the server, it should not show up there. It just cannot. I will go crazy if they do show up at the server!

**Comment by mikko-ttlsystems** [comment] 2018-07-06 12:58
I suppose it's not impossible that the server contributes to the dupes forming somehow. MS Exchange and Outlook have both been caught modifying server-side data during what was supposed to be a pure client read operation before... fortunately the worst examples have been fixed but still.

**Comment by jobisoft** [comment] 2018-07-06 13:00
So you are telling me, that the special version of TbSync (https://github.com/jobisoft/TbSync/issues/99#issuecomment-403023996) is indeed modifying your server data?

**Comment by mikko-ttlsystems** [comment] 2018-07-06 13:01
Well, *something* did at exactly the moment I ran it.

**Comment by jobisoft** [comment] 2018-07-06 13:13
This cannot be, I do not care about what happens in your local Thunderbird, but TbSync is not sending anything back to your server, that function is removed! Check the log!

Are you 100% sure that you installed the above version (it should identify itself as 0.7.10.1) and if you sync with THIS version new entries show up in the webinterface of O365? Please close outlook, just to make sure.

**Comment by jobisoft** [comment] 2018-07-06 13:29
I am loosing it ... this is driving me crazy ... any news?

**Comment by mikko-ttlsystems** [comment] 2018-07-06 23:45
Oh well, tried this on a different PC and now I'm not even getting the
spurious changelog.json entries at all.

Though, I did get an extra "change" notification on CardDAV through
DavMail for no known change during the testing.

This was a fresh TB profile; Xubuntu 16.04.4 like the one where I did
most of the testing before... hm.

Clearly there's something funny going on but I guess now I'd need to
start eliminating differences... or I could try to see if this still
happens on one of the PCs where it did earlier - if it was a server-side
problem I'd hope it'd have been fixed.

**Comment by jobisoft** [comment] 2018-07-07 06:35
If it still happens on the other pc, where you tested before, you could try to disable all other addons to see if it has an effect. You only need to restart once, not after every single disable.

**Comment by jobisoft** [comment] 2018-07-16 18:52
Any news on this, could you eliminating differences between your two systems? 
Could you identify, if another addon is causing this?

I just got notified, that another user has this issue. Hm...

**Comment by jobisoft** [comment] 2018-07-24 20:18
If this shows up in a fresh Thunderbird Profile with just TbSync installed and no other AddOns at all, and just that one account setup in TbSync, I have no further idea, where this might come from. 

When I download contacts from the server and add them to the address book, something is modifying them (or remove + re-add) almost instantly, so for the TbSync changelog that looks like modifications or additions, which he sends back to the server.

**Comment by mikko-ttlsystems** [comment] 2018-07-25 07:03
Well, the problem isn't constrained to a single build rev of Thunderbird, since there was an update and it didn't seem to change things at all. Besides, well... I suppose I could run a separate check on the binaries but I'd think the Ubuntu repositories could be trusted with this...

Good:
ii  thunderbird               1:52.9.1+build3-0ubuntu0.16.04.1 amd64
ii  thunderbird-locale-en     1:52.9.1+build3-0ubuntu0.16.04.1 amd64
ii  thunderbird-locale-en-us  1:52.9.1+build3-0ubuntu0.16.04.1 all
ii  thunderbird-locale-fi     1:52.9.1+build3-0ubuntu0.16.04.1 amd64

Bad:
ii  thunderbird               1:52.9.1+build3-0ubuntu0.16.04.1 amd64
ii  thunderbird-locale-en     1:52.9.1+build3-0ubuntu0.16.04.1 amd64
ii  thunderbird-locale-en-us  1:52.9.1+build3-0ubuntu0.16.04.1 all
ii  thunderbird-locale-fi     1:52.9.1+build3-0ubuntu0.16.04.1 amd64

Bad:
Thunderbird 52.9.1 x86 fi on Windows 10 Pro 64 build 1709

**Comment by mikko-ttlsystems** [comment] 2018-07-25 09:45
Oh well. Seems that now I'm not getting duplicates. Still with the special TbSync 07.10.1 beta, same procedure as previously (another new profile). 

Since my end of this thing hasn't changed from when I still did get duplicates, I'd say it looks like it was something on the server then. Or maybe this is just being an intermittent problem still.

It's a real bother that MS doesn't publish detailed changelogs from what they do to Office 365, sometimes - there have been changes again this week already...

**Comment by mikko-ttlsystems** [comment] 2018-07-25 20:08
Well, sorry, not quite... and the behaviour has changed during this time too.

First, all three computers have "old" profiles of the same approximate age, all upgraded from TbSync 7.7 at the very least. One of these has never exhibited this problem (so far).

Only one of these currently has the special version, and that's the Linux box with the duplicating problem. Which didn't occur this last test run at all - not locally even. So, the problem does not occur every time, frequency seems to vary greatly between days... which is a bit of a bother as I can't devote all my time to this one problem. (Fortunately our end users haven't run into this one yet.)

So, I tried again with one of those old profiles with a standard version TbSync, where the TbSync account was wiped before my vacation but everything else was kept (mailboxes, other extensions and the like). It then generated duplicates again, but this time differently than before my vacation. This time the duplicates were the only entries shown in TbSync's address book, so TbSync on that profile showed the correct number of entries but everything else showed double (including the special version TbSync). Upon removing these duplicates through other means, the affected instance of TbSync then showed no entries at all.

(It's helpful to be able to run multiple independent concurrent instances of Thunderbird with different profiles, easy to do in Linux at least...)

Now, it's quite possible that this is a server side problem - Office 365 / Exchange Online seems to be moving towards keeping separate proxy copies of data for each ActiveSync client accessing it, thus the provisioning delay - and occasional sync delays between clients too. (Hence the funny known-problem with read-only calendars over ActiveSync where you can still make changes, they just never propagate past your proxy copy of the calendar.)

So the server would be making the proxy copy at provisioning / first sync time and... somehow it'd leak back to the main data set as separate entries? That's my theory so far.

Since this apparently hasn't happened to droves of mobile phone ActiveSync users, I'd expect it to be something specific to TbSync that triggers the incorrect behaviour.

**Comment by jobisoft** [comment] 2018-07-25 21:36
Thanks for your time on this.

If we take old Thunderbird profiles aside (also not running in the background) and only look at new Thunderbird profiles created* after the release of 0.7.10 (or after today) without any addons but just a regular TbSync (stable 0.7.10 or the latest beta 0.7.10.16): Do you get duplicates on any of your systems?

* a clean/empty profile created with the Thunderbird Profile Manager, not copied fro somewhere else

**Comment by jobisoft** [comment] 2018-08-02 19:59
I released a new beta, which adds some checks to identify problems in the TbSync settings and aborts sync in such a case with an error. It would be interesting to know, if that error message shows up (only) on your bad profiles.

https://github.com/jobisoft/TbSync/releases/download/v0.7.10/TbSync-beta.xpi

**Comment by ilvipero** [comment] 2018-08-05 14:44
Hi, I had the same issue, found 20,000 duplicate items and tbsync going forever. Version 0.7.10

What I did to resolve the issue:
1. Disabled the account
2. Deleted the account
3. Cleaned up all the mess from Outlook Web Access
4. Deleted the sync folders (contacts and calendars) in Thunderbird
5. Created a new account in TBsync.

So far it looks ok, TBsync is idle, all calendar events and contacts seem under control. I will keep an eye on this and report back if I notice any issue.

**Comment by matt6575** [comment] 2018-08-09 19:47
TbSync: 0.7.10.18
I just started using this addon but I started noticing duplicates. I wasn't seeing as many as others here but I was getting 2 of each contact. Here's what seems to happen:

- The only contacts to get duplicated were ones that were created server side on outlook.live.com.
- Then as soon as TbSync was run a duplicate would be created. 
- The duplicate only appears on the server side. In TB only one contact shows.
- Subsequent TbSync runs seems to ignore the duplicate on the server because the duplicate never shows in TB.
- Creating a contact in TB then running TbSync creates a single contact server side and no duplicates ever appear for that contact.

I was able to determine that there seems to be a conflict with gContactSync addon. If I disable this then TbSync works correctly and no duplicates are created. Re-enable gContactsSync and the problem returns. gContactSync appears to do it's sync job correctly though whether TbSync is enabled or not.

**Comment by jobisoft** [comment] 2018-08-09 19:55
Thanks for the feedback. Which version of gContactSync are you using (which version is causing this error)?

**Comment by jobisoft** [comment] 2018-08-09 20:56
```
  onItemAdded: function AbListener_onItemAdded(aParentDir, aItem) {
    aParentDir.QueryInterface(Components.interfaces.nsIAbDirectory);

    if (aItem instanceof Components.interfaces.nsIAbCard &&
        !gContactSync.Preferences.mSyncPrefs.synchronizing.value) {

      // if a contact was added to an AB clear the GoogleID in case it was copied/moved
      if (!aParentDir.isMailList) {
        var ab = new gContactSync.GAddressBook(aParentDir);
        var contact = new gContactSync.TBContact(aItem, ab);
        contact.setValue("GoogleID", null);
        contact.update();
      }
    }
  },
```

It looks like gContactSync is modifiying ANY added card in EVERY addressbook and removes a GoogleID, this messes up tbSync changelog managment. Lets see how this can be fixed ...

**Comment by matt6575** [comment] 2018-08-09 23:13
Just tried it and yes it seems to fix the problem, no more duplicates!

I haven't tested gContactSync functionality yet to make sure everything in it still works but will report back if I find any problems on its side.

Thank you very much for your work. Do you take donations?

**Comment by jobisoft** [comment] 2018-08-10 05:16
Yes, donations are appreciated :-)
https://www.paypal.me/johnbieling

This however is just a quick fix. I still need to understand how I can fix TbSync itself to become independent of other AddOns messing with my change log.

I will report back here.



Am 10.08.18 um 01:13 schrieb matt6575

**Comment by jobisoft** [comment] 2018-08-10 21:42
After analyzing what gContactSync is doing to my changelog, I *may* have found (and fixed) a race condition inside TbSync. If this fix works, than other AddOns can no longer mess up my changelog...

@matt6575 : If you have the time, could you test the fix, before I release it?
1. Revert back to the official gContactSync 3.0
2. Install the attached pre release of TbSync 0.7.10.19

[TbSync-beta.xpi.zip](https://github.com/jobisoft/TbSync/files/2279544/TbSync-beta.xpi.zip)

Is it fixed?

**Comment by matt6575** [comment] 2018-08-11 01:02
I'll give it a try shortly and let you know.

**Comment by jobisoft** [comment] 2018-08-11 06:38
Thanks for your feedback and time! I just release 0.7.10.19 for the public. 

Would be interesting to know, if this also fixes the issue reported by @mikko-ttlsystems

**Closed** 2018-08-13 16:10 UTC
