### ISSUE TITLE
Unable to configure TBsync in TB 78.6.1!

### ISSUE THREAD

**Issue by aaeneas** [jobisoft/TbSync#488] opened 2021-01-24 21:59 UTC
## Your environment

TbSync version: 2.20
Thunderbird version: 78.6.1

[ ] Yes, I have installed the latest available beta version from 
https://tbsync.jobisoft.de
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
To be able to configure TBsync 

## Actual behavior
Cannot find a way to configure TBsync as was done using sub-menu of Menu Item "Add-on" in TB 68.

## Steps to reproduce
This problem arose when I upgraded TB from Version 68.12.1 to Version 78.6.1.  The upgrade seemed to work pretty well.  It figured out I was running TBsync and related add-ons.  This included recognizing that new versions of those add-ons were available and it looks like they were installed.  However, on TB78 there is no sub-menu on the Menu item for add-ons which is what I was able to select to invoke the dialogues used for configuring said add-ons.

I have found [this page](https://support.mozilla.org/en-US/kb/thunderbird-add-ons-frequently-asked-questions#w_how-do-i-configure-add-ons) which seems to describe how TB78 should work but when I select the 3-Dot iCon there is no selection entry presented called "Options".  Only entries called "Remove" and "Manage".  "Manage" only displays the information page for the the add-on.

Therefore, at present I'm unable to either inspect or adjust the configuration options on TB78. 

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by jobisoft** [comment] 2021-01-24 22:40
Read that paragraph you linked again. Specifically its last sentence. We are working on a solution to get options of older add-ons into the 3 dot menu as well. Until then, you have to use the tools menu.

**Comment by GaryT-NZ** [comment] 2021-01-25 00:25
I also have this issue, and have been confused by the conflict between outdated help, and the fact that I had turned off menus, as they are typically a waste of space. Apparently not here. 
If you are similarly confused by the lack of 'tools', you need to right click in the tab header, and turn on 'menu bar'.

**Comment by aaeneas** [comment] 2021-01-25 03:48
I'm a little old fashion and therefore I keep the menu bar on.  The referenced paragraph mentions the "Tools>Add-on Options" selection.  On my installation there is only "Tools>Add-ons".  When I select that I get the same window (with the 3-Dot icon) displayed as when I use the menu icon and select Add-ons.  Still no way to configure.

**Comment by GaryT-NZ** [comment] 2021-01-26 09:33
Not sure if it's relevant in your case, but I noticed during changing my settings that if tbsync was disabled (in the three dot menu), the options menu option disappeared.

**Comment by jobisoft** [comment] 2021-03-18 19:46
Duplicate of #462

**Closed** 2021-03-18 19:47 UTC
