### ISSUE TITLE
TBSync not compatible with TB115

### ISSUE THREAD

**Issue by PotatoCarl** [jobisoft/TbSync#682] opened 2023-08-01 11:26 UTC
## Your environment

TbSync version: current
Thunderbird version: 115

## Expected behavior
Working

## Actual behavior
Not Working

## Steps to reproduce
always

Looking how to support getting a working version for TB115+
Thanks

**Comment by scollovati** [comment] 2023-08-01 12:17
Duplicate of https://github.com/jobisoft/TbSync/issues/669

**Comment by PurpleZ2023** [comment] 2023-08-02 10:24
[TbSync115.1.zip](https://github.com/jobisoft/TbSync/files/12239040/TbSync115.1.zip)

**Comment by PotatoCarl** [comment] 2023-08-02 11:17
I installed the one from #669 which works. But the one posted above is not working (incompatible)

**Comment by PurpleZ2023** [comment] 2023-08-02 11:18
ok strange, in my TB it works ....

**Comment by jobisoft** [comment] 2023-08-18 11:48
Compatible versions have been submitted to ATN for review. ETA: a few days.

**Closed by jobisoft** 2023-08-18 11:48 UTC
