### ISSUE TITLE
Kerio Connect not working

### ISSUE THREAD

**Issue by franklupo** [jobisoft/TbSync#65] opened 2018-04-13 11:34 UTC
Hi,
Excellent work.
With Zimbra and Z-Push ok it's perfect.
Kerio Connect with ActiveSync protocol but it does not work and gives me error 400. What can it be?

best regards

**Comment by jobisoft** [comment] 2018-04-13 18:30
Hard to tell without details. Will try to get a test account.

**Comment by franklupo** [comment] 2018-04-14 06:12
For demo
https://demo.kerio.com/en/

https://demo.kerio.cloud/webmail/login/
user: admin-en
password: kerio

best regards

**Comment by jobisoft** [comment] 2018-04-14 07:33
I need a real account to connect TbSync. The first link is creating a temp account, but does not give me the password. I asked them if they can provide a real test account.

**Comment by franklupo** [comment] 2018-04-15 11:52
This work

https://demo.kerio.cloud/webmail/login/
user: admin-en
password: kerio

**Comment by jobisoft** [comment] 2018-04-15 12:13
What is the eas server I have to connect to?

**Comment by franklupo** [comment] 2018-04-15 13:12
https://demo.kerio.cloud/Microsoft-Server-ActiveSync

**Comment by jobisoft** [comment] 2018-04-15 20:14
Hm, that is strange. First of all: I could reproduce the issue.

I could get task and event sync working by manually activating provision. Contact sync fails for some other reason, which I will look at later.

The main question is now: Why is kerio not sending a HTTP 449 or EAS status codes 141, 142, 143 or 144 to indicate, that it needs provision enabled?  https://msdn.microsoft.com/en-us/library/ee218647(v=exchg.80).aspx

Do you have any insights on this?

I do not want to make the provision option changeable by the user, because it should be negotiated between client and server, I also do not want to have it enabled per default.

**Comment by jobisoft** [comment] 2018-04-15 20:30
I know, because outlook has provision enabled by default. If I force TbSync to enable provision by default as well, it will also work. But for different reasons I do not want that. The server should tell TbSync to activate provision, if needed. He can do that via HTTP 449 or some EAS status codes.

I will try to find a solution for this.

**Comment by franklupo** [comment] 2018-04-15 20:39
Also Android/IPhone activesync work perfectly.

**Comment by franklupo** [comment] 2018-04-16 16:52
News?
Best regards

**Comment by jobisoft** [comment] 2018-04-16 17:54
The situation is as follows:
- most of the other clients have provision activated by default, that is why they work with kerio
- tbsync currently does not activate provision by default but waits for the server to ask for activation
- kerio fails to send a propper provision request, but sends a HTTP 400 (instead of 449)
- many other server fail to send a provision deactivation request, if provision is not needed, which creates a lot of data overhead, which I do not want and why i do not want to activate provision by default

I am currently contemplating, how to fix this:
- get kerio to fix the wrong error code
- somehow detect kerio and activate provision on HTTP 400
- add an option to tbsync UI
- I will probably release some sort of fix by the end of april

Nevertheless, there is another error with contact sync. I can only fix this in the 0.8 branch, where I rewrite the contact sync code (current contact sync code is taken from tzpush and a black box to me). I cannot give you a timeframe here.

**Comment by franklupo** [comment] 2018-04-19 17:37
Wow,  calendar and task work but contact errors.
Sync failed. Server responded with status <j>.

**Comment by jobisoft** [comment] 2018-04-19 17:58
As I said, contact sync will be fixed in v0.8.

**Comment by franklupo** [comment] 2018-05-17 10:09
Any new?

Best regards

**Comment by jobisoft** [comment] 2018-05-17 22:09
Are you willing to spend time on beta testing? You can activate the current state of the new sync code and test it:

https://github.com/jobisoft/TbSync/wiki/Advanced-configurations#extensionstbsynceasuse_tzpush_contactsync_code

If something is unclear, just ask. You must install the latest beta to use this.

**Comment by franklupo** [comment] 2018-05-18 06:12
Ok thanks

**Comment by jobisoft** [comment] 2018-05-18 10:00
I am closing this issue, because it is very similar to issue https://github.com/jobisoft/TbSync/issues/76

If you post something there, you will be notified about updates as well.

**Closed by jobisoft** 2018-05-18 10:00 UTC

**Comment by jobisoft** [comment] 2018-05-20 13:03
I just released a final beta, containing the new sync method. Its stable now. Also I created a dedicated wiki page for this:

https://github.com/jobisoft/TbSync/wiki/Rewrite-of-tzpush-contact-sync-code

I consider this done. The new sync method will be promoted to default with the release of v0.8. Until than, it needs to be activated manually.

For Kerio, please also note this:
https://github.com/jobisoft/TbSync/wiki/Troubleshooting
