### ISSUE TITLE
TbSync for Thunderbird 102

### ISSUE THREAD

**Issue by gerd-git** [jobisoft/TbSync#591] opened 2022-06-29 06:17 UTC
## Your environment
Window 10
TbSync version:
3.0.2
Thunderbird version:
102

**EDIT: Previews of updated versions for Thunderbird 102 can be found here:**
* TbSync/DAV: https://github.com/jobisoft/DAV-4-TbSync/issues/283
* TbSync/EAS: https://github.com/jobisoft/EAS-4-TbSync/issues/167

To avoid dataloss, I will release TbSync for Thunderbird 102 only after https://bugzilla.mozilla.org/show_bug.cgi?id=1792399 has been backported to Thunderbird 102.

**Comment by fightuntilwedie** [comment] 2022-06-29 07:24
Same here!

**Comment by jobisoft** [comment] 2022-06-29 07:31
I am working on an upgrade, ETA 2 weeks.

**Comment by gerdlimbeck** [comment] 2022-06-29 07:31
Way back to TB91:

deinstall TB102
install TB91
copy profil
start tb91 with "thunderbird --allow-downgrade"
wait a few minutes
smile

**Comment by derritter88** [comment] 2022-06-29 15:07
Duplicate/linked to #590

**Comment by KrisSchneider** [comment] 2022-06-30 04:57
Same here aswell

**Comment by jobisoft** [comment] 2022-07-01 13:44
![image](https://user-images.githubusercontent.com/5830621/176906799-360e5642-c351-4049-ba85-6d650a32090d.png)

**Comment by peci1** [comment] 2022-07-01 23:17
Different from Google4TbSync, the integrated method does not sync contact groups.

**Comment by abysso2** [comment] 2022-07-03 18:08
Does the native one also handle icloud contacts?

**Comment by jobisoft** [comment] 2022-07-03 18:10
Don't know, try it.

**Comment by kwlorenz** [comment] 2022-07-10 09:50
Yes, the native sync handles iCloud too, but not contact groups or contact photos; you have to use a application-specific password for the sync

**Comment by kiravi** [comment] 2022-07-10 16:42
Just an FYI: 
It is now officially 102.0.1 that Is released. With a new TBSync release the following may also need an update:
1. Provider for CalDAV & CardDAV
2. Provider for Exchange ActiveSync
3. Any other embedded providers for google/icloud/yahoo/aol etc.

**Comment by abysso2** [comment] 2022-07-11 10:12
> Yes, the native sync handles iCloud too, but not contact groups or contact photos; you have to use a application-specific password for the sync

Okay, a bit OT here, but: can you tell me the address of the iCloud CardDAV URL. I am not able to login with my app pw ...

**Comment by smmehta1822** [comment] 2022-07-11 15:23
any update on tbsync fix for version 102 ?

**Comment by abysso2** [comment] 2022-07-13 11:40
Did not succeed:

Tried myname@icloud.com as user, https://p58-caldav.icloud.com as account and then once more myname@icloud.com as user and an newly generted apppw. 

Mhhhh ...

**Comment by wol-win** [comment] 2022-07-17 07:47
Hello - quick question: any idea when Tbsync for TB 102 would be available? I am desperately awaiting it for syncing back with an Exchange Server. Thanks.

**Comment by jobisoft** [comment] 2022-07-17 08:05
I will still need a couple of days.

**Comment by dbonner** [comment] 2022-07-17 12:00
Thanks for the update. Just curious ... Do you know roughly when you expect to release the Provider for Exchange ActiveSync for TB 102?

**Comment by KrisSchneider** [comment] 2022-07-17 20:33
> I will still need a couple of days.

Good to hear. Thank you for your hard work.

**Comment by smmehta1822** [comment] 2022-07-21 13:54
> I will still need a couple of days.

Hello John, Sorry to bother you. Any update on the fix? TB version 102.3 is out.

**Comment by crti** [comment] 2022-07-25 10:12
> Thunderbird 102 has builtin support for remote calendars (ex: google) and address books (CardDav).
> For google/gmail just enter [xy@gmail.com](mailto:xy@gmail.com) as username when adding calendar (on network) or CardDav addressbook

> to sync my Nextcloud calendars. I was easily able to add them using the native sync. Just added the base URL of my installation and entered my username and password, et voila

So far I stayed on TB 91.11.0 to continue to sync Nextcloud multiple calendars and contacts together with Android smartphones. Do I understand it correctly TB 102 natively supports sync of CalDAV calendars? So in the future only a CardDAV add-on to sync to the Nextcloud address is needed? Maybe TB also plans to add CardDAV support?

**Comment by Uwe-MrT** [comment] 2022-07-26 21:11
I use cardbook for google contacts.
It works fine with categorys like friends, business, etc
maybe this is an alternative for the Moment to manage your adressbooks

**Comment by Uwe-MrT** [comment] 2022-07-26 21:22
> ct gro

Take a look at Cardbook

**Comment by jobisoft** [comment] 2022-07-27 08:27
Thunderbird has native carddav support in 102. Dav4Tbsync will only do its custom discovery, but will hand over syncing to Thunderbird.

I might do migration, but I am not 100% sure yet. You can remove tbsync and it's addressbooks and set them up anew in Thunderbird's new addressbook.

**Comment by crti** [comment] 2022-07-27 09:18
Regarding **Cardbook** I tried it longer ago (when Stationary was still working) and it was a nice Add-On. I had some problem, do not remember exactly what (maybe Categories sync). 

Generally I would like to avoid any Add-On for essential functions (Address-books and Calendars are that to me) if they work natively. 

@jobisoft First thanks for your support to give TB essential functions. I installed TB 102.0.3 x64 Portable and beside IMAP was able to setup Nextcloud CalDAV Calendars and as well Nextcloud CardDAV Address-books. I need to get accustomed to the new Address-book GUI but almost everything seems to work - the only thing I need and still not native seems to be Category editing/listing, so it seems Category Manager Add-On is still needed but v5.1 also not yet compatible with TB 102 :-/ 
BTW: Selecting existing mbox dirs used in TB with LocalFolders Add-On seems to now work (subdirs do not show up, maybe limited to instance creating the initial mbox files)

**Comment by jobisoft** [comment] 2022-07-27 09:35
I am currently torn how much work I should put into the category manager. The entire UI is gone which will need a massive rewrite if I want to provide the same features as before. The cardbook add-on does have category support so I might suggest to try that.

I am part of the development team for TB 114 and i see what is in the pipeline. They will be a global search bar which will be accessible to add-ons, so my idea is to use that to filter for categories.

I will also lobby for native category support in the new UI.

**Comment by stheine** [comment] 2022-07-27 09:43
> I am currently torn how much work I should put into the category manager.

I never used it. my main use case of TBSync is getting the Exchange/Outlook calendar entries synced into Thunderbird.

**Comment by crti** [comment] 2022-07-27 09:58
@jobisoft Ok thank you very much for these very valuable insights - I will try Cardbook Add-On in TB 102 Portable

The disruptions on Add-Ons caused by changes in the TB core do not cease to concern devs and as well users. 
I hope the other TB 114 devs recognize the utility of CardDAV category support as for example the Nextcloud browser GUI provides natively. 
Flexibility for Import/Export/Backup (data and settings/setup) locally (or also by WebDAV) IMHO are also major concerns but this focuses on mbox folders and we are getting OT.

**Comment by DavidBE-UK** [comment] 2022-07-27 12:00
So is native TB support for syncing with outlook.com calendars and People/addressbooks on the horizon? The extended loss of this on major version TB releases (and using betas) isn't a good look for TB.

**Comment by smmehta1822** [comment] 2022-07-27 12:52
> > I am currently torn how much work I should put into the category manager.
> 
> I never used it. my main use case of TBSync is getting the Exchange/Outlook calendar entries synced into Thunderbird.

I am also looking for the same - TBSync getting the Exchange/Outlook calendar entries synced into Thunderbird 102+.

**Comment by dbonner** [comment] 2022-07-29 03:32
> > > I am currently torn how much work I should put into the category manager.
> > 
> > I never used it. my main use case of TBSync is getting the Exchange/Outlook calendar entries synced into Thunderbird.
> 
> I am also looking for the same - TBSync getting the Exchange/Outlook calendar entries synced into Thunderbird 102+.

+1 for me. I also only use Tbsync for synching Thunderbird with Exchange/Outlook calendar enties. It's a fantastic addon (or set of 2 addons: TbSync + Exchange Provider addon).

**Comment by aries223** [comment] 2022-08-01 17:40
Is it possible now to sync TB with Apple's iCal and Addessbook?
I was using TBSync & Provider and it worked perfectly.. but now it doesnt look like the new native sync can discover the iCal calendars. Any help would be appreciated..

**Comment by aries223** [comment] 2022-08-02 17:36
@Eternal9100 - Yes seems you can.. Problem is that TB does not discover Apple's iCal and Addessbook. You have to find out the exact and complete URL to the cal/addresbook to be able to add it. Next to impossible to do for the avg person (and even tech savy people without doing some digging).

The TBSync & Provider combo auto discovered them and made adding them to TB super straight foward.

**Comment by aries223** [comment] 2022-08-02 18:07
@Eternal9100  - Got the calendar added, thanks for the link. Do you have a link like that for the AddressBook URL? I cant find it anywhere...

**Comment by aries223** [comment] 2022-08-02 18:37
@Eternal9100 - Ok that worked.. Thanks for that! 
There is an error in that explanation though, the author forgot to add the ".com" in the url, ex:

https://pXX-contacts.icloud/XXXXXXXXX/carddavhome/card/
should be:
https://pXX-contacts.icloud.com/XXXXXXXXX/carddavhome/card/

**Comment by smmehta1822** [comment] 2022-08-04 02:13
Is there any update on Exchange calendar sync? I hate to bother @jobisoft

**Comment by tdido** [comment] 2022-08-04 09:17
A gentle suggestions, friends: donate and/or contribute code, and wait. There's no point in asking for a timeline, let the man work.

**Comment by dbonner** [comment] 2022-08-09 13:37
Hi, Yes let's donate!

**Comment by tjyrinki** [comment] 2022-08-10 06:28
Could there be a working branch somewhere so it'd be easier to contribute and test/debug? Of course donations are very good and something everyone can participate to, but in the long run there could be a better (even if always a bit small) chance of having multiple developers for the extension if development happened in public branches.

Regardless, big thank you for the work on the extension and the providers!

**Comment by T-6** [comment] 2022-08-10 15:44
Quite a surprise. I am on OpenSUSE Tumbleweed and received an upgrade to TB 102.1.0.
As expected the TbSync Add-on is disabled, BUT the calendar syncing with Nextcloud is still working.

**Comment by T-6** [comment] 2022-08-10 16:00
I was just surprised that it "just worked" without me setting up the CalDAV.
For the address book however, I had to set it up using the CardCAV functionality of TB102

**Comment by jobisoft** [comment] 2022-08-10 16:04
Sorry that you have to wait so long. It is a bit chaotic here and I do not find the time I need to get it done. I am putting any free time I have into this.

**Comment by hfm158** [comment] 2022-08-11 09:25
> Sorry that you have to wait so long. It is a bit chaotic here and I do not find the time I need to get it done. I am putting any free time I have into this.

Thank you for your hard work. Take your time, the old TB still works fine.

My more general concern about TB and its add-ons: Why must TB change its APIs and functions for major releases? This requires a lot of re-write for add-on developers, and a lot of work for users when they upgrade, or they are forced to stay on older versions of TB. In any case, acceptance is being reduced.
Why can TB not provide more stable interfaces for add-on development?
The number of add-ons will also be reduced since many developers don't have the time and money to continue adapting and updating their add-ons for new TB versions.

**Comment by jobisoft** [comment] 2022-08-11 10:29
> My more general concern about TB and its add-ons: Why must TB change its APIs and functions for major releases? This requires a lot of re-write for add-on developers, and a lot of work for users when they upgrade, or they are forced to stay on older versions of TB. In any case, acceptance is being reduced.
Why can TB not provide more stable interfaces for add-on development?
The number of add-ons will also be reduced since many developers don't have the time and money to continue adapting and updating their add-ons for new TB versions.

Thunderbird is actually working on providing a set of stable APIs, the WebExtension APIs. However, it is still a lot of work and TbSync is not yet using them, but the "old" approach. My free time is limited because ... *drum roll* ... I am a full time MZLA employee and my day job is to work on those WebExtension APIs.

**Comment by smmehta1822** [comment] 2022-08-11 12:36
> > My more general concern about TB and its add-ons: Why must TB change its APIs and functions for major releases? This requires a lot of re-write for add-on developers, and a lot of work for users when they upgrade, or they are forced to stay on older versions of TB. In any case, acceptance is being reduced.
> > Why can TB not provide more stable interfaces for add-on development?
> > The number of add-ons will also be reduced since many developers don't have the time and money to continue adapting and updating their add-ons for new TB versions.
> 
> Thunderbird is actually working on providing a set of stable APIs, the WebExtension APIs. However, it is still a lot of work and TbSync is not yet using them, but the "old" approach. My free time is limited because ... _drum roll_ ... I am a full time MZLA employee and my day job is to work on those WebExtension APIs.

Thank you for the update and take your time as you have a day job as well.

**Comment by GCamp6** [comment] 2022-08-12 14:44
> > > > I am currently torn how much work I should put into the category manager.
> > > 
> > > 
> > > I never used it. my main use case of TBSync is getting the Exchange/Outlook calendar entries synced into Thunderbird.
> > 
> > 
> > I am also looking for the same - TBSync getting the Exchange/Outlook calendar entries synced into Thunderbird 102+.
> 
> +1 for me. I also only use Tbsync for synching Thunderbird with Exchange/Outlook calendar enties. It's a fantastic addon (or set of 2 addons: TbSync + Exchange Provider addon).

My company uses Outlook and on my pc I installed Thunderbird. I need to have access to the outlook company's calendars, in the past was super easy and smooth thanks to TbSync! Hope to be able to be back on using this feature soon. Thanks for the great work

**Comment by GrizzlyAK** [comment] 2022-08-19 07:46
I REALLY hope you are able to get this updated soon, and don't abandon it altogether. I've installed Cardbook, which is already compatible with v102, and it is pretty feature rich, and seems to work fine, but I've grown comfortable with TBSync. Plus, Cardbook doesn't do Calendars.

Please let us know if you still intend to update TBSync,. I've turned off auto-update on TB for now.

**Comment by mdi22** [comment] 2022-08-22 09:55
Thank you for your hard work.

Still, I'm using Exchange for my "real" work and having a system that is not working and evaluating more or less well working alternatives (like davmail) when I have other things to do is not very satisfying.

Would it be less stressful for everybody if you could add a warning to the Addon?

_Warning: This addon is backed by just one developer in spare time. Use it with caution and be ready that it stops working without warning at any time._

**Comment by spaetz** [comment] 2022-08-22 10:56
> Warning: This addon is backed by just one developer in spare time. Use it with caution and be ready that it stops working without warning at any time.

You'd probably have to add this exact warning for 80% of all add-ons.
I just wonder how many people who claim that this add-on is absolutely crucial for them and that he should hurry up have donated money to the developer. He has stated a few days ago that he is on it, and that he has a paid full-time job besides doing free support for his voluntary efforts. Give the man time to do it on his own schedule or hire him to get it done faster.

**Comment by GrizzlyAK** [comment] 2022-08-22 19:41
> He has stated a few days ago that he is on it, and that he has a paid full-time job besides doing free support for his voluntary efforts

As I understand it, the dev actually works for Mozilla, on TB, and on the very thing that broke this add-on. Seems to me he should have seen this coming and at least could have warned users not to upgrade. Unless, of course, he was hired _after_ the update, which is possible.

> Give the man time to do it on his own schedule or hire him to get it done faster.

Many of us, including myself, already sponsor multiple FOSS devs/orgs here on GitHub, some of us monthly, so you can save your shaming. No one who reads the README.md for this project would come away believing that the project "team" isn't committed to maintaining and improving the project. Yeah, sure, EVERYBODY asks for donations now, but your comment gives a whole new meaning to FOSS, almost like, _get 'em hooked, then hold them hostage_. 🙄

**Comment by GrizzlyAK** [comment] 2022-08-22 19:57
> When we get to the "spare me your...." is where I unsubscribe.

Says the user with a _private_ profile who just dropped in to make a snarky comment. I guess you missed the whole "Open" part of FOSS. Why are you hear?

**Comment by DavidBE-UK** [comment] 2022-08-22 20:22
>  I managed to work out that it wuldn't work because of the maximum version number on the listing in addons.

Actually TbSync with EAS worked fine up to TB 98. The number in the addons listing is either just as high a TB version as the developer has tested it with, or as high a TB version as they're prepared to provide support for. It's not necessarily the limit of what it will work with. Having gone to the betas with TB 92, every major version upgrade I just bumped up the max_version in the manifests of all the extensions I use and tried them, and all the other extensions actually kept going fine up to and including the 102 general release. TbSync with EAS failing from TB98 on up was the only extension I use that stopped working even though every single one had the max TB 91 listed on the addons pages.

**Comment by Kurti123** [comment] 2022-08-26 09:39
Let's just hope that Mozilla finally hired John zu once and for all integrate Outlook 365 integration to TB.

**Comment by RaphaelaH** [comment] 2022-08-27 15:23
> iCloud

Unfortunately, the process is a bit more complicated than described in the article for more recent calenders, as these do not use the name anymore, but an ID. You can use this link of course https://github.com/midnightmonster/icloud-calendar-urls but if that is not possible, then you can use the following method to find the long alphanumeric ID, it should look something like this: b8e0edb4-1acd-445a-b20e-66a1bf964bb7. So the overall URL would then be for example:  https://p12-caldav.icloud.com/586234577/calendars/b8e0edb4-1acd-445a-b20e-66a1bf964bb7/

In the debugging console, for the POST entry (the first) as described in the link, the is a filename which has two ID components. Take the first one, as marked yellow here, and use it for the URL. 
![grafik](https://user-images.githubusercontent.com/78073608/187036641-41fc3460-4fa8-4caf-8b69-8442db0ed56f.png)

**Comment by axelrathey** [comment] 2022-08-28 16:29
Hi,
are there any news with tbsync with TB 102? I need "TBSync" and "Provider für Exchange ActiveSync" Addon to sync TB with exchange.

Thanks Axel

**Comment by TRPB** [comment] 2022-08-30 17:20
For those waiting for office365/outlook calendar, a partial workaround is sharing the calendar (Log in to the web UI, click share at the top right, email yourself a link. I don't know if it has to be an email address that isn't the outlook address) Then right click and copy the link at the bottom of the email that says "this URL"

Finally, add the calendar as a network calendar in thunderbird, paste the URL from the email, no username needed.

This isn't ideal as the calendar is read only, but at least lets you see your events until tbsync is updated :)

**Comment by sleeksorrow** [comment] 2022-08-30 21:11
Well I for myself got a clue when TB automatically created a new profile instead of using the old one, so I could backup that whole profile before trying. Additionally I'd like to remind that this issue is about TbSync, not TB, so maybe your ideas and thoughts about TB will not reach the right people here.

**Comment by stratosjl** [comment] 2022-09-05 12:05
TbSync should be part of the main TB branch, it's a no-brainer.
This is brilliant work; many of us simply cannot use TB without it in corporate (e.g. Exchange-based) environments. Thank you John, for your hard work.

**Comment by dsommers** [comment] 2022-09-07 10:28
I see several comments here that TB-102 has built-in CalDAV/CardDAV support.  But that's something which already existed in older Thunderbird versions too.

What for me gives TbSync an edge is that I configure a *single* server, which gives me all calendars and contact books in a single setup.  When the password needs to be changed, I change it *one* place and it's all set.  I don't know if this has improved in TB-102, but in prior versions I needed to do each calendar and each contact book setup individually.  And if the password changed, it was a complete mess until it got updated in all the right places.

I hear rumors that @jobisoft has become a fulltime hire of Mozilla, working on Thunderbird.  If this is true, who can we talk to in the Mozilla/Thunderbird teams so we can get TbSync fully integrated with Thunderbird out-of-the-box?  The Exchange and ActiveSync support could still be add-ons.  And an EteSync adapter would also be immensely cool.

**Comment by axelrathey** [comment] 2022-09-07 12:23
In old TB-Versions <=91.*.* you have CalDAV support but no CardDAV support. For CardDAV Support you need the CardBook AddOn.
CalDAV Support in TB <= 91.*.* is difficult to admin because you have to config each calendar you have in an CalDAV account.

Axel

**Comment by dsommers** [comment] 2022-09-07 13:14
@axelrathey This is from a new, fresh and clean Thunderbird profile, going into the address book (CTRL-B) and selecting File->New->CardDAV Address Book.  No add-on's added.

![image](https://user-images.githubusercontent.com/1685255/188886847-c7578ab9-2f85-4d3a-9bed-b80b40dc5c97.png)

**Comment by dbonner** [comment] 2022-09-07 15:01
Hi John and Hi all. I've held back on commenting for a few weeks now because I don't want to put pressure on John. I guess it would be nice to know where things are up to (no judgment will come from me if TbSync on esr-102 is a no-go).  I'm guessing that Thunderbird 91.14.0 will be the final in the esr-91 series and that 91's end of life will be in a few weeks' time. My current plan is to continue using Thunderbird 91 beyond the end of life because I need Tbsync for my two most important email addresses (one for the hospital and one for the university, both emails being hosted on Exchange).  I'm a little fearful of the security implications for going beyond end of life, but nevertheless that's my plan if TbSync on esr-102 is a no-go. All the best, Daniel.

**Comment by GrizzlyAK** [comment] 2022-09-07 18:25
>  But that's something which already existed in older Thunderbird versions too.

I don't believe that is correct. IIRC, before moving to TB from Outlook, I specifically researched how to sync both calendars and contacts among devices, and found that TB was not capable of the same functionality I had in Outlook 2010, until I discovered TBSync. I also considered CardBook, but that is only CardDAV, not CalDAV, and I need both.

However, looking back on that decision now, I think choosing TB over upgrading to the latest version of Outlook might have been a mistake, given how Mozilla pulled the rug out from under us in 102. I should have known, though, in light of similar issues I've experienced the last 20 years with Mozilla updates with Firefox. I've stopped updating FF because I grew tired of re-configuring it every single time, or troubleshooting things that broke.

Oh, the joys (and pains) of OSS.

**Comment by dsommers** [comment] 2022-09-07 18:32
> >  But that's something which already existed in older Thunderbird versions too.
>
> I don't believe that is correct. [...]

@GrizzlyAK Please see the screenshots in [this comment](https://github.com/jobisoft/TbSync/issues/591#issuecomment-1239374802).

The CalDAV support is the same, add a new calendar and choose "On the network", then you get this window:
![image](https://user-images.githubusercontent.com/1685255/188952190-1f8c3966-c4b8-432d-8681-c9ee1d36b0f2.png)

This is just now, from the same version as the former screenshot.  The address field here requires the URL to an specific calendar.  TbSync makes that simpler, as it figures out which calendars are available for you.

**Comment by Kurti123** [comment] 2022-09-07 19:16
There's another plugin for Exchange synchronization, it's called Owl and already works with TB 102. It costs ~10 Bucks a year and they have a 30 day trial period, in case some of you want to just bridge the time it takes for TbSync to be ready (or not). 

If, for some of the commenters here, Exchange integration with TB is so important as they claim to be, 10 bucks a year would be a hell of a deal. 

https://addons.thunderbird.net/en-us/thunderbird/addon/owl-for-exchange/versions/?page=1#version-0.8.3

**Comment by GrizzlyAK** [comment] 2022-09-07 20:03
> The CalDAV support is the same, add a new calendar and choose "On the network", then you get this window: ![image](https://user-images.githubusercontent.com/1685255/188952190-1f8c3966-c4b8-432d-8681-c9ee1d36b0f2.png)

Hmm...  If this is true, why do any of us use TBSync? I get my address book from my hosting provider and my calendar from iCloud, and both need to be a two-way (push/pull) sync, not read only. Does your example provide that?

**Comment by lectrode** [comment] 2022-09-07 20:07
> If, for some of the commenters here, Exchange integration with TB is so important as they claim to be, 10 bucks a year would be a hell of a deal.

 i've used that for the past year, and i can confirm that extension is a good option. i use that extension for accessing email, the global address list, and the basic user-specific calendar. it works well for those things. if that's all you need, it should work for you.

however,  it does not support syncing other calendars (like a company-provided holiday calendar). i'm unsure if it supports syncing "tasks", as that's not a feature i use with that account. afaik, that's the only shortcoming currently. i've been using tbsync to sync additional calendars (and formerly contacts from before owl supported that).

**Comment by dsommers** [comment] 2022-09-07 21:03
@GrizzlyAK TbSync has a few extra features which makes it way easier to use CardDAV and CalDAV.

* TbSync does auto-discovery of available calendars and address books.  Provide service URL and credentials, and you get everything setup instantly.
* TbSync requires only a single set of username/password per server.  The Thunderbird method requires providing credentials per calendar and address book.  Which gets quite tedious when changing the password.

TbSync just gives a much better user experience than the native Thunderbird approach.

**Comment by gbakeman** [comment] 2022-09-07 21:29
I have a Nextcloud instance that I use as my primary CalDAV/CardDAV server and I've been using just the native functionality to access it. My biggest complaint is that there's a delay between making changes and those being updated, but otherwise it works. I'd definitely like to see some improvements to the *DAV experience in Thunderbird, and for reference [here's](https://bugzilla.mozilla.org/buglist.cgi?short_desc_type=allwordssubstr&bug_status=UNCONFIRMED&bug_status=NEW&bug_status=ASSIGNED&bug_status=REOPENED&bug_status=RESOLVED&bug_status=VERIFIED&order=Importance&resolution=---&query_format=advanced&short_desc=calendar&classification=Client%20Software&classification=Developer%20Infrastructure&classification=Components&classification=Server%20Software&classification=Other&product=Thunderbird) a search in the Bugzilla for anything relating to the string "calendar".

**Comment by dbonner** [comment] 2022-09-08 09:56
> > If, for some of the commenters here, Exchange integration with TB is so important as they claim to be, 10 bucks a year would be a hell of a deal.
> 
Hi, Kurti123 I do subscribe to Owl ($20/year for 2 Exchange accounts). I can't read emails without it.  However, may main email address seems to have extra security measures around calendar syncing.  TbSync works for calendar sync perfectly well.  Owl seemed to work OK at first.  However, if an appointment is deleted using Outlook (e.g. by work colleagues with access to my calendar) then the appointment fails to be deleted in Thunderbird (if I rely on Owl for calendar sync).  The Owl guys are aware of my difficult.  However, they are stretched thin too at the moment.
All the best,
Daniel

**Comment by Michal-Szczepaniak** [comment] 2022-09-12 21:52
Any update from the maintainer?

**Comment by arunskrish** [comment] 2022-09-16 05:42
Same here .. any update? Thanks.

**Comment by jobisoft** [comment] 2022-09-16 07:43
For the exchange active sync provider, please head over to:
https://github.com/jobisoft/EAS-4-TbSync/issues/167

**Comment by Michal-Szczepaniak** [comment] 2022-09-16 07:46
Yeah I'm more interested in Nextcloud :P

**Comment by dvestezar** [comment] 2022-09-18 14:52
> but for cardDav addresss book, How should I fill it? ![image](https://user-images.githubusercontent.com/3435696/176909701-8251bbc6-59ef-40f3-80ed-f1a9b461cfb4.png)

### tested, working

**name** = ***google mail*** = name@google.com

click next - show up login - check adresbook - finish

**Comment by GrizzlyAK** [comment] 2022-09-19 03:38
I admit I'm a little confused about what is possible or not in TB without TBsync. I moved to TB earlier this year from Outlook primarily because of the existence of TBSync, so I'm currently stuck on v91. I'm hoping someone in the know can help me out. 

I have simple needs. I have several address books hosted on my web hosting provider. I use iCloud for my Calendar and Tasks. All of this works wonderfully on TBSync.

I've installed Cardbook, and it seems to work for my address books, but I do not prefer it over TBSync. However, I don't know of an iCloud calendar replacement for TBSync. If anyone has similar basic needs like mine and have found a suitable replacement for TBSync for Card/CalDAV, please let me know what they are. I'd like to update TB and it sounds like this incompatibility will not be resolved any time soon. 

Any advice would be appreciated.

**Comment by dsommers** [comment] 2022-09-19 09:16
@GrizzlyAK How I see it, TBSync adds the last missing glue to Thunderbird which makes use of CardDAV and CalDAV simpler and more user friendly.

For example with stock Thunderbird ; the URL needed must be exactly to just a single calendar or contacts file.  And you need to provide credentials for that specific file.  If you want to add more calendars or contacts, it's the same steps for each of them; even if it is on the same server. Find the unique URL to what you need, provide credentials.

With TBSync ... You add a new CalDAV/CardDAV server, provide a generic URL to that service.  TBSync supports auto-discovery of all available calendars and contact books.  So after giving it the URL to the service/server, TBSync asks for credentials and retrieves everything available.  The next you do is to just mark all the calendards and address books available, and Thunderbird is full configured.  This can easily be tested with [Radicale](https://radicale.org/v3.html), which provides auto-discovery support as well.

TBSync is also extensible to support more protocols, like Exchange OWA.  I know there's been some work on [EteSync](https://github.com/etesync/EteSync-4-TbSync) support as well; which would be awesome (you wouldn't need the [EteSync DAVBridge](https://github.com/etesync/etesync-dav/#etesync---secure-data-sync) running locally).

**Comment by jim-davenport** [comment] 2022-09-19 12:09
I am using the TBSync Beta on 102.2.2. Everything seems to work with the exception of this sync error on my Hotmail contacts.

Unable to set DisplayName as a property, use vCardProperties

setProperty@resource:///modules/AddrBookCard.jsm:371:13
setProperty@chrome://tbsync/content/modules/addressbook.js:381:20
setThunderbirdItemFromWbxml@chrome://eas4tbsync/content/includes/contactsync.js:145:28
processCommands@chrome://eas4tbsync/content/includes/sync.js:933:53

**Comment by jgato** [comment] 2022-09-19 12:24
how did you get the beta version?

**Comment by jim-davenport** [comment] 2022-09-19 13:22
Early version. Not to be used in production. https://github.com/jobisoft/EAS-4-TbSync/issues/167#issuecomment-1249030422

**Comment by aries223** [comment] 2022-09-19 16:31
> I admit I'm a little confused about what is possible or not in TB without TBsync. I moved to TB earlier this year from Outlook primarily because of the existence of TBSync, so I'm currently stuck on v91. I'm hoping someone in the know can help me out.
> 
> I have simple needs. I have several address books hosted on my web hosting provider. I use iCloud for my Calendar and Tasks. All of this works wonderfully on TBSync.
> 
> I've installed Cardbook, and it seems to work for my address books, but I do not prefer it over TBSync. However, I don't know of an iCloud calendar replacement for TBSync. If anyone has similar basic needs like mine and have found a suitable replacement for TBSync for Card/CalDAV, please let me know what they are. I'd like to update TB and it sounds like this incompatibility will not be resolved any time soon.
> 
> Any advice would be appreciated.

@GrizzlyAK I use TB 102.2.2 and have it working just fine with the buit in Cal/CardDav. Its not difficult to set up, you just need to figure out the string for each ical calendar manually.

Begin reading here, I get it setup with another users help.
https://github.com/jobisoft/TbSync/issues/591#issuecomment-1203049120

**Comment by GrizzlyAK** [comment] 2022-09-19 17:30
And everything syncs both ways OK for both address books and calendars? I was under the impression the calendar was only read only. Are you using iCloud calendars by chance?

**Comment by aries223** [comment] 2022-09-19 23:22
> 

Yes everything syncs fine, both ways. Yes I use iCloud for calendars and contacts, and use TB on an iMac, Windows 10 and Linux machines. All sync both ways just fine.

**Comment by GrizzlyAK** [comment] 2022-09-20 01:13
Very cool! I'll give it a try. Thank you!

**Comment by aries223** [comment] 2022-09-20 19:09
@GrizzlyAK  This link is what I used for manually determining the iCal calender URL:
https://frightanic.com/apple-mac/thunderbird-icloud-calendar-sync/

Unfortunately the link to the Addressbook part of this is now 404. Youll have to figure that part out, maybe try the script link..

**Comment by to82** [comment] 2022-09-21 06:28
Thank you for all the great work that goes into TBSync and it is greatly appreciated. With the internal CardDAV solution we have the problem that distribution lists are not synchronized as well. CardBook would possibly go, but needs training of colleagues. The nice thing is that the address books from TBSync show up in the regular address book. Will it be possible to synchronize distribution lists again with the new version? There was a sync issue in TBSync as well, which is why there was the checkbox for contact group sync. When can we expect a new version. A big thanks already!

**Comment by hellsbelz** [comment] 2022-09-21 08:45
I was using TBSync just a couple of weeks before TB was updated automatically and I gut stuck in the "incompatility trap". I used it for syncing my adressbook with the iCloud, which worked perfectly. I would like to thank @jobisoft for his great work so far  to encourage him to solve the incompatibility issue.

**Comment by jobisoft** [comment] 2022-09-21 12:26
There is now also an update for TbSync/DAV available here:
https://github.com/jobisoft/DAV-4-TbSync/issues/283

For reference, the update for TbSync/EAS is available here:
https://github.com/jobisoft/EAS-4-TbSync/issues/167

**Comment by jobisoft** [comment] 2022-10-16 11:03
Released on ATN.

**Closed by jobisoft** 2022-10-16 11:03 UTC
