### ISSUE TITLE
No idea where the Tbsync configuration menu is, not specified anywhere

### ISSUE THREAD

**Issue by UgoFlamarion** [jobisoft/TbSync#503] opened 2021-02-27 11:31 UTC
The screenshot points at a Tools > Add-on options > TbSync that does not exist on my version (78.7.1 64bit).
All I have is a Add-ons Manager tab where I get nothing but this :
![image](https://user-images.githubusercontent.com/1921477/109385941-9a8b2e80-78f7-11eb-8152-478ec0a01c0d.png)

I couldn't find a way to open the menu.

**Comment by jobisoft** [comment] 2021-02-27 12:31
Wait a few days, I have just landed:
https://thunderbird.topicbox.com/groups/addons/T02a09c034809ca6d/resolving-the-add-on-options-chaos-introduced-by-my-wrapper-apis-windowlistener-and-bootstraploader

**Comment by jobisoft** [comment] 2021-03-18 19:48
Duplicate of #462

**Closed by jobisoft** 2021-03-18 19:48 UTC
