### ISSUE TITLE
Can't see free-busy information of my attendees 

### ISSUE THREAD

**Issue by wit12345** [jobisoft/TbSync#252] opened 2019-04-24 10:35 UTC
## Your environment

TbSync version: 0.15
DAV-4-TbSync version:
Thunderbird version: 60.6.1 

Yes, I have installed the latest available (beta) version from 
 - https://github.com/jobisoft/TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
When I'm make a new appointment I want to see the free-busy information of my attendees .

## Actual behavior
When I'm make a new appointment I can't see the free-busy information of my attendees 

## Steps to reproduce
Go to calendar, create a new event and add the attendees.

Is this a bug? 

If more information is needed I will be happy to provide.

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email). done

**Comment by jobisoft** [comment] 2019-04-24 11:46
You set up a caldav calendar using TbSync and when you want to add an event to that calendar in lightning, you see no free-busy-info? Can I have a screenshot? Via Email if confidential.

**Comment by wit12345** [comment] 2019-04-24 12:04
Hi @jobisoft,
Sure, can you give me your email please?

**Comment by jobisoft** [comment] 2019-04-24 12:07
It is right here (and you already wrote me an email/bug report) :-) : 
https://github.com/jobisoft

II just saw your comment on the EAS issue. Are we talking about a CalDAV calendar (created with TbSync/DAV) or an Exchange calendar (created with TbSync/EAS)?

**Comment by wit12345** [comment] 2019-04-24 12:13
I'm talking about a CalDAV calendar (created with TbSync/DAV) :)

**Comment by jobisoft** [comment] 2019-04-24 12:36
Ok, than this is unrelated to TbSync, since TbSync only creates the CalDAV calendars in lightning. All further handling is done by lightning. You could disable Tbsync and the calendar sync will still be working. (This is different for EAS calendars, where TbSync is doing the sync and all related tasks).

I do recall, that CalDAV supports free-busy, but I am not an expert on that. Maybe your Server does not provide the needed information?

Sorry, I am of no help for you in that case.

**Comment by wit12345** [comment] 2019-04-24 13:23
Hmmm, ok :)

Yes, I think my server (Horde Groupware Webmail Edition) provide the needed information because for example with the Evolution Mail and Calendar everything works fine.

**Comment by jobisoft** [comment] 2019-04-24 13:25
You are sure, that you Setup the calendar in Evolution Mail using CalDAV as well, and not EWS? just trying to help...

**Comment by wit12345** [comment] 2019-04-24 13:29
I know :) 

I have the EWS disabled in my configuration (https://wiki.horde.org/ActiveSync)

**Comment by jobisoft** [comment] 2019-04-26 18:41
I am closing this, as I cannot fix this, as it is caused by Lightning.

**Closed by jobisoft** 2019-04-26 18:41 UTC
