### ISSUE TITLE
Request: GAL contacts also in auto complete (not only on search results)

### ISSUE THREAD

**Issue by nitro322** [jobisoft/TbSync#39] opened 2018-01-26 17:20 UTC
The original issue has been resolved, there is now a follow up request regarding auto complete, which starts https://github.com/jobisoft/TbSync/issues/39#issuecomment-399968276

---

Hello.  I'm a new user of TbSync, trying to use it with my work Office 365 account.  Having an odd error that I haven't seen addressed here (or just missed).  When setting up the account, the autodiscover process appears to be successful.

```
** Fri Jan 26 2018 11:10:34 GMT-0600 (CST) **
[Trying EAS autodiscover] : [https://autodiscover-s.outlook.com/Autodiscover/Autodiscover.xml]

** Fri Jan 26 2018 11:10:34 GMT-0600 (CST) **
[Error on EAS autodiscover (400)] : <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">
<HTML><HEAD><TITLE>Bad Request</TITLE>
<META HTTP-EQUIV="Content-Type" Content="text/html; charset=us-ascii"></HEAD>
<BODY><h2>Bad Request - Invalid Verb</h2>
<hr><p>HTTP Error 400. The request verb is invalid.</p>
</BODY></HTML>


** Fri Jan 26 2018 11:10:34 GMT-0600 (CST) **
[Trying EAS autodiscover] : [https://autodiscover-s.outlook.com/Autodiscover/Autodiscover.xml]

** Fri Jan 26 2018 11:10:34 GMT-0600 (CST) **
[EAS autodiscover with response (status: 200)] : 
<?xml version="1.0" encoding="utf-8"?>
<Autodiscover xmlns="http://schemas.microsoft.com/exchange/autodiscover/responseschema/2006">
  <Response xmlns="http://schemas.microsoft.com/exchange/autodiscover/mobilesync/responseschema/2006">
    <Culture>en:us</Culture>
    <User>
      <DisplayName>Name</DisplayName>
      <EMailAddress>email@domain.com</EMailAddress>
    </User>
    <Action>
      <Settings>
        <Server>
          <Type>MobileSync</Type>
          <Url>https://outlook.office365.com/Microsoft-Server-ActiveSync</Url>
          <Name>https://outlook.office365.com/Microsoft-Server-ActiveSync</Name>
        </Server>
      </Settings>
    </Action>
  </Response>
</Autodiscover>

** Fri Jan 26 2018 11:10:34 GMT-0600 (CST) **
[EAS OPTIONS with response (status: 200)] : 
[] [2.0,2.1,2.5,12.0,12.1,14.0,14.1,16.0,16.1] [Sync,SendMail,SmartForward,SmartReply,GetAttachment,GetHierarchy,CreateCollection,DeleteCollection,MoveCollection,FolderSync,FolderCreate,FolderDelete,FolderUpdate,MoveItems,GetItemEstimate,MeetingResponse,Search,Settings,Ping,ItemOperations,Provision,ResolveRecipients,ValidateCert,Find]
```
I don't know why it gets that first 400 error, but the second query succeeds and returns my name and email.  It defaults to outlook.office365.com and activesync version 14.0.  After clicking Connect account, it states that the connection status for both my Contacts and Calendar is OK.  New entries are indeed added to my calendar and address book, but I see no actual data in either.

Looking at the debug log, it correctly pulls and lists all of my folders.  I then see a bunch of additional sync activity, see it creating the local address book and calendar, etc.  No errors that I can find.  However, no actual data (events or contacts) are pulled down.  Searching the address book also fails.  If I create a new message and try to auto-complete someone's e-mail address, I get this in the debug log:

```
** Fri Jan 26 2018 11:18:44 GMT-0600 (CST) **
[JavaScript Error: "uncaught exception: 2147746065" {file: "resource:///modules/activity/autosync.js" line: 210}]
```

Any idea what might be going on?  I'm going to share my debug.log via e-mail since I'd prefer not to pose the full contents here.

Thanks.  Appreciate any help.

**Comment by jobisoft** [comment] 2018-01-26 17:37
I do not know why I get the invalid verb on the first try. I have to aks twice to get the data. I do not know why.

The shown error is not from TbSync.

The selected addressbook and calendar appear to be empty indeed, are you sure there is data in them? (Maybe you have multiple addressbooks / calendars and the data is not i the default ones, which are subscribed to automatically?)

Can you retry with [beta2](https://github.com/jobisoft/TbSync/releases/download/v0.7/TbSync-0.7.1-beta2.xpi)

**Comment by nitro322** [comment] 2018-01-26 17:42
Wow, thanks for the quick reply.  Yes, I'll try the beta shortly and let you know.  As for the other questions:

1. Yes, I'm certain there are plenty of events on my calendar  ;-)
2. It's possible I may be using a non-default calendar or something, but I don't remember explicitly doing that.  Do you know of any way to test for that?

**Comment by jobisoft** [comment] 2018-01-26 17:47
the account manager lists all avail calendars, tasks and adressbooks, you just have to enable/disable them by doubleclick. Only the default calendars are enabled by default.

**Comment by nitro322** [comment] 2018-01-26 17:51
Just tried beta2.  I see a Tasks entry now in my calendar list, but otherwise the same behavior - everything appears to connect and sync properly, just get no calendar invites, and still can't find anyone in the address book.

Regarding the additional calendar/contacts folders, I did also have:
Skype for Business Contacts
Suggested Contacts

I enabled and synced both of them.  New address book additions, but still can't find anyone.  There were no additional calendar folders.

**Comment by jobisoft** [comment] 2018-01-26 17:53
disconnect account, restart TB, reconnect account, when done, send debug.log

**Comment by nitro322** [comment] 2018-01-26 18:01
sent.  Btw, I normally wouldn't mention this in a bug report, but you're so responsive I feel I should give you a heads up - I'm about to step away for lunch and a couple of back-to-back meetings, so I'll be away for a bit.  Will follow up as soon as I can.

Thanks.

**Comment by jobisoft** [comment] 2018-01-26 18:09
thanks, but the log contains autodiscover, which it should not. Please hit the "disconnect" button in the account manager, you should now see all the options including server.

Now restart Thunderbird, which clears the debug.log

Now hit the "connect account" button, which will get the folders and sync the default calendar, tasks and addressbook.

After TbSync ist done (State idle in the lower right corner) get the debug log and send it to me.

**Comment by jobisoft** [comment] 2018-01-26 18:22
Nevertheless, your folders are empty. Beta2 is asking the server in advance for an estimate of the changes to be able to give a progress feedback. Your server reports 0.

```
** Fri Jan 26 2018 11:58:51 GMT-0600 (CST) **
[Receiving data <send.request.estimate> for AutoZone (Calendar) (XML)] : 
<?xml version="1.0"?>
<GetItemEstimate xmlns='GetItemEstimate'>
<Response>
<Status>1</Status>
<Collection>
<CollectionId>2</CollectionId>
<Estimate>0</Estimate>
</Collection>
</Response>
</GetItemEstimate>
```

```
** Fri Jan 26 2018 11:58:51 GMT-0600 (CST) **
[Receiving data <send.request.estimate> for AutoZone (Contacts) (XML)] : 
<?xml version="1.0"?>
<GetItemEstimate xmlns='GetItemEstimate'>
<Response>
<Status>1</Status>
<Collection>
<CollectionId>5</CollectionId>
<Estimate>0</Estimate>
</Collection>
</Response>
</GetItemEstimate>
```

```
** Fri Jan 26 2018 11:58:52 GMT-0600 (CST) **
[Receiving data <send.request.estimate> for AutoZone (Tasks) (XML)] : 
<?xml version="1.0"?>
<GetItemEstimate xmlns='GetItemEstimate'>
<Response>
<Status>1</Status>
<Collection>
<CollectionId>26</CollectionId>
<Estimate>0</Estimate>
</Collection>
</Response>
</GetItemEstimate>
```
I cannot help here. What happens if you connect the same account on an iPhone or some other EAS client? You sure, you connected the right account and your data is in yoir own folders and not something globally shared?

**Comment by nitro322** [comment] 2018-01-26 21:05
Huh.  So I just restarted again (about my sixth restart), and this time it picked up my calendar entries on the sync after restart.  No idea what was different compared to that vs. previous restarts/syncs, but at least calendar is working now.

Regarding contacts, I think I may be misunderstanding what's supposed to be happening there.  I don't use OWA/Outlook as an address book; my personal contacts are in Thunderbird.  However, I need to be able to lookup addresses in our corporate directory, which itself is in Office 365.  Should *that* be resolvable or synced through tbsync?  or asking that question a little differently, if I start entering a recipient's name in an e-mail address, when thunderbird tries to autocomplete that address should it be able to match against our corporate directory?

You asked about other products...  on my phone I use Aqua Mail and it both searches/autocompletes addresses as well as syncs my calendar.  Didn't have to do anything special there.  In Thunderbird I previously used the exchangecalendar / Exchange EWS Provider extension - this worked for both contact searching and calendar syncing, but was too buggy for day-to-day use.  I most recently was using evolution with it's EWS module, which again worked fine regarding calendar sync and contact search (though I had other issues with evolution itself as a mail client).

So, I don't think there's anything especially unusual with my account.  Now that calendar sync is working (for whatever reason), my main concern is contact searching.  Would appreciate if you could clarify the expected behavior here.

Thanks.

**Comment by jobisoft** [comment] 2018-01-26 21:17
Hi, the global address book search (GAL) is not yet implemented, it is on the lower end of my [todo](https://github.com/jobisoft/TbSync/wiki/Detailed-changelog-&-roadmap) list. I know i can access and search the GAL via EAS, but I have not yet even looked at a possible integration in Thunderbird.

The current use case of TbSync is to sync ones own folder from the server to Thunderbird and sync back changes to the server. This is still a pre release and contacts are still buggy. I am going to fix contacts next. With version v0.8 you should be able to copy your local Thunderbird contacts into the EAS Adressbook (created by TbSync) and sync those to your server. At the moment this is not suggested, because there are issues with Thunderbird lists which mess everything up.

**Comment by nitro322** [comment] 2018-01-26 22:01
OK, got it.  In that case the contacts thing is a misunderstanding on my part, and with calendar working now it looks like there's no issue here after all.  :-)  Will close.

Thanks for the information and clarification.  Definitely appreciate your time.

**Comment by jobisoft** [comment] 2018-06-11 15:25
GAL search is now part of the latest beta. Feedback would be appreciated.

**Comment by nitro322** [comment] 2018-06-25 14:18
Hello.  I just saw your note about GAL search now being included.  That's great news!  Was testing and it does seem to work as far as adding an entry to may address book and letting me search through there, but I can't get Thunderbird to auto-complete against that when composing a new message.

Are you aware of anything I may need to enable for that?  The only related settings I could find are:

Account Settings:
Composition & Addressing
	Addressing
		[*] Use my global LDAP server preferences for this account

Global Preferences:
Composition
	Addressing
		[*] Local Address Books
		[ ] Directory Server

I previously had an LDAP connection to our local domain controller defined to do the address lookups, which I deleted to test whether this was working properly.  Have Directory Server unchecked in the options above because it only refers to LDAP servers, of which none are currently defined.

Any ideas?  Also, is there another, better place you'd prefer to discuss this rather tan this bug report?

**Comment by jobisoft** [comment] 2018-06-25 16:15
Thanks for the feedback. I did not implement auto-complete. I implemented address book search in the main address book and in the F9 contact sidebar (which might be a replacement for auto-complete)

I put this back on the todo list. However, currently I do not know how auto complete works at all. I am not connecting to an LDAP directory, but send a "find a match" request to your server and add those entries on the fly to your address book, and remove them, when search is closed.

**Comment by nitro322** [comment] 2018-06-25 16:50
Thanks for the clarification.  Unfortunately, I can't help much with autocomplete either, just know that it's a life saver in a large organization.  :-)  If/when that can ever be added, that'd be fantastic, though this is still a great step forward even without.

Regarding the current implementation, I did have one extra piece of feedback.  When I search for a user, all of the results come back with the tbsync account name appended to their display name.  So, if I search for a user and then compose a message to one of the results, the To: line is:

Last, First (Account Name) <first.last@company.com>

That's not how the entries actually appear in our address book, and it'd be confusing to send out e-mails addressed as such.  Would it be possible to remove that?

**Comment by jobisoft** [comment] 2018-06-25 18:00
I added that suffix, so theses entries could be identified as GAL search results. I will think of something else...

**Comment by jobisoft** [comment] 2018-07-07 06:32
I have now understood how to register custom XPCOM components with boostraped addons, which was the main reason why I could not integrate autocomplete. Now it is just a matter of time and putting the pieces together.

**Comment by jobisoft** [comment] 2018-07-07 22:34
Would you like to test autocomplete?
https://github.com/jobisoft/TbSync/releases/download/v0.7.10/TbSync-beta.xpi

**Comment by nitro322** [comment] 2018-07-08 10:02
Absolutely!  Will try it out on Monday and give you some feedback.

**Comment by BillBrowne** [comment] 2018-07-09 03:00
I can confirm that autocomplete is working now.  It's as fast as the tweaked LDAP lookup I have running in parallel on the same server.

**Comment by jobisoft** [comment] 2018-07-09 06:17
Thanks for the feedback. If you like TbSync, consider a donation to help be continue to work on this extension.
https://www.paypal.me/johnbieling

**Comment by nitro322** [comment] 2018-07-09 14:29
Hello.  When I got to work this morning, where I had left Thunderbird w/ TbSync running over the weekend, I had a message from TbSync stating that there was some error and that my sync account had been disabled (apologies, I didn't take a screenshot of that error).  Since I was going to upgrade anyway I used the Help tab to upgrade directly to 0.7.10, then re-enabled my account.

Calendar is syncing fine now, but Contacts gives me this message:  "Javascript error! Check debug log for details."  Debug log shows this:

```
[JavaScript Error: "tbSync.createAddressBook is not a function" {file: "chrome://tbsync/content/tbsync.jsm" line: 1300}]
tbSync.checkAddressbook@chrome://tbsync/content/tbsync.jsm:1300:25
eas.syncPendingFolders<@chrome://tbsync/content/provider/eas/eas.js:510:30
TaskImpl_run@resource://gre/modules/Task.jsm:320:42
Handler.prototype.process@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:935:21
this.PromiseWalker.walkerLoop@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:813:7
this.PromiseWalker.scheduleWalkerLoop/<@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:747:11
```

I tried restarting Thunderbird and disabling/re-enabling my account again, but keep getting that same error.  Any suggestions?

**Comment by nitro322** [comment] 2018-07-09 15:48
I'm having more significant issues.  When tbsync disabled itself over the weekend, it apparently created an "emergency backup" calendar to preserve my events.  When re-enabling the account, it created a second calendar.  I thought that may be causing some conflicts, so I figured I'd disable and remove my sync account, delete the emergency calendar, then start fresh.

However, after doing that I'm no longer able to add an account to tbsync.  I select Account actions, Add new account, Exchange ActiveSync (EAS), and then, aside from the menu going away nothing happens.  Repeat and get the same behavior every time.  Nothing gets added to the debug log, either.

Tried restarting Thunderbird as well as uninstalling and reinstalling tbsync with the same behavior.  So at this point, I seem to be unable to add an account to tbsync.  I suspect I can probably "fix" it by reverting to a previous version, but I can make due as is for the rest of the day if there's anything I can do to provide more details or help test anything.

**Comment by jobisoft** [comment] 2018-07-09 16:20
Why did you remove the emergency backup? Hm. Version 0.7.9 had an issue which did not show up during beta testing. I rewoked 0.7.9 and released 0.7.10 which did a total reset and backuped your data: usually a reset of tbsync also deletes all local sync targets, but because i did not know if you may have unsynced local changes, i backuped your data into that emergency backup.

Please install the latest beta and restart your entire pc to make sure all process of thunderbird get killed. The other issue you reported was fixed in the today beta release.

If you still have issues, delete the tbsync folder from your thunderbird profile while thunderbird is not running. This will reset to a total fresh start.

Latest beta (0.7.10.5 as of this writing)
https://github.com/jobisoft/TbSync/releases/download/v0.7.10/TbSync-beta.xpi

**Comment by jobisoft** [comment] 2018-07-09 16:38
You have found a new bug! With the latest beta, it is indeed no longer possible to create new accounts. I will fix that and release beta .6 as soon as possible.

**Comment by nitro322** [comment] 2018-07-09 16:39
Haha.  I seem to be good at that.  :-)  Was just about to reply back that I still got the same behavior even after the latest delete and restart.  Thanks - I'll keep an eye out for the update.

**Comment by jobisoft** [comment] 2018-07-09 20:31
I released beta 0.7.10.7, that version should be bug free and should have working autocomplete.

**Comment by nitro322** [comment] 2018-07-09 22:06
Thanks.  Just updated and I'm able to add an account again.  No data seems to be getting synced despite everything reporting okay, but that seems to happen whenever I disable/delete and then re-enable an account for some reason.  Usually my data shows up on it's own after a while.  I'll check on it tomorrow and see how things look, then report back.

**Comment by jobisoft** [comment] 2018-07-09 22:08
Does this help?
https://github.com/jobisoft/TbSync/wiki/Troubleshooting#office-365-and-maybe-other-microsoft-servers

**Comment by nitro322** [comment] 2018-07-10 13:46
Thanks for the tip.  Yeah, that does sound like exactly my problem.  Will try it next time.  In this case, my calendar entries did show up overnight again as I had observed in the past, so I'm up and running again.

Regarding address completion, have some some mixed news.  The good news is that it does seem to work, and work well - for something you just figured out in the last few days, that's damn impressive.

Bad news is that it conflicts with another address book add-on I use called cardbook.  When initially testing tbsync auto-completion it wasn't working, so I disabled cardbook restarted, and tbsync auto-complete worked like a champ.  Re-enabled cardbook, and tbsync stopped working.

So, that's a bummer.  I use cardbook because it effectively adds carddav support to Thunderbird, which is how I store my personal address books and share across multiple applications.  I suspect you and the cardbook developer must be using some of the same tricks to tap into the auto-complete system and they're clobbering each other.

Anyway, as far as the nature of this request, you met it.  I doubt there will be many users running both extensions like I am, so I'm fine closing this out.  Really appreciate all the work you're continuing to put into this.  Definitely makes working in an exchange environment much more tolerable.  :-)

Thanks!

**Comment by jobisoft** [comment] 2018-07-10 13:55
I can confirm this. But I am not getting any error. Hm. Will talk with Phillip about this.

**Comment by jobisoft** [comment] 2018-07-10 14:03
Found it. He clears all other autocomplete providers, when he adds himself. That must be fixed.

**Comment by jobisoft** [comment] 2018-07-10 16:53
This is a fixed version of cardbook (30.1 -> 30.1.1), so you can use both until Philippe has fixed this. You need to rename the file from zip to xpi.

[cardbook-30.1.1-tb.zip](https://github.com/jobisoft/TbSync/files/2181351/cardbook-30.1.1-tb.zip)

**Comment by jobisoft** [comment] 2018-07-10 19:03
I just wanted to get this issue closed :-) Thanks again for your donation! I have contacted Philippe already, so you do not need to file a bug report.

Glad this is working for you now.

**Closed by jobisoft** 2018-07-10 19:03 UTC
Labels: enhancement

**Comment by jobisoft** [comment] 2018-07-12 14:30
Philippe worked on the fix:
https://gitlab.com/CardBook/CardBook/issues/310#note_87639075

Could you try that version and report back?

**Comment by nitro322** [comment] 2018-07-12 14:40
Updated, tested, still working great!  Happy as can be right now.  Thanks!
