### ISSUE TITLE
O365 Calendar items not updated in O365 as accepted/declined

### ISSUE THREAD

**Issue by kimfr** [jobisoft/TbSync#362] opened 2020-02-14 09:47 UTC
## Your environment

TbSync version: 2.10
Thunderbird version: 68.4.1

[ X] Yes, I have installed the latest available (beta) version from 
https://github.com/jobisoft/TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
Once an calendar item is accepted in Thunderbird, it should update the status in your own O365 calendar as either "Accepted" or "Declined"

I would also expect that the responses would synchronize to any other instances of Thunderbird running against the same O365 account - thereby removing the appointments from the "Invitations list" and also remove the "Still needs action" flag in the Calendar view.
...

## Actual behavior
Organizing is NOT receiving a mail with "Accepted/Declined" and checking your own calendar via outlook.office365.com and/or the iPhone Outlook App - the marked as having not been RSVP'ed.

Once responded to on one PC, the other PC running Thunderbird against the same O365 still show the calendar item as "Still needs action" and it's still in the "Invitations list".
...

## Steps to reproduce
Accept an appointment via the Calendar or the Invitation list, click "Synchronize now", once completed, check your calendar via web/iPhone
...

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by jobisoft** [comment] 2020-02-14 19:41
Duplicate of https://github.com/jobisoft/EAS-4-TbSync/issues/25 or one of the other meeting issues.

**Closed by jobisoft** 2020-02-14 19:41 UTC
