### ISSUE TITLE
problem with bi-directional tb sync with gmail contacts

### ISSUE THREAD

**Issue by danielehernan** [jobisoft/TbSync#418] opened 2020-08-07 19:25 UTC
## Your environment

TbSync version: 2.12
Thunderbird version:68.11.0

[ ] Yes, I have installed the latest available beta version from 
https://tbsync.jobisoft.de
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior:BE ABLE TO SYNCHRONIZE THE CONTACTS
BIDIRECTIONALLY BETWEEN THUNDERBIRD AND G MAIL
## Actual behavior
...I can only synchronize from gmail, registrations from thunderbrd are not taken

## Steps to reproduce:                          
...first i install Provider for CalDAV y CardDAv version 1.12, after TBSync version 2.12
i create the new account with my account name in gmail, plus pasword, without server url , and he puts me this text
"the query of gmail.com did not provide the required information regarding the CalDav and CardDAV service endpoints  please entre the hostname of your server to proceed with the automatic configuration"  (event log 1)
[event log 1.txt](https://github.com/jobisoft/TbSync/files/5043047/event.log.1.txt)

if I try to put the url of the contacts, it gives me the following error "Automatic discovery od CalDAV & CardDAv service endpoint of "contacts.google.com/?hl=es&tab=mc" has failed. Try again, specifying a different serves addres, or switch to the custom configuration to manually specify the service endpoints  (event log 2)
[event log 2.docx](https://github.com/jobisoft/TbSync/files/5043074/event.log.2.docx)

If I select a "google" server profile, and enter my gmail and password account data, 

calendar data and contacts can be synchronized, but in thunderbird, I cannot remove the padlock from the contacts, that is, they are only updated only from gmail, and I have no possibility of registering / modifying in thunderbird to later be able to synchronize it with gmail.

I have tried to do the same with Gcontact Sync, but it sincronixe only 1.500 contact no more.

Thank you very much for your help

Best Regards

Daniel

**Comment by Anthony010101** [comment] 2020-09-21 06:45
Hello,

Have you found the solution? I am in the same situation.

Anthony

**Comment by Anthony010101** [comment] 2020-09-21 07:47
There she is

![Capture d’écran 2020-09-21 094630](https://user-images.githubusercontent.com/51364026/93743020-7d875c80-fbef-11ea-8b88-99df122273fb.jpg)

**Comment by jobisoft** [comment] 2020-09-21 07:52
That is not a padlock, that is an edit pen, which means you have write access. Here are pad locks:
![grafik](https://user-images.githubusercontent.com/5830621/93743295-17e7a000-fbf0-11ea-8b04-62328570f4c1.png)

Which means I have no write access to some of these resources.

**Comment by Anthony010101** [comment] 2020-09-21 07:55
I do not understand. Do you need the padlock or do you need the pen?

Thank you.

**Comment by jobisoft** [comment] 2020-09-21 07:57
In order to write changes to the google serve? You need the "pen" which stands for write access. Do you get any other errors when trying to sync changes to the google server?

**Comment by Anthony010101** [comment] 2020-09-21 07:59
No I don't see any error. If I create a contact on Google it syncs, but the reverse from Thunderbird doesn't work.

**Comment by jobisoft** [comment] 2020-09-21 08:18
hm. confirmed.

**Comment by Anthony010101** [comment] 2020-09-21 08:42
What's confirmed ?

**Comment by jobisoft** [comment] 2020-09-21 08:44
The bug you reported. I could confirm that tbsync is not sending changes to the google server. I will fix it.

**Comment by Anthony010101** [comment] 2020-09-21 08:51
Great ! Do you need log or something?

**Comment by jobisoft** [comment] 2020-09-21 08:52
No, because I confirmed it, that means I could reproduce it myself. All good. Stay tuned.

**Comment by danielehernan** [comment] 2020-09-21 19:01
Thank you very much for your help... Today i saw your comment-----
Until now the problem still exist.

**Comment by Anthony010101** [comment] 2020-09-23 10:01
Hello

Do you have an aproxymative time limit for the resolution of this bug? I have to put your plugin in productin

thank you

**Comment by Clicac** [comment] 2020-10-01 14:24
I'm having a similar issue, no sync of contacts with a CardDav Server (Baikal). 
Hope that your solution will fix this as well?
Thanks in advance!

**Comment by LivingInternet** [comment] 2020-10-02 12:10
I am having the same issue.  Contacts created in Thunderbird Address Book in the Google contacts are not synced to Google.

**Comment by LivingInternet** [comment] 2020-10-02 14:06
Fwiw I do not seem to be able to change the icon to a pen, it is stuck on the lock.  See attached:

![t3](https://user-images.githubusercontent.com/70285448/94932256-d3cd8880-0496-11eb-9a7d-5971a482b042.PNG)

**Comment by marcio32** [comment] 2020-10-07 01:58
I'm having the same problem, it doesn't synchronize the changes made in the agenda with my hotmail.

**Comment by andreasbrett** [comment] 2020-10-07 13:05
> I'm having a similar issue, no sync of contacts with a CardDav Server (Baikal).
> Hope that your solution will fix this as well?
> Thanks in advance!

Same here. Any contact I create in TB won't get synced to my Baikal server. Creating contacts on my Android smartphone (contacts synced using OpenSync) appear on my Baikal server and are synced to Thunderbird. Just uploading is not working.

**Comment by LivingInternet** [comment] 2020-10-13 12:56
Hi @jobisoft  - just wondering if you can give an update on how you think this one will go?  My new contacts are piling up in Thunderbird, but not accessible on my phone, so causing a bit of a problem, so appreciate any illumination you can provide.

**Comment by jobisoft** [comment] 2020-10-13 13:00
I have withdrawn the broken version, so no official TB78 support at the moment. I will also remove google support, as it turns out a lot of google users are the most unfriendly people I have ever met, which have a very strange demanding-everything-for-free attitude I no longer want to put up with.

**Comment by jobisoft** [comment] 2020-10-13 13:03
@LivingInternet  I was not referring to you. Personal attacks via email.

**Comment by LivingInternet** [comment] 2020-10-13 13:03
Thanks.  Fwiw, I donated to you about a month or so ago.  

So please help me understand my situation, is google support with TBSync coming back, or should I look for something else (and if so, could you be so kind as to recommend an alternative?)

**Comment by jobisoft** [comment] 2020-10-13 13:06
I have not made up my mind to 100%.
In the meantime, you can use Cardbook. I helped that author to convert his add-on.

**Comment by LivingInternet** [comment] 2020-10-13 14:03
Thanks @jobisoft - Cardbook will help with contacts, but still leaves me hanging on Calendar.  Hope you get TBSync working again for that.  If not, any recommendations for other solutions will be very welcome.

**Comment by jobisoft** [comment] 2020-10-16 11:51
I uploaded a new version for TB78 via my beta release channel. Please give it a good spin. 

https://github.com/jobisoft/TbSync/wiki/Get-the-latest-TbSync-version#beta-release-channel

I will close this issue. Open a new one if you run into errors, but please check first, if someone else has already created a new issue.

**Closed by jobisoft** 2020-10-16 11:51 UTC
Labels: bug

**Comment by bartosz-antosik** [comment] 2020-10-16 16:49
Thank you for pushing this despite your concerns you mentioned above, in the thread. Much appreciated.

It seems to be working.

There is one thing, not a bug I reckon: it does not synchronize (from TB to Google Contacts) contacts that were created when it was not synchronizing them (last couple of days). It does synchronize them when I delete & re-create them. I have not had too many of them so that's not a big deal, mostly because I remembered which were those recently added of course.

**Comment by andreasbrett** [comment] 2020-10-16 17:13
> There is one thing, not a bug I reckon: it does not synchronize (from TB to Google Contacts) contacts that were created when it was not synchronizing them (last couple of days). It does synchronize them when I delete & re-create them. I have not had too many of them so that's not a big deal, mostly because I remembered which were those recently added of course.

Have you tried creating a local addressbook in thunderbird and moving those contacts over there and back again to your Google contacts address book? Would be much quicker than recreating.

**Comment by bartosz-antosik** [comment] 2020-10-16 17:16
@andreasbrett Clever! I have local addressbook, of course, just haven't had this bright idea!

The real trouble is how to identify those not yet synchronized items, because they pass silently while synchronizing.

**Comment by andreasbrett** [comment] 2020-10-16 17:18
That trouble is also easily solved: move all of them to the local addressbook and back ;-)

**Comment by jobisoft** [comment] 2020-10-16 17:19
> Have you tried creating a local addressbook in thunderbird and moving those contacts over there and back again to your Google contacts address book? Would be much quicker than recreating.

You might lose additional information stored in those contacts, which cannot be stored in standard addressbooks, so I would not do that. But you can use the category manager to fully export them and reimport them.

**Comment by bartosz-antosik** [comment] 2020-10-16 17:21
@andreasbrett Exactly what @jobisoft said - even properties boxes are different in those two addressbooks.

**Comment by jobisoft** [comment] 2020-10-16 17:21
thinking about it, I would also not use the catman.

**Comment by jobisoft** [comment] 2020-10-16 17:22
I will think of something.

**Comment by LivingInternet** [comment] 2020-10-17 11:33
Thanks John.
