### ISSUE TITLE
Feature request: Have error icon on global status bar of thunderbird

### ISSUE THREAD

**Issue by satnamram** [jobisoft/TbSync#216] opened 2019-01-15 13:07 UTC
TbSync version: 0.7.22 (via addon installer in thunderbird)
Thunderbird version: 60.2.1 (from Linux Mint 19 repository)

## Expected behavior
On certificate issues, show error icon in bottom status bar of thunderbird,

## Actual behavior
Currently, I get an error in the tbsync view, but not in the overall bottom status bar. 
It just stood still with 'TbSync: Idle', as is also the case when everything is alright.

Since I have 'sync every one minute' enabled, I did not see that something was wrong 
until someone told me that I missed an appointment.

## Steps to reproduce
Run against an ActiveSync server (v14.0) that exhibits an illegal certificate

**Comment by jobisoft** [comment] 2019-01-15 13:10
Can you provide a test account on such an EAS Server? I do not have any server where I could invalidate the cert. Credentials via email.

**Comment by jobisoft** [comment] 2019-01-15 13:48
Also, could you try if it is fixed in beta already (by accident)?
https://tbsync.jobisoft.de

**Comment by jobisoft** [comment] 2019-01-22 18:23
Can you provide feedback? There is a global error indicator in the lower right corner. I am not able to reproduce your issue. I have a server with self signed certs and I removed the exception and got the error as expected...

**Closed** 2019-01-27 15:34 UTC
Labels: bug
