### ISSUE TITLE
ActiveSync Freezes when adding account if domain returns unauthorised

### ISSUE THREAD

**Issue by Cousjava** [jobisoft/TbSync#25] opened 2017-12-04 14:57 UTC
When adding an account, if the server returns a unauthorised response when doing the configuration TbSync freezes and requires thunderbird to be manually killed. Note this is not the point of incorrect username or password, but connecting to the Activesync xml.

**Comment by jobisoft** [comment] 2017-12-04 16:40
What is an unauthorised response, besides wrong username/password? How can I reproduce that?

**Comment by Cousjava** [comment] 2017-12-04 17:08
http://autodiscover.aston.ac.uk/autodiscover/autodiscover.xml

**Comment by jobisoft** [comment] 2017-12-04 18:24
Cannot reproduce. Maybe if you can provide username and password, so I can run autodiscover as intended. If you can provide them, send me an email, do not post them here.

**Comment by jobisoft** [comment] 2017-12-30 22:53
I retried with the latest beta, using "john@aston.ac.uk" to force Tbsync to try the above url. It is the second url it tries and it does "freeze" for about 10s and then I get a password prompt. The 10s are the timeout of the response.

I do not see a problem here. Can I close this?

**Closed** 2018-01-02 16:29 UTC
