### ISSUE TITLE
Periodic sync issue

### ISSUE THREAD

**Issue by misar1** [jobisoft/TbSync#420] opened 2020-08-17 10:55 UTC
## Your environment

TbSync version: 2.12
Thunderbird version: 68.11.0 (64 bit)
Provider for Exchange ActiveSync: 1.14
Windows 10 (64 bit, Ver 1909)

I am using TbSync with an outlook.com calendar. There seems to be an intermittent problem when I enable Periodic Sync (10 minutes).

From time to time the calendar loses all entries. This seems to happen at random and I cannot identify a specific action which may cause it. However, I have TB on several PCs and it occurs on all of them.

On inspection of the TbSync status for the Outlook connection, calendar has disappeared from the usual list of three resources and the other two (never used) are greyed out. It can be restored by deselecting "Enable and synchronize this account" then selecting it again. A manual sync then restores the calendar entries.

I have never seen this issue if I leave Periodic Sync on 0 and do a manual sync when required.

**Comment by templis** [comment] 2020-08-20 14:01
I have also this issues:

TbSync version: 2.16
Thunderbird version: 78.1.1 (32 bit)
Provider for Exchange ActiveSync: 1.16
Windows 10 (64 bit, Ver 1909 (Build 18363.1016))

**Comment by jobisoft** [comment] 2020-08-23 18:14
The reason for that is that your server sometimes reports no resources. In periodic sync you hit that more often than in manual sync.
TbSync than thinks the resource has been removed. No idea how to fix this currently.

**Comment by misar1** [comment] 2020-08-23 18:38
Thanks for the explanation. 
Hope you can find a solution because it is annoying when you have created a new event to upload and need to do it again. There must be one because other calendar apps sometimes encounter the same situation without behaving this way.

**Comment by jobisoft** [comment] 2020-08-23 18:55
I am running in so many issues with Outlook.com, that I consider dropping support actually.

**Comment by misar1** [comment] 2020-08-23 19:36
That would be a shame because otherwise TbSync works very well. I don't think you have much competition - Provider for Microsoft Exchange was last updated in 2012.

**Comment by templis** [comment] 2020-09-08 07:17
> I am running in so many issues with Outlook.com, that I consider dropping support actually.
Thats not entirely outlook.com related. I have had this issue with my own mailcow/sogo Provider.
But beside that - I have to agree, that the microsoft freemail (Outlook.com, etc.) is a piece of sh.... and nobody should use that :) 

I was able to fix it with creating a new profile. The issue is now gone and my calenders are syncing like a charm. 👍

**Comment by jobisoft** [comment] 2020-09-12 09:54
@misar1 : Is your situation improving, if you create a fresh profile like @templis did? 

Are you using multiple accounts, so TbSync could get "mixed" up and think a response from account A was for account B and because account B has different folders than account A it may deactivate/remove all folders of account B? In a next sync TbSync would then get the correct list again, but has all folders disabled...

**Comment by misar1** [comment] 2020-09-13 07:15
@jobisoft, I was only using one account (outlook.com) with TbSync but your comment reminded me of something else. 

I previously used Google Calendar and forgot that Provider for Google Calendar was still enabled and syncing. I disabled it and that seems to have fixed the problem. After testing for some time both auto and manual sync have been OK.

Thanks for your help and apologies for any confusion.

**Comment by BenoitSvB** [comment] 2020-11-10 07:20
Sync error with my Nextcloud:

Component returned failure code: 0x8000ffff (NS_ERROR_UNEXPECTED) [nsIPrefBranch.getCharPref]

promisifiedHttpRequest/<@chrome://dav4tbsync/content/includes/network.js:515:64
promisifiedHttpRequest@chrome://dav4tbsync/content/includes/network.js:494:12
sendRequest@chrome://dav4tbsync/content/includes/network.js:428:33

Component returned failure code: 0x8000ffff (NS_ERROR_UNEXPECTED) [nsIPrefBranch.getCharPref]

promisifiedHttpRequest/<@chrome://dav4tbsync/content/includes/network.js:515:64
promisifiedHttpRequest@chrome://dav4tbsync/content/includes/network.js:494:12
sendRequest@chrome://dav4tbsync/content/includes/network.js:428:33

I can access my calendar with my browser (Firefox) and do not see the cause.

**Comment by jobisoft** [comment] 2020-11-10 07:25
Please update your add-ons, should be fixed in latest release 1.24 of the CalDAV & CardDAV provider. Can you confirm?

**Comment by BenoitSvB** [comment] 2020-11-10 07:36
Thank you for your lightning-fast reply; although I had automatic update set to "standard" I had to manually remove and reinstall the add-on. I can confirm the problem was solved after the update.

**Closed** 2020-11-10 07:37 UTC
