### ISSUE TITLE
HTTP 500 when trying to connect to owncloud

### ISSUE THREAD

**Issue by molle503** [jobisoft/TbSync#344] opened 2019-12-05 18:51 UTC
## Your environment

TbSync version: 2.8/11-29-2019
Thunderbird version: 68.3.0
ownCloud 10.3.0 (stable) 

[ ] Yes, I have installed the latest available (beta) version from 
https://github.com/jobisoft/TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
logon to my owncloud server as before. Worked until I updated Thunderbird

## Actual behavior
URL:
https://myserver/cloud/remote.php/dav/principals/users/myname/ (PROPFIND)

Request:
<d:propfind xmlns:d="DAV:" xmlns:cal="urn:ietf:params:xml:ns:caldav" xmlns:cs="http://calendarserver.org/ns/"><d:prop><cal:calendar-home-set /><cs:calendar-proxy-write-for /><cs:calendar-proxy-read-for /><d:group-membership /></d:prop></d:propfind>

Response:
<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>TypeError</s:exception>
  <s:message>explode() expects parameter 2 to be string, null given</s:message>
</d:error>

## Steps to reproduce
just start to connect to owncloud.

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by jobisoft** [comment] 2019-12-05 18:54
Duplicate of https://github.com/jobisoft/DAV-4-TbSync/issues/164

**Closed by jobisoft** 2019-12-05 18:54 UTC
