### ISSUE TITLE
How to access the Options Dialog?

### ISSUE THREAD

**Issue by gogolo2** [jobisoft/TbSync#491] opened 2021-01-29 15:03 UTC
## Your environment

TbSync version: 2.20
Thunderbird version: 78.7.0

## Expected behavior
Should show the addon options dialog and the Synchronization settings (TbSync)

## Actual behavior
Non shown

thx!

**Comment by jobisoft** [comment] 2021-03-18 19:47
Duplicate of #462

**Closed by jobisoft** 2021-03-18 19:47 UTC
