### ISSUE TITLE
Error Parsing Calendar Data

### ISSUE THREAD

**Issue by shanemeagher** [jobisoft/TbSync#4] opened 2017-03-15 11:23 UTC
After configuring to connect to an outlook.com account, the first synchronisation stalls on the first calendar. From reviewing the logs in the Error console, it appears that TbSync has an issue where there is a symbol in the text of a calendar entry.

The first instance was in an entry where the body of the entry had a url with variables appended:
`<Body xmlns='Calendar'>http://m.ovi.me/B8AeHQjnueBQ&_s=Xxxxx%2520Xx%25206&_ci=Xxxxx&_co=Xxxxxxxxx&_zi=0000&_cx=XXX&_ln=0%2520Xxxxx%2520Xx</Body>`.
I got past this by adding extra text to the body after the url:
`<Body xmlns='Calendar'>http://m.ovi.me/B8AeHQjnueBQ&_s=Xxxxx%2520Xx%25206&_ci=Xxxxx&_co=Xxxxxxxxx&_zi=0000&_cx=XXX&_ln=0%2520Xxxxx%2520Xx
Extra Test Text</Body>`

The second instance was in an entry where the subject of the entry had an "&".
![image](https://cloud.githubusercontent.com/assets/2144292/23945721/8d6bb642-09b2-11e7-8553-209075364daa.png)
Changing the "&" to "and" allowed this entry to parse. The third try failed due to an identical issue.

Could there be an issue with how such characters are processed?

Let me know if there is any specific debugging I can do to provide more info.

**Comment by jobisoft** [comment] 2017-03-18 21:30
Thanks for the report, I will fix that over the next week!

**Comment by jobisoft** [comment] 2017-03-21 22:20
Bug confirmed. 

I use parseFromString(str, "text/xml") of the Components.interfaces.nsIDOMParser to parse the response from the server and that parser is sensitive to html entities (for example &nbsp;) and throws on "bad" entities, so basically every & which is not followed by a valid entity.

Looking for a solution.

**Comment by jobisoft** [comment] 2017-03-23 14:58
Could you checkout 0.6.5? It includes fixes for you, but also some other changes I was working on. I hope everything is fine.

https://github.com/jobisoft/TbSync/releases/tag/v0.6.5

**Comment by shanemeagher** [comment] 2017-03-24 07:31
From first look, I think this is having issues with the @ symbol also (in this case, it is an email address in the description of an event.).  I'll investigate further but I've nil experience in javascript unfortunately.

**Comment by jobisoft** [comment] 2017-03-24 08:16
Thanks, I will look into it as well. Your feedback is very helpful!

Yours
John


Am 24.03.2017 um 08:31 schrieb Shane:

**Comment by jobisoft** [comment] 2017-03-24 08:33
I could not verify problems with @ in description. I found the following 
chars, which are special to XML:

|" &quot; ' &apos; < &lt; > &gt; & &amp; Is there any of these symbols in 
that failing description? Could you provide the full description? If you 
remove the problematic chars from the description, does it work again? 
Thanks, John|

**Comment by shanemeagher** [comment] 2017-03-24 10:24
Your likely correct. The full error description is:
```
Timestamp: 24/03/17 17:55:48
Error: not well-formed
Source File: moz-nullprincipal:{7c321fb3-b8ba-4f29-9590-fe2c02918cac}
Line: 60, Column: 1093
Source Code:
</Body><Sensitivity xmlns='Calendar'>0</Sensitivity><BusyStatus xmlns='Calendar'>2</BusyStatus><AllDayEvent xmlns='Calendar'>0</AllDayEvent><MeetingStatus xmlns='Calendar'>0</MeetingStatus></ApplicationData></Add><Add><ServerId>gnuRyIzxC0WkvcYMIJHp_wAAAAABDYJ7kciM8QtFpL3GDCCR6f8AAAAA8Rc1</ServerId><ApplicationData><TimeZone xmlns='Calendar'>IP7//1cALgAgAEEAdQBzAHQAcgBhAGwAaQBhACAAUwB0AGEAbgBkAGEAcgBkACAAVABpAG0AZQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACgAVQBUAEMAKwAwADgAOgAwADAAKQAgAFAAZQByAHQAaAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==</TimeZone><DtStamp xmlns='Calendar'>20161021T073452Z</DtStamp><StartTime xmlns='Calendar'>20150818T003000Z</StartTime><Subject xmlns='Calendar'>House Inspection</Subject><UID xmlns='Calendar'>844220a9-c206-4816-8201-6fd9f845ddfc</UID><OrganizerName xmlns='Calendar'>Shane Meagher</OrganizerName><OrganizerEmail xmlns='Calendar'>shanemeagher@xxxxxxx.com</OrganizerEmail><Location xmlns='Calendar'>Home</Location><EndTime xmlns='Calendar'>20150818T023000Z</EndTime><Body xmlns='Calendar'>From: FirstName LastName <Xxxxxx@xxxxxxxxxxxxxx.com.au>
```

The entry body has the header from an email. The error points to the `From:` line so it is possible that it is the "<" which is causing the error, not the @.

**Comment by jobisoft** [comment] 2017-03-24 11:08
Ok, I hope I fixed it now for good.

https://github.com/jobisoft/TbSync/releases/tag/0.6.5

I did not bump the version number, but this one should escape all five special xml chars.

Does it work?

**Comment by jobisoft** [comment] 2017-03-24 19:56
I bumped it now indeed:
https://github.com/jobisoft/TbSync/releases/tag/v0.6.6

Could you confirm, that the bug(s) are fixed now?

**Comment by shanemeagher** [comment] 2017-03-24 23:06
I've tried the 0.6.5_1 version and this seems to get me past the issue with special characters. All calendar entries load and the contacts are being loaded, although I now get a connection timeout before completion. Will dig into the log late to see if I can get more info but looks like this issue is fixed. Will start a new issue if I can narrow down the problem.

**Comment by shanemeagher** [comment] 2017-03-25 09:48
Have tried with 0.6.6. Calendar entries sync okay but contacts consistently suffers from a "Connection Timeout". There is very little shown in the Console input except for:
`[TbSync] finishSync(): Error @ Account #2 : Communication timeout.`
and
`Timestamp: 25/03/17 15:37:48`
`Error: TypeError: folder is null`
`Source File: chrome://tbsync/content/provider/eas/db.js`
`Line: 407`

wbxml-debug.log makes no reference to a connection timeout. Let me know if I should raise it as a new issue.

**Comment by jobisoft** [comment] 2017-03-25 09:51
That error helps. Looking into it. No need for a new issue.


Am 25.03.2017 um 10:48 schrieb Shane:

**Comment by jobisoft** [comment] 2017-03-25 09:54
Any chance you could write directly at john.bieling@gmx.de? I have a 
question which should not be out in the open.

Yours
John

**Comment by jobisoft** [comment] 2017-04-13 21:31
OK, I think I fixed the timeout problem. On some servers, the receiving phase is very long because they send contacts one by one instead of in a single response. I will add visual feedback later but for now I just write something into the console on each response. 

I hope it works now for you.

**Comment by shanemeagher** [comment] 2017-04-15 04:59
This fixes the timeout problem for me. Thanks.

**Closed** 2017-04-15 09:51 UTC
