### ISSUE TITLE
Deleting single items of recurring appointment not synced from Thunderbird to server

### ISSUE THREAD

**Issue by Manuel1948** [jobisoft/TbSync#435] opened 2020-09-24 15:57 UTC
TbSync version: 2.12
Thunderbird version: 68.12.0 (32-Bit)
Provider for Exchange Active Sync: 1.14
Mailserver: Kopano 
WebApp: 3.4.6+dfsg1-1
Kopano Core: 8.5.5

Problem:
If I delete a single item of a recurring appointment in Thunderbird it should be synced by TbSync to the server, but this doesn't work, the items are still existing on the server afetr the sync. From the server to Thunderbird changes will be synced.

Debug.log sent from suedwind.at mail adress.

**Comment by Oxalin** [comment] 2020-10-09 17:22
This could be related to #436 and #399 (both flagged against Google services, but there is something similar)

**Comment by jobisoft** [comment] 2020-10-16 13:16
Fixed in latest beta?
https://github.com/jobisoft/TbSync/wiki/Get-the-latest-TbSync-version#beta-release-channel

**Comment by michgagnon** [comment] 2020-10-16 16:17
Not the OP, but I was about to report the same problem when updating a single event from a repeating event in a Google Calendar

My system:
Windows 10
Thunderbird 78.3.2
TBSync 2.12
Provider for CalDav and CardDav : 1.19
Provider for Exchange : 1.18 (irrelevant, I think)


STEPS TO REPRODUCE:
1. Create a repeating event in a Google Calendar.
    Save and quit (everything is OK so far).
2. At some time in the future (i.e. after one or two synchronizations), click on an event to edit it.
    Edit one occurence as a single event.
    Things seem to go well so far
3. Quit Thunderbird. OK.
4. Restart Thunderbird.
At this point, I get the following error message: "This item has recently been changed on the server. Submitting your changes will overwrite the changes made on the server." Neither the two buttons work. (and no information as to which event triggers the error message).
I can temporarily dismiss the error message by closing it with the close box.... it will reappear at next sync 30 minutes later.

WORKAROUNDS:
1. Unsusbscribe from the offending agenda, then resubscribe to it. The agenda will be fine (and no further error message) but not updated.
2. To update the single item on the agenda, use the Google Calendar web interface. The event will then be correctly on the web, and at next sync, in Thunderbird also.

ADDITIONAL NOTE:
Even when changed via Google, the event is still considered part of a series, i.e. it cannot be changed a second time in Thunderbird with TBsync


UPDATE – WITH THE LATEST BETA (2020-10-16)
TbSync 2.18
Provider for CalDav and CardDav 1.21
Provider for EAS 1.20

Slightly different behaviour, but not correct either, as I block in step 2 (from above):
2. At some time in the future (i.e. after one or two synchronizations), click on an event to edit it.
    Edit one occurence as a single event.
2b. When closing (Close and save), I get the following error message: "This item has recently been changed on the server. Submitting your changes will overwrite the changes made on the server."
2c. The only option that works is to cancel changes.

Obviously, this is slightly better as there are no further issues down the road. However, to change a single item, I still have to use workaround 2 (above).

**Comment by Manuel1948** [comment] 2020-10-29 15:28
> Fixed in latest beta?
> https://github.com/jobisoft/TbSync/wiki/Get-the-latest-TbSync-version#beta-release-channel

Hi, thank you for asking, two minutes before I tested it. The sync to the server is now working, but if I open the calendar on another computer (also with the new beta version), Thunderbird doesn't get the changes for single elements.

One thing I remeber, on the second computer I forgot to install the DAV beta xpi (does I need this even when I didn't used it before?)

**Comment by lorenzk1** [comment] 2020-11-27 16:52
Since two days confirmations of single items of recurring calender events are synced properly.
No idea, why it works now and did not work in the last months. Maybe Google changed something...
Actual Thunderbird 78.5.0 (64-Bit), extensions.dav4tbsync.googlesupport;true
TBSync (not beta...) 2.19 form 11/19
Provider für CalDAV & CardDAV 1.24 from 11/21

Thanks for great extensions, jobisoft!

**Comment by lorenzk1** [comment] 2020-12-04 18:46
Sorry to say: After a few days the problems are back.
It seems to me, that these issues might have nothing to do with tbsync etc. but with some Google-policies. At least I do not understand, what's going on. The situation reminds me of a problem with gContactSync several years ago after a change in Google-Api, when suddenly all hit rates counted to the developer instead of the costumer...

With "reminders" turned off and after re-sync everything is working fine again.

**Comment by jobisoft** [comment] 2022-09-21 08:30
I no longer support google.

**Closed by jobisoft** 2022-09-21 08:30 UTC
Labels: fixed in beta?
